- titus-common/src/main/java/com/netflix/titus/common/framework/reconciler/EntityHolder.java
- titus-common/src/main/java/com/netflix/titus/common/framework/reconciler/internal/DefaultReconciliationFramework.java
- titus-common/src/test/java/com/netflix/titus/common/framework/reconciler/EntityHolderTest.java
- titus-common/src/test/java/com/netflix/titus/common/framework/reconciler/internal/DefaultReconciliationFrameworkTest.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/JobReconciliationFrameworkFactory.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/common/action/TaskTimeoutChangeActionsTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/scenario/JobsScenarioBuilder.java
This change includes also performance improvements in the EntityHolder class.
> Run job reconciliation framework on its own thread

- build.gradle
- titus-common/src/main/java/com/netflix/titus/common/framework/reconciler/internal/CompositeTransaction.java
- titus-common/src/main/java/com/netflix/titus/common/framework/reconciler/internal/EmptyTransaction.java
- titus-common/src/main/java/com/netflix/titus/common/framework/reconciler/internal/FailedTransaction.java
- titus-common/src/main/java/com/netflix/titus/common/framework/reconciler/internal/InternalReconciliationEngine.java
- titus-common/src/main/java/com/netflix/titus/common/framework/reconciler/internal/SingleTransaction.java
- titus-common/src/main/java/com/netflix/titus/common/framework/reconciler/internal/Transaction.java
- titus-common/src/main/java/com/netflix/titus/common/util/code/RecordingCodeInvariants.java
- titus-common/src/main/java/com/netflix/titus/common/util/guice/internal/ActivationProvisionListener.java
* Upgrade dependencies
* Add headers
* Add error to log statements
> Minor improvements

- PULL_REQUEST_TEMPLATE.md
... encouraging contributors to write at least one sentence explaining why/what changes are being made.
> Initial (very simple) PR template

- titus-api/src/main/java/com/netflix/titus/api/loadbalancer/model/sanitizer/DefaultLoadBalancerJobValidator.java
- titus-api/src/main/java/com/netflix/titus/api/loadbalancer/service/LoadBalancerException.java
- titus-api/src/test/java/com/netflix/titus/api/loadbalancer/model/sanitizer/DefaultLoadBalancerJobValidatorTest.java
- titus-api/src/test/java/com/netflix/titus/api/loadbalancer/service/LoadBalancerExceptionTest.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/endpoint/rest/JerseyModule.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/endpoint/JerseyModule.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/v3/rest/LoadBalancerResource.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/v3/rest/RestConstants.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/v3/rest/RestUtil.java
- titus-server-runtime/src/test/java/com/netflix/titus/runtime/endpoint/v3/rest/LoadBalancerResourceTest.java
The Load Balancer API only had a gRPC interface.  This PR adds the accompanying REST API.
> [TITUS-2268] Add load balancer REST API

- titus-common/src/main/java/com/netflix/titus/common/util/code/CodeInvariants.java
- titus-common/src/main/java/com/netflix/titus/common/util/code/LoggingCodeInvariants.java
Improvements to two classes in the `com.netflix.titus.common.util.code` package.
> CodeInvariants-related improvements

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/ContainerResources.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/sanitizer/JobConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/service/management/CapacityManagementConfiguration.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/TitusEntitySanitizerModule.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/model/job/ContainersGenerator.java
Update the min disk resource dimension to 10GB
Update the max disk resource dimension to 1TB
> update the min and max disk resource dimensions used by validators

- titus-server-gateway/src/main/java/com/netflix/titus/gateway/endpoint/v3/rest/AgentManagementResource.java
- titus-server-master/src/main/java/com/netflix/titus/master/taskmigration/TaskMigrationDetails.java
- titus-server-master/src/main/java/com/netflix/titus/master/taskmigration/V2TaskMigrationDetails.java
- titus-server-master/src/main/java/com/netflix/titus/master/taskmigration/V3TaskMigrationDetails.java
* Add explicit contract to determine whether or not a task migration details object is self managed.
* Fix path param in getAgentInstance API.
> Small improvements

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/sanitizer/JobAssertions.java
- titus-api/src/test/java/com/netflix/titus/api/jobmanager/model/job/sanitizer/JobAssertionsTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/JobSubmitAndControlNegativeTest.java
Implement validation rules according to spec (https://github.com/docker/distribution/blob/master/reference/reference.go)
> Fix the image digest validation pattern

- titus-common/src/main/java/com/netflix/titus/common/util/archaius2/Archaius2ConfigurationLogger.java
Logging with log4j from within the archaius visitor callback may result in a deadlock, as both log4j and archaius access System.props Hashtable which has synchronized access.
> Move property logging out of the visitor code to avoid the deadlock

- titus-ext/cassandra-testkit/src/main/java/com/netflix/titus/ext/cassandra/testkit/store/EmbeddedCassandraStoreFactory.java
- titus-ext/cassandra/src/main/java/com/netflix/titus/ext/cassandra/store/CassandraJobStore.java
- titus-ext/cassandra/src/main/java/com/netflix/titus/ext/cassandra/store/CassandraStoreConfiguration.java
- titus-ext/cassandra/src/main/java/com/netflix/titus/ext/cassandra/tool/command/TestStoreLoadCommand.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/JobReconciliationFrameworkFactory.java
* add configuration to turn on cassandra query tracing
* log loaded jobs/tasks on initialization
> Visibility Improvements

- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/agent/replicator/GrpcAgentReplicatorEventStream.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/common/replicator/AbstractReplicatorEventStream.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/common/replicator/RetryableReplicatorEventStream.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/eviction/replicator/GrpcEvictionReplicatorEventStream.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/jobmanager/replicator/GrpcJobReplicatorEventStream.java
Additional logging in the stream replication connectors, that should help diagnose
reoccurring stability issues.
> Add more logging in the replicating connectors

- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/common/replicator/RetryableReplicatorEventStream.java
- titus-server-runtime/src/test/java/com/netflix/titus/runtime/connector/common/replicator/RetryableReplicatorEventStreamTest.java
Bug fix in `RetryableReplicatorEventStream`.
> Fix the retry logic in RetryableReplicatorEventStream

- titus-server-master/src/main/java/com/netflix/titus/master/appscale/service/DefaultAppScaleManager.java
- titus-server-master/src/test/java/com/netflix/titus/master/appscale/endpoint.v3/grpc/DefaultAutoScalingServiceGrpcTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/appscale/service/DefaultAppScaleManagerTest.java
Deprecating V2 engine integration (also RxEventBus) code
> removing v2 references

- titus-common/src/main/java/com/netflix/titus/common/util/rx/SchedulerExt.java
- titus-server-master/src/main/java/com/netflix/titus/master/clusteroperations/ClusterAgentAutoScaler.java
- titus-server-master/src/main/java/com/netflix/titus/master/clusteroperations/ClusterOperationFunctions.java
- titus-server-master/src/main/java/com/netflix/titus/master/clusteroperations/ClusterOperationsConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/clusteroperations/ClusterRemovableAgentRemover.java
- titus-server-master/src/main/java/com/netflix/titus/master/clusteroperations/ClusterRemovableInstanceGroupAgentRemover.java
- titus-server-master/src/main/java/com/netflix/titus/master/clusteroperations/TierAutoScalingConfiguration.java
- titus-server-master/src/test/java/com/netflix/titus/master/clusteroperations/ClusterAgentAutoScalerTest.java
* fix bugs
* add grace period for idle instances to prevent scale down of new instances
* calculate resource dimensions to get an estimate of how many instances are needed
> Experimental Auto Scaler Improvements

- titus-server-master/src/main/java/com/netflix/titus/master/agent/service/DefaultAgentManagementService.java
- titus-server-master/src/main/java/com/netflix/titus/master/clusteroperations/ClusterAgentAutoScaler.java
- titus-server-master/src/test/java/com/netflix/titus/master/agent/service/DefaultAgentManagementServiceTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/clusteroperations/ClusterAgentAutoScalerTest.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/model/agent/AgentGenerator.java
Fix auto scaler scale down logic to take into account instance group min
> fix scale down logic to take into account instance group min

- titus-server-master/src/test/java/com/netflix/titus/master/clusteroperations/ClusterRemovableAgentRemoverTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/clusteroperations/ClusterRemovableInstanceGroupAgentRemoverTest.java
Fix the failing cluster auto scaler tests
> fix the failing tests

- titus-server-master/src/main/java/com/netflix/titus/master/clusteroperations/ClusterAgentAutoScaler.java
- titus-server-master/src/test/java/com/netflix/titus/master/clusteroperations/ClusterAgentAutoScalerTest.java
Exclude non primary instance type instance groups from cluster auto scaling.
> exclude non primary instance type instance groups from scaling

- titus-common/src/main/java/com/netflix/titus/common/util/StringExt.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/DefaultV3TaskInfoFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/MesosConfiguration.java
* Send fully qualified image to the executor based on the configured registry url
> send fully qualified image to executor

- build.gradle
- titus-common/src/main/java/com/netflix/titus/common/util/rx/FluxObservableEmitter.java
- titus-common/src/main/java/com/netflix/titus/common/util/rx/ReactorExt.java
- titus-common/src/main/java/com/netflix/titus/common/util/rx/ReactorReEmitterOperator.java
- titus-common/src/main/java/com/netflix/titus/common/util/rx/RetryHandlerBuilder.java
- titus-common/src/test/java/com/netflix/titus/common/util/rx/ReactorReEmitterOperatorTest.java
- titus-common/src/test/java/com/netflix/titus/common/util/rx/ReactorRetryHandlerBuilderTest.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/agent/AgentSnapshot.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/agent/replicator/AgentDataReplicatorProvider.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/agent/replicator/GrpcAgentReplicatorEventStream.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/common/replicator/AbstractReplicatorEventStream.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/common/replicator/DataReplicator.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/common/replicator/DataReplicatorDelegate.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/common/replicator/ReplicatorEventStream.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/common/replicator/RetryableReplicatorEventStream.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/common/replicator/StreamDataReplicator.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/eviction/replicator/EvictionDataReplicatorProvider.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/eviction/replicator/GrpcEvictionReplicatorEventStream.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/jobmanager/JobSnapshot.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/jobmanager/replicator/GrpcJobReplicatorEventStream.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/jobmanager/replicator/JobDataReplicatorProvider.java
- titus-server-runtime/src/test/java/com/netflix/titus/runtime/connector/agent/replicator/GrpcAgentReplicatorEventStreamTest.java
- titus-server-runtime/src/test/java/com/netflix/titus/runtime/connector/common/replicator/RetryableReplicatorEventStreamTest.java
- titus-server-runtime/src/test/java/com/netflix/titus/runtime/connector/common/replicator/StreamDataReplicatorTest.java
- titus-server-runtime/src/test/java/com/netflix/titus/runtime/connector/jobmanager/replicator/GrpcJobReplicatorEventStreamTest.java
- titus-supplementary-component/task-relocation/src/main/java/com/netflix/titus/supplementary/relocation/startup/TaskRelocationModule.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/model/agent/AgentDeployment.java
Refactoring (RxJava -> Spring Reactor)
> Port the task relocation component to Spring Reactor

- titus-common/src/test/java/com/netflix/titus/common/jhiccup/sensor/RxJavaComputationSchedulerSensorTest.java
The test is time sensitive, and the configured probing interval was sometimes too short.
> Fix the flaky test in RxJavaComputationSchedulerSensorTest

- titus-server-master/src/main/java/com/netflix/titus/master/agent/service/cache/InstanceCache.java
- titus-server-master/src/test/java/com/netflix/titus/master/agent/service/cache/InstanceCacheTest.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/stub/connector/cloud/TestableInstanceCloudConnector.java
> InstanceCache should fail on startup, if the AWS connector times out

- titus-api/src/main/java/com/netflix/titus/api/containerhealth/model/ContainerHealthState.java
- titus-api/src/main/java/com/netflix/titus/api/containerhealth/model/ContainerHealthStatus.java
- titus-api/src/main/java/com/netflix/titus/api/containerhealth/model/event/ContainerHealthChangeEvent.java
- titus-api/src/main/java/com/netflix/titus/api/containerhealth/model/event/ContainerHealthEvent.java
- titus-api/src/main/java/com/netflix/titus/api/containerhealth/model/event/ContainerHealthSnapshotEvent.java
- titus-api/src/main/java/com/netflix/titus/api/containerhealth/service/ContainerHealthService.java
> Initial version of the container health API

- titus-testkit/src/main/java/com/netflix/titus/testkit/cli/CLI.java
Allow more specialized CLIs to override builtin commands, and add new ones.
> allow commands to be modified by subclasses

- build.gradle
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/JobDescriptor.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/disruptionbudget/AvailabilityPercentageLimitDisruptionBudgetPolicy.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/disruptionbudget/ContainerHealthProvider.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/disruptionbudget/Day.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/disruptionbudget/DisruptionBudget.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/disruptionbudget/DisruptionBudgetPolicy.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/disruptionbudget/DisruptionBudgetRate.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/disruptionbudget/HourlyTimeWindow.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/disruptionbudget/PercentagePerHourDisruptionBudgetRate.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/disruptionbudget/RelocationLimitDisruptionBudgetPolicy.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/disruptionbudget/SelfManagedDisruptionBudgetPolicy.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/disruptionbudget/TimeWindow.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/disruptionbudget/UnhealthyTasksLimitDisruptionBudgetPolicy.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/disruptionbudget/UnlimitedDisruptionBudgetRate.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/store/mixin/JobDescriptorMixin.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/v3/grpc/V3GrpcModelConverters.java
Add job disruption core models and converters between grpc and core.
> add job disruption budget core models and converters

- README.md
- titus-ext/runner/titusgateway.properties
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/endpoint/v3/SupplementaryServiceLocationConfiguration.java
* Add missing @Inject and @Singleton to SupplementaryServiceLocationConfiguration
* Rename titus.gateway.* properties to titus.masterClient.*
Fixes #384
> Fix local docker-compose workflow.

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/Container.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/sanitizer/JobAssertions.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/sanitizer/JobConfiguration.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/sanitizer/JobSanitizerBuilder.java
- titus-api/src/test/java/com/netflix/titus/api/jobmanager/model/job/sanitizer/JobAssertionsTest.java
- titus-api/src/test/java/com/netflix/titus/api/jobmanager/model/job/sanitizer/JobModelSanitizationTest.java
Too large entry point causes container to crash immediately.
> Limit entry point size to 16KB

- titus-server-master/src/main/java/com/netflix/titus/master/taskmigration/V3TaskMigrationDetails.java
- titus-server-master/src/main/java/com/netflix/titus/master/taskmigration/job/ServiceJobTaskMigrator.java
Fix task migration code to properly handle when a task no longer exists.
> Fix task migration

- titus-api/src/main/java/com/netflix/titus/api/eviction/service/EvictionOperations.java
- titus-api/src/main/java/com/netflix/titus/api/eviction/service/ReadOnlyEvictionOperations.java
- titus-common/src/main/java/com/netflix/titus/common/util/rx/ReactorExt.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/eviction/EvictionResource.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/eviction/GatewayGrpcEvictionService.java
- titus-server-master/src/main/java/com/netflix/titus/master/eviction/endpoint/grpc/GrpcEvictionService.java
- titus-server-master/src/main/java/com/netflix/titus/master/eviction/service/DefaultEvictionOperations.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/eviction/CachedReadOnlyEvictionOperations.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/eviction/client/GrpcEvictionServiceClient.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/eviction/replicator/GrpcEvictionReplicatorEventStream.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/titusmaster/TitusMasterConnectorModule.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/common/grpc/DefaultReactorGrpcClientAdapterFactory.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/common/grpc/ReactorGrpcClientAdapter.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/common/grpc/ReactorGrpcClientAdapterFactory.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/common/rest/Responses.java
- titus-supplementary-component/task-relocation/src/main/java/com/netflix/titus/supplementary/relocation/workflow/step/TaskEvictionStep.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/model/eviction/StubbedEvictionOperations.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/model/eviction/StubbedEvictionServiceClient.java
Part of RxJava -> Spring Reactor migration.
> Move the eviction service to spring-reactor

- build.gradle
> Upgrade Mesos client to 1.4.2

- titus-server-master/src/main/java/com/netflix/titus/master/agent/service/cache/DefaultAgentCache.java
- titus-server-master/src/test/java/com/netflix/titus/master/agent/service/cache/DefaultAgentCacheTest.java
* delete agent instances in store after termination.
> delete agent instances in store after termination

- titus-common/src/main/java/com/netflix/titus/common/framework/reconciler/internal/DefaultReconciliationFramework.java
- titus-common/src/test/java/com/netflix/titus/common/framework/reconciler/internal/DefaultReconciliationFrameworkTest.java
- titus-common/src/test/java/com/netflix/titus/common/util/rx/DemultipexTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/MoveTaskTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/scenario/JobScenarioBuilder.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/scenario/JobsScenarioBuilder.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/scenario/StubbedJobStore.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/jobmanager/JobSnapshot.java
Additional unit tests for the reconciliation framework and the JobManagement component.
> MoveTask better test coverage and bug fixes

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/service/JobManagerException.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/service/V3JobOperations.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/service/AggregatingJobManagementClient.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/endpoint/v3/grpc/DefaultJobManagementServiceGrpc.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/DefaultV3JobOperations.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/model/job/StubbedJobOperations.java
Add moveTask to federation and add some validation
PR is work in progress, need to add tests
> Add moveTask api to federation and validations

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/service/JobManagerException.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/DefaultV3JobOperations.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/JobManagerConfiguration.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/MoveTaskTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/scenario/JobScenarioBuilder.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/scenario/JobsScenarioBuilder.java
> Add feature flag for move tasks api

- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/v3/grpc/ErrorResponses.java
Without this, API calls will see errors that look like:
```json
{"statusCode":500,"message":"INTERNAL: CompositeException: 1 exceptions occurred. "}
```
... which is not very useful. It should be:
```json
{"statusCode":500,"message":"INTERNAL: CompositeException: JobManagerException: Cannot decrement job 6855cb18-c825-4a74-a7b9-330c51ffa619 desired size by 1, as it violates the minimum job size constraint: min=3, desired=3, max=3"}
```
> unwrap CompositeException with a single cause when returning errors to API clients

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/JobFunctions.java
- titus-common/src/main/java/com/netflix/titus/common/util/CollectionsExt.java
- titus-grpc-api/dependencies.lock
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/service/action/MoveTaskBetweenJobsAction.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/TaskMoveTest.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/jobmanager/JobSnapshot.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/jobmanager/replicator/GrpcJobReplicatorEventStream.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/v3/grpc/V3GrpcModelConverters.java
- titus-server-runtime/src/test/java/com/netflix/titus/runtime/connector/jobmanager/replicator/GrpcJobReplicatorEventStreamTest.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/client/V3ClientUtils.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/model/job/StubbedJobData.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/model/job/StubbedJobOperations.java
... and simplify the logic on how snapshots are being generated after each event by using a Builder.
> handle tasks being moved in the grpc replicator component

- titus-server-gateway/src/main/java/com/netflix/titus/gateway/endpoint/v3/grpc/DefaultAgentManagementServiceGrpc.java
Fix update agent instance attributes grpc implementation to call the service to do the update.
> fix update agent instance attributes grpc api

- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/registry/DefaultDockerRegistryClient.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/registry/DefaultDockerRegistryClientMain.java
Connection leak bug fix in the docker registry client
>  Connection leak bug fix in the docker registry client

- buildViaTravis.sh
- titus-ext/zookeeper/src/test/java/com/netflix/titus/ext/zookeeper/supervisor/ZookeeperMasterMonitorTest.java
@fabiokung Contains your changes from https://github.com/Netflix/titus-control-plane/pull/482 + bug fix
> Enable all tests in the TITUS_INTEGRATION_TEST phase and fix the race condition in ZookeeperMasterMonitorTest

- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/JobTransactionLogger.java
Fix ordering of caller id and call reason for job transaction log
> Fix ordering of job transaction log

- titus-server-master/src/main/java/com/netflix/titus/master/clusteroperations/ClusterOperationsAttributes.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/DefaultV3TaskInfoFactory.java
* Add owner passthrough attribute to agent.
* Fix cluster operations attribute names
> add owner passthrough attribute to agent

- titus-common/src/main/java/com/netflix/titus/common/util/spectator/DatabaseMetrics.java
- titus-ext/jooq/src/main/java/com/netflix/titus/ext/jooq/JooqModule.java
- titus-ext/jooq/src/main/java/com/netflix/titus/ext/jooq/jobactivity/JooqJobActivityPublisherStore.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobactivity/service/JobActivityPublisher.java
These are some minor cleanups I made while doing some of the performance benchmarking.
> Cleanup around job activity publishing/logging

- build.gradle
See [the Mesos 1.7.2 CHANGELOG](https://github.com/apache/mesos/blob/1.7.2/CHANGELOG) for more info.
> Update to Mesos 1.7.2

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/store/mixin/DisruptionBudgetRateMixIn.java
- titus-common/src/main/java/com/netflix/titus/common/jhiccup/HiccupRecorderConfigurationBean.java
- titus-common/src/main/java/com/netflix/titus/common/jhiccup/JHiccupComponent.java
- titus-common/src/main/java/com/netflix/titus/common/util/SpringConfigurationUtil.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/service/v3/internal/GatewayJobServiceGateway.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/ChannelTunablesConfiguration.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/ChannelTunablesConfigurationBean.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/GrpcClientConfigurationBean.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/agent/replicator/AgentDataReplicatorProvider.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/common/reactor/DefaultGrpcToReactorClientFactory.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/common/reactor/ReactorToGrpcClientBuilder.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/common/replicator/AbstractReplicatorEventStream.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/common/replicator/DataReplicatorMetrics.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/common/replicator/RetryableReplicatorEventStream.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/common/replicator/StreamDataReplicator.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/eviction/EvictionDataSnapshot.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/eviction/replicator/EvictionDataReplicatorProvider.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/eviction/replicator/GrpcEvictionReplicatorEventStream.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/jobmanager/replicator/JobDataReplicatorProvider.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/relocation/RelocationClientModule.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/titusmaster/TitusMasterClientConfigurationBean.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/common/grpc/GrpcEndpointConfigurationBean.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/jobmanager/gateway/GrpcJobServiceGateway.java
- titus-server-runtime/src/test/java/com/netflix/titus/runtime/connector/common/reactor/ReactorToGrpcClientBuilderTest.java
- titus-supplementary-component/task-relocation-springboot/src/main/java/com/netflix/titus/supplementary/relocation/RelocationMain.java
- titus-supplementary-component/task-relocation/src/main/java/com/netflix/titus/supplementary/relocation/RelocationConfiguration.java
- titus-supplementary-component/task-relocation/src/main/java/com/netflix/titus/supplementary/relocation/workflow/step/MustBeRelocatedTaskCollectorStep.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/cli/CommandContext.java
Miscellaneous improvements and bug fixes
> Client connector improvements

- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/validator/JobIamValidator.java
Adds a reason tag to failed IAM validation counter. The cardinality of the value should be similar to the cardinality of the `iamRoleName` itself since each should fail for a specific reason.
> Add reason tag to failed IAM validations

- titus-api/src/main/java/com/netflix/titus/api/agent/model/AgentFunctions.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/agent/AgentSnapshot.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/agent/replicator/GrpcAgentReplicatorEventStream.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/common/replicator/DataReplicator.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/common/replicator/DataReplicatorDelegate.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/common/replicator/ReplicatedSnapshot.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/common/replicator/StreamDataReplicator.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/eviction/EvictionDataSnapshot.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/eviction/replicator/GrpcEvictionReplicatorEventStream.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/jobmanager/JobSnapshot.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/jobmanager/replicator/GrpcJobReplicatorEventStream.java
- titus-server-runtime/src/test/java/com/netflix/titus/runtime/connector/agent/replicator/GrpcAgentReplicatorEventStreamTest.java
- titus-server-runtime/src/test/java/com/netflix/titus/runtime/connector/common/replicator/StreamDataReplicatorTest.java
- titus-supplementary-component/task-relocation/src/main/java/com/netflix/titus/supplementary/relocation/workflow/step/MustBeRelocatedTaskCollectorStep.java
> More metrics/logging in the Titus client connectors

- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/DefaultSchedulingService.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/SchedulerConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/SchedulerUtils.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/VMStateMgr.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/constraint/ActiveHostConstraint.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/constraint/AgentManagementConstraint.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/fitness/AgentManagementFitnessCalculator.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/systemselector/SystemSelectorFunctions.java
- titus-server-master/src/test/java/com/netflix/titus/master/scheduler/constraint/AgentManagementConstraintTest.java
Remove the scheduler usage of the mesos asg label and use agent management data.
> remove the scheduler usage of the mesos asg label

- titus-api/src/main/java/com/netflix/titus/api/appscale/model/AlarmConfiguration.java
- titus-api/src/main/java/com/netflix/titus/api/appscale/store/mixin/AlarmConfigurationMixIn.java
- titus-ext/cassandra/src/test/java/com/netflix/titus/ext/cassandra/store/CassAppScalePolicyStoreTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/appscale/service/AutoScalingPolicyTests.java
> AlarmConfiguration#autoscalingGroupName is not being used

- .circleci/config.yml
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/JobCompatibility.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/perf/load/plan/catalog/AgentExecutableGeneratorCatalog.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/perf/load/plan/catalog/JobDescriptorCatalog.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/perf/load/plan/catalog/JobExecutableGeneratorCatalog.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/perf/load/rest/ScenarioSpringResource.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/perf/load/runner/JobExecutionPlanRunner.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/perf/load/runner/job/ServiceJobExecutor.java
Generate load that is representative of long running services on the critical tier.
> add long running (service style) to the workload generator

- titus-server-master/src/main/java/com/netflix/titus/master/clusteroperations/ClusterAgentAutoScaler.java
- titus-server-master/src/test/java/com/netflix/titus/master/clusteroperations/ClusterAgentAutoScalerTest.java
Scale phased out instance groups and prefer Active for scale ups and PhasedOut for scale downs.
> Support scaling phased out instance groups

- build.gradle
- titus-api/dependencies.lock
- titus-common/dependencies.lock
- titus-ext/aws/dependencies.lock
- titus-ext/cassandra/dependencies.lock
- titus-ext/elasticsearch/dependencies.lock
- titus-ext/eureka/dependencies.lock
- titus-ext/jooq/dependencies.lock
- titus-ext/zookeeper/dependencies.lock
- titus-server-federation/dependencies.lock
- titus-server-gateway/dependencies.lock
- titus-server-master/build.gradle
- titus-server-master/dependencies.lock
- titus-server-runtime-spring/dependencies.lock
- titus-server-runtime/dependencies.lock
- titus-supplementary-component/job-activity-history-springboot/dependencies.lock
- titus-supplementary-component/job-activity-history/dependencies.lock
- titus-supplementary-component/task-relocation/dependencies.lock
- titus-supplementary-component/tasks-publisher-springboot/dependencies.lock
- titus-supplementary-component/tasks-publisher/dependencies.lock
- titus-testkit/dependencies.lock
* Update the version of fenzo-core
* Remove fenzo-trigger depedency
> update fenzo version

- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/registry/TitusRegistryClientConfiguration.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/validator/JobImageValidator.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/validator/JobImageValidatorConfiguration.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/validator/JobSecurityValidatorConfiguration.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/validator/TitusValidatorConfiguration.java
This PR increases the aggregating validator timeout from 2 to 5 and increases those of the sub-validators. Also, adds more detail to image error validation tags.
> Titus 1167

- titus-server-master/src/main/java/com/netflix/titus/master/mesos/DefaultV3TaskInfoFactory.java
> Add NETFLIX_INSTANCE_ID env variable

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/sanitizer/SchedulingConstraintValidator.java
- titus-ext/aws/src/main/java/com/netflix/titus/ext/aws/AwsInstanceCloudConnector.java
- titus-server-master/src/main/java/com/netflix/titus/master/clusteroperations/ClusterAgentAutoScaler.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/SchedulerConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/constraint/AvailabilityZoneConstraint.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/constraint/MachineIdConstraint.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/constraint/MachineTypeConstraint.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/constraint/V3ConstraintEvaluatorTransformer.java
- titus-server-master/src/test/java/com/netflix/titus/master/scheduler/SchedulerTestUtils.java
- titus-server-master/src/test/java/com/netflix/titus/master/scheduler/constraint/AvailabilityZoneConstraintTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/scheduler/constraint/MachineIdConstraintTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/scheduler/constraint/MachineTypeConstraintTest.java
Add experimental constraints to prefer placement based on:
* availability zone
* machine id
* machine type
> Add experimental constraints

- titus-testkit/src/main/java/com/netflix/titus/testkit/perf/load/plan/catalog/JobExecutableGeneratorCatalog.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/perf/load/rest/ScenarioSpringResource.java
Add churn parameter to the batch performance test plan
> Batchperf test update

- titus-server-federation/src/main/java/com/netflix/titus/federation/endpoint/grpc/TitusFederationGrpcServer.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/endpoint/v3/grpc/TitusGatewayGrpcServer.java
- titus-server-runtime/build.gradle
... which allows usage of standard off the shelf grpc CLIs. Tested with `grpcurl`: https://github.com/fullstorydev/grpcurl
> suport grpc server reflection

- titus-api/src/test/java/com/netflix/titus/api/jobmanager/model/job/validator/AggregatingValidatorTest.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/validator/AggregatingValidator.java
in case any validators return Mono.empty() instead of Mono.just(Collections.emptySet()) as "no errors", the entire chain of validations can be ignored by Mono.zip(), which will automatically switch the aggregated result to Mono.empty().
> Mono.zip() requires protection against Mono.empty()

- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/DefaultV3JobOperations.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/metadata/CallMetadataUtils.java
Update the kill message to include the caller id.
> Update kill message with caller id

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/validator/FailJobValidator.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/validator/PassJobValidator.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/validator/TestingAppNameSanitizer.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/validator/TestingCapacityGroupSanitizer.java
- titus-api/src/test/java/com/netflix/titus/api/jobmanager/model/job/validator/AggregatingValidatorTest.java
- titus-api/src/test/java/com/netflix/titus/api/jobmanager/model/job/validator/NeverJobValidator.java
- titus-common/src/main/java/com/netflix/titus/common/model/validator/EntityValidator.java
- titus-common/src/main/java/com/netflix/titus/common/model/validator/ValidationError.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/JobValidatorNegativeTest.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/validator/AggregatingValidator.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/validator/JobIamValidator.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/validator/JobImageValidator.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/validator/TitusValidatorModule.java
... and some small cleanup of the validation code.
> allow IAM sanitization to be disabled

- titus-api/src/main/java/com/netflix/titus/api/json/AssignableFromDeserializers.java
- titus-api/src/main/java/com/netflix/titus/api/json/CompositeDeserializers.java
- titus-api/src/main/java/com/netflix/titus/api/json/CustomDeserializerSimpleModule.java
- titus-api/src/main/java/com/netflix/titus/api/json/ObjectMappers.java
- titus-api/src/main/java/com/netflix/titus/api/json/ProtobufMessageDeserializer.java
- titus-api/src/main/java/com/netflix/titus/api/json/ProtobufMessageSerializer.java
- titus-api/src/main/java/com/netflix/titus/api/json/TrimmingStringDeserializer.java
- titus-api/src/test/java/com/netflix/titus/api/json/ProtobufMessageObjectMapperTest.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/common/rest/JsonMessageReaderWriter.java
allow the serializer to be reused by Spring WebClients
> allow reuse of the protobuf<->json (de)serializer

- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/common/replicator/AbstractReplicatorEventStream.java
... when an error is expected and won't cause any harm.
> only log a stacktrace when debug is enabled

- titus-supplementary-component/task-relocation/src/test/java/com/netflix/titus/supplementary/relocation/integration/TaskRelocationIntegrationTest.java
Client connection although on the blocking stub was done asynchronously.
During its setup, the task was relocated, and when the client finally subscribed
to the event stream it was too late. In the fixed test, we fetch first the
snapshot marker, to be sure we are subscribed before triggering the relocation
process.
> Flaky TaskRelocation service integration test

- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/JobIamValidator.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/ValidatorMetrics.java
... or it will error out and complain.
> don't send tags with no values to spectator

- titus-api/src/main/java/com/netflix/titus/api/clustermembership/connector/ClusterMembershipConnector.java
- titus-api/src/main/java/com/netflix/titus/api/clustermembership/connector/ClusterMembershipConnectorException.java
- titus-api/src/main/java/com/netflix/titus/api/clustermembership/model/ClusterMember.java
- titus-api/src/main/java/com/netflix/titus/api/clustermembership/model/ClusterMemberAddress.java
- titus-api/src/main/java/com/netflix/titus/api/clustermembership/model/ClusterMemberLeadershipState.java
- titus-api/src/main/java/com/netflix/titus/api/clustermembership/model/ClusterMemberState.java
- titus-api/src/main/java/com/netflix/titus/api/clustermembership/model/ClusterMembershipRevision.java
- titus-api/src/main/java/com/netflix/titus/api/clustermembership/model/event/ClusterMemberAddedEvent.java
- titus-api/src/main/java/com/netflix/titus/api/clustermembership/model/event/ClusterMemberRemovedEvent.java
- titus-api/src/main/java/com/netflix/titus/api/clustermembership/model/event/ClusterMemberUpdatedEvent.java
- titus-api/src/main/java/com/netflix/titus/api/clustermembership/model/event/ClusterMembershipEvent.java
- titus-api/src/main/java/com/netflix/titus/api/clustermembership/model/event/ClusterMembershipSnapshotEvent.java
- titus-api/src/main/java/com/netflix/titus/api/clustermembership/service/ClusterMembershipService.java
- titus-api/src/main/java/com/netflix/titus/api/clustermembership/service/ClusterMembershipServiceException.java
Initial version reflecting GRPC/protobuf IDL.
> Cluster Membership service Java API

- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeApiServerIntegrator.java
Use the updated register latency method signature
> use the updated register latency method signature

- build.gradle
- titus-api/dependencies.lock
- titus-common/dependencies.lock
- titus-ext/aws/dependencies.lock
- titus-ext/cassandra-testkit/dependencies.lock
- titus-ext/cassandra/dependencies.lock
- titus-ext/eureka/dependencies.lock
- titus-ext/jooq/dependencies.lock
- titus-ext/zookeeper/dependencies.lock
- titus-server-federation/dependencies.lock
- titus-server-gateway/dependencies.lock
- titus-server-master/dependencies.lock
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/common/action/task/BasicTaskActions.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeApiServerIntegrator.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/TaskPlacementRecorder.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/scenario/TaskScenarioBuilder.java
- titus-server-runtime-spring/dependencies.lock
- titus-server-runtime/dependencies.lock
- titus-supplementary-component/job-activity-history-springboot/dependencies.lock
- titus-supplementary-component/job-activity-history/dependencies.lock
- titus-supplementary-component/task-relocation/dependencies.lock
- titus-supplementary-component/tasks-publisher-springboot/dependencies.lock
- titus-supplementary-component/tasks-publisher/dependencies.lock
- titus-testkit/dependencies.lock
* Remove task from fenzo if the task state is not still in Accepted when attempting to launch.
* Change k8s GC to delete all pending pods with a deletion timestamp.
> Fix Terminated Accepted Tasks

- titus-api/src/main/java/com/netflix/titus/api/json/ObjectMappers.java
... from store and from autoscaling APIs. This allows for forwards-backwards compatible changes.
> don't fail on unknown when deserializing

- titus-server-master/src/main/java/com/netflix/titus/master/mesos/WorkerStateMonitor.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeApiServerIntegrator.java
* Update reason classifications to change the code based on a pattern.
* Change GC logic for tasks that don't exist in api server.
* Use pod message instead of reason for Titus reasonMessage field.
> Update K8S Integration

- titus-common/src/main/java/com/netflix/titus/common/aws/AwsInstanceType.java
* Add m5 and r5 metal instance type configs
> add m5 and r5 metal instance type configs

- .gitattributes
More details: https://github.com/github/linguist
> tell github to hide dependency.lock files in diffs

- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeApiServerIntegrator.java
Improve k8s integration for terminating tasks by transitioning states immediately.
> Improve k8s integration for terminating tasks

- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeApiServerIntegrator.java
* Add gpu support to the k8s integration.
> add gpu support to the k8s integration

- titus-api/src/main/java/com/netflix/titus/api/model/ResourceDimension.java
- titus-api/src/main/java/com/netflix/titus/api/store/v2/ResourceDimensionMixin.java
- titus-api/src/test/java/com/netflix/titus/api/jobmanager/model/job/sanitizer/JobModelSanitizationTest.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeOpportunisticResourceProvider.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/model/v1/V1OpportunisticResource.java
- titus-server-master/src/main/java/com/netflix/titus/master/model/ResourceDimensions.java
- titus-server-master/src/main/java/com/netflix/titus/master/service/management/internal/DefaultAvailableCapacityService.java
- titus-server-master/src/main/java/com/netflix/titus/master/service/management/internal/ResourceConsumptionEvaluator.java
- titus-server-master/src/main/java/com/netflix/titus/master/service/management/internal/ResourceConsumptionServiceMetrics.java
- titus-server-master/src/test/java/com/netflix/titus/master/model/ResourceDimensionsTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/service/management/internal/DefaultResourceConsumptionServiceTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/service/management/internal/ResourceConsumptionEvaluatorTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/service/management/internal/ResourceConsumptionLogTest.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/data/core/ResourceDimensionSample.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/model/job/JobComponentStub.java
> track usage of opportunistic CPUs

- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/endpoint/v3/grpc/DefaultJobManagementServiceGrpc.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/DefaultV3JobOperations.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/JobAndTaskMetrics.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/V3JobManagerModule.java
* Buffer reconciliation framework events and move API requests to IO thread
* Add metric for total active jobs
> Buffer reconciliation framework events

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/JobAttributes.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/JobType.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeApiServerIntegrator.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/SchedulerAttributes.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/constraint/AgentManagementConstraint.java
- titus-server-master/src/test/java/com/netflix/titus/master/scheduler/constraint/AgentManagementConstraintTest.java
* Add agent instance and instance group taints attribute and job tolerations attribute.
* Set K8s restart policy to `Never`.
> Add taints and tolerations

- build.gradle
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/JobAttributes.java
- titus-common/src/main/java/com/netflix/titus/common/util/DateTimeExt.java
- titus-common/src/main/java/com/netflix/titus/common/util/archaius2/Archaius2Ext.java
- titus-common/src/main/java/com/netflix/titus/common/util/closeable/CloseableReference.java
- titus-common/src/main/java/com/netflix/titus/common/util/closeable/DefaultCloseableReference.java
- titus-server-runtime/build.gradle
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/JobRuntimePredictionSanitizer.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/JobRuntimePredictionSelection.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/JobRuntimePredictionSelector.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/JobRuntimePredictionSelectors.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/JobRuntimePredictionUtil.java
- titus-server-runtime/src/test/java/com/netflix/titus/runtime/endpoint/admission/JobRuntimePredictionSanitizerTest.java
- titus-server-runtime/src/test/java/com/netflix/titus/runtime/endpoint/admission/JobRuntimePredictionSelectorsTest.java
> AB testing for JobRuntimePredictionSelector

- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/JobManagerUtil.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeApiServerIntegrator.java
Expect the node name to be a unique identifier instead of an ip address in the k8s integration.
> Expect the node name to be a unique identifier

- titus-server-master/src/main/java/com/netflix/titus/master/mesos/DefaultV3TaskInfoFactory.java
- titus-server-master/src/test/java/com/netflix/titus/master/mesos/DefaultV3TaskInfoFactoryTest.java
cc @jigish @gabrielhartmann FYI
> forward job runtime predictions to agents

- titus-common-api/src/main/java/com/netflix/titus/api/common/LeaderActivationListener.java
- titus-common-server/src/main/java/com/netflix/titus/runtime/clustermembership/activation/LeaderActivationComponent.java
- titus-common-server/src/main/java/com/netflix/titus/runtime/clustermembership/activation/LeaderActivationConfiguration.java
- titus-common-server/src/main/java/com/netflix/titus/runtime/clustermembership/activation/LeaderActivationConfigurationBean.java
- titus-common-server/src/main/java/com/netflix/titus/runtime/clustermembership/activation/LeaderActivationCoordinator.java
- titus-common-server/src/main/java/com/netflix/titus/runtime/clustermembership/activation/LeaderActivationCoordinators.java
- titus-common-server/src/test/java/com/netflix/titus/runtime/clustermembership/activation/LeaderActivationCoordinatorTest.java
- titus-common-server/src/test/java/com/netflix/titus/runtime/clustermembership/endpoint/grpc/ClusterMembershipServiceStub.java
- titus-ext/jooq/src/main/java/com/netflix/titus/ext/jooq/relocation/JooqTaskRelocationStore.java
- titus-ext/jooq/src/test/java/com/netflix/titus/ext/jooq/relocation/JooqTaskRelocationStoreTest.java
- titus-supplementary-component/task-relocation-springboot/src/main/java/com/netflix/titus/supplementary/relocation/RelocationMain.java
- titus-supplementary-component/task-relocation/src/main/java/com/netflix/titus/supplementary/relocation/RelocationLeaderActivator.java
- titus-supplementary-component/task-relocation/src/main/java/com/netflix/titus/supplementary/relocation/store/TaskRelocationStore.java
- titus-supplementary-component/task-relocation/src/main/java/com/netflix/titus/supplementary/relocation/workflow/DefaultRelocationWorkflowExecutor.java
- titus-supplementary-component/task-relocation/src/test/java/com/netflix/titus/supplementary/relocation/integration/TaskRelocationIntegrationTest.java
- titus-supplementary-component/task-relocation/src/test/java/com/netflix/titus/supplementary/relocation/integration/TaskRelocationSandbox.java
- titus-supplementary-component/tasks-publisher/src/main/java/com/netflix/titus/supplementary/taskspublisher/TaskPublisherLeaderActivator.java
- titus-supplementary-component/tasks-publisher/src/main/java/com/netflix/titus/supplementary/taskspublisher/es/EsPublisher.java
- titus-supplementary-component/tasks-publisher/src/test/java/com/netflix/titus/supplementary/taskspublisher/TaskEventsGeneratorTest.java
and integrate it with the task relocation and task publisher services.
> Add leader activation/deactivation mechanism

- titus-common/src/main/java/com/netflix/titus/common/aws/AwsInstanceType.java
Adds the new [g4 instance types](https://aws.amazon.com/ec2/instance-types/g4/)
> Add g4 instance types

- titus-common-api/src/main/java/com/netflix/titus/api/clustermembership/model/ClusterMember.java
- titus-common-api/src/main/java/com/netflix/titus/api/clustermembership/model/ClusterMemberAddress.java
- titus-common-api/src/main/java/com/netflix/titus/api/clustermembership/model/ClusterMemberLeadership.java
- titus-common-api/src/main/java/com/netflix/titus/api/clustermembership/model/ClusterMembershipFunctions.java
- titus-common-api/src/main/java/com/netflix/titus/api/clustermembership/model/ClusterMembershipRevision.java
- titus-common-client/src/main/java/com/netflix/titus/client/clustermembership/ClusterMembershipClientMetrics.java
- titus-common-client/src/main/java/com/netflix/titus/client/clustermembership/grpc/GrpcClusterMembershipNameResolverFactory.java
- titus-common-client/src/main/java/com/netflix/titus/client/clustermembership/resolver/DirectClusterMemberResolver.java
- titus-common-client/src/main/java/com/netflix/titus/client/clustermembership/resolver/EmptyClusterMembershipResolver.java
- titus-common-client/src/main/java/com/netflix/titus/client/clustermembership/resolver/MultiNodeClusterMemberResolver.java
- titus-common-client/src/main/java/com/netflix/titus/client/clustermembership/resolver/MultiNodeClusterMemberResolverMetrics.java
- titus-common-client/src/main/java/com/netflix/titus/client/clustermembership/resolver/SingleClusterMemberResolver.java
- titus-common-client/src/test/java/com/netflix/titus/client/clustermembership/resolver/MultiNodeClusterMemberResolverTest.java
- titus-common-client/src/test/java/com/netflix/titus/client/clustermembership/resolver/SingleClusterMemberResolverTest.java
- titus-common-ext/kube/src/main/java/com/netflix/titus/ext/kube/clustermembership/connector/KubeClusterState.java
- titus-common-server/src/main/java/com/netflix/titus/runtime/clustermembership/endpoint/grpc/MemberDataMixer.java
- titus-common-server/src/main/java/com/netflix/titus/runtime/endpoint/common/grpc/interceptor/CommonErrorCatchingServerInterceptor.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/common/grpc/interceptor/ErrorCatchingServerInterceptor.java
for Titus relocation leader discovery
> TitusGateway integration with the GRPC/cluster membership name resolver

- titus-server-master/src/main/java/com/netflix/titus/master/eviction/service/quota/job/UnhealthyTasksLimitTracker.java
- titus-server-master/src/test/java/com/netflix/titus/master/eviction/integration/EvictionComponentIntegrationTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/eviction/service/quota/job/UnhealthyTasksLimitTrackerTest.java
- titus-supplementary-component/task-relocation/src/main/java/com/netflix/titus/supplementary/relocation/workflow/step/RelocationTransactionLogger.java
Health based quota limits are provided for larger jobs which can tolerate a few unhealthy
tasks.
> Enforce health check quota constraints only for jobs with size above a threshold (>=3)

- titus-common/src/main/java/com/netflix/titus/common/util/FunctionExt.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/JobRuntimePredictionSanitizer.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/JobRuntimePredictionSanitizerMetrics.java
- titus-server-runtime/src/test/java/com/netflix/titus/runtime/endpoint/admission/JobRuntimePredictionSanitizerTest.java
With some coarse grained categorization for each failure case.
> Emit metrics on cases where predictions are skipped

- titus-common/src/main/java/com/netflix/titus/common/network/client/ClientMetrics.java
- titus-common/src/main/java/com/netflix/titus/common/network/client/internal/WebClientMetric.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/MesosConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeApiServerIntegrator.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeOpportunisticResourceProvider.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeUtil.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/OkHttpMetricsInterceptor.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/registry/DefaultDockerRegistryClient.java
Use the shared informer pattern in the k8s integration.
> Shared Informer

- titus-common/src/main/java/com/netflix/titus/common/util/spectator/DatabaseMetrics.java
- titus-ext/jooq/src/main/java/com/netflix/titus/ext/jooq/jobactivity/JooqJobActivityPublisherStore.java
Add some more database metrics methods to be used by CMB.
> Adding common database metrics methods for cmb

- titus-common/src/main/java/com/netflix/titus/common/util/spectator/DatabaseMetrics.java
Add missing counter increment.
> Fix database metric bug

- titus-server-federation/src/main/java/com/netflix/titus/federation/endpoint/EndpointConfiguration.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/endpoint/FederationEndpointModule.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/endpoint/grpc/TitusFederationGrpcServer.java
Protection for REST endpoints will come at a later date.
> add load shedding to federation grpc requests

- titus-server-federation/src/main/java/com/netflix/titus/federation/endpoint/grpc/TitusFederationGrpcServer.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/endpoint/v3/grpc/TitusGatewayGrpcServer.java
- titus-server-master/src/main/java/com/netflix/titus/master/endpoint/grpc/TitusMasterGrpcServer.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/common/grpc/AbstractTitusGrpcServer.java
> tear down thread pools when grpc servers shutdown

- titus-api/src/main/java/com/netflix/titus/api/FeatureRolloutPlans.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/endpoint/v3/grpc/GrpcEndpointConfiguration.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/endpoint/v3/grpc/TitusGatewayGrpcServer.java
- titus-server-master/src/main/java/com/netflix/titus/master/endpoint/grpc/GrpcMasterEndpointConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/endpoint/grpc/TitusMasterGrpcServer.java
> Code hygiene

- build.gradle
- titus-common-grpc-api/dependencies.lock
- titus-grpc-api/dependencies.lock
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/DefaultV3TaskInfoFactory.java
Will depend on: https://github.com/Netflix/titus-api-definitions/pull/118 being merged.
> Set job accepted timestamp in agent proto

- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeApiServerIntegrator.java
Add executor details to missing statuses.
> add executor details to missing statuses

- HOTFIX.md
Testing hotfix release process
> Hotfix release testing 2019

- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeApiServerIntegrator.java
* Immediately finish the task if the pod object does not exist in apiserver and the current state is accepted.
> Fix kill after accepted state transition delay

- titus-ext/cassandra/src/main/java/com/netflix/titus/ext/cassandra/store/CassAppScalePolicyStore.java
- titus-ext/cassandra/src/main/java/com/netflix/titus/ext/cassandra/store/CassandraLoadBalancerStore.java
- titus-ext/cassandra/src/test/java/com/netflix/titus/ext/cassandra/store/CassAppScalePolicyStoreTest.java
- titus-ext/runner/Dockerfile.master
* isolate C* load balancer operations on a dedicated C* `Session`
* limit concurrency of C* operations during activation by the ApplicationAutoScaling component
> C* improvements

- titus-api/src/main/java/com/netflix/titus/api/FeatureActivationConfiguration.java
- titus-api/src/main/java/com/netflix/titus/api/FeatureRolloutPlans.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/service/V3JobOperations.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/KubeNotificationProcessor.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/V3JobManagerModule.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/batch/BatchDifferenceResolver.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/common/action/task/BasicTaskActions.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/service/ServiceDifferenceResolver.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/MesosModule.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeApiServerIntegrator.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DefaultDirectKubeApiServerIntegrator.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DefaultTaskToPodConverter.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DirectKubeApiServerIntegrator.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DirectKubeConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/NoOpDirectKubeApiServerIntegrator.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/TaskToPodConverter.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/model/PodAddedEvent.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/model/PodDeletedEvent.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/model/PodEvent.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/model/PodUpdatedEvent.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/KubeSchedulerTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/scenario/JobScenarioBuilder.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/scenario/JobsScenarioBuilder.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/scenario/ScenarioTemplates.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/scenario/StubbedDirectKubeApiServerIntegrator.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/scenario/StubbedSchedulingService.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/FeatureFlagModule.java
The newly introduced components are turned off by default. More work is required to fully support this integration.
> Initial kube-scheduler integration

- titus-common/src/main/java/com/netflix/titus/common/util/CollectionsExt.java
- titus-ext/cassandra/src/test/java/com/netflix/titus/ext/cassandra/store/CassStoreHelperTest.java
- titus-server-master/src/main/java/com/netflix/titus/master/service/management/ResourceConsumption.java
- titus-server-master/src/main/java/com/netflix/titus/master/service/management/ResourceConsumptions.java
- titus-server-master/src/main/java/com/netflix/titus/master/service/management/internal/DefaultResourceConsumptionService.java
- titus-server-master/src/main/java/com/netflix/titus/master/service/management/internal/ResourceConsumptionEvaluator.java
- titus-server-master/src/main/java/com/netflix/titus/master/service/management/internal/ResourceConsumptionServiceMetrics.java
- titus-server-master/src/test/java/com/netflix/titus/master/service/management/internal/ConsumptionModelGenerator.java
- titus-server-master/src/test/java/com/netflix/titus/master/service/management/internal/DefaultResourceConsumptionServiceTest.java
Emit consumption metrics tagged with the underlying host machine type being utilized.
> track consumption by host machine instance type

- titus-server-master/src/main/java/com/netflix/titus/master/mesos/MesosConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/MesosModule.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeModule.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeUtil.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/NoOpJobManagementReconciler.java
Use kube config file instead of a configured url to kube-apiserver.
> use kube config file

- build.gradle
- titus-common-server/build.gradle
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/DefaultSchedulingService.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/SchedulerConfiguration.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/embedded/cell/master/EmbeddedTitusMasters.java
... speeding up integration tests that rely on many scheduling iterations.
> configurable min scheduler iteration frequency

- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeApiServerIntegrator.java
> minor: use the value from KubeConstants

- titus-common/src/main/java/com/netflix/titus/common/util/rx/RetryHandlerBuilder.java
- titus-common/src/test/java/com/netflix/titus/common/util/rx/ReactorRetryHandlerBuilderTest.java
- titus-common/src/test/java/com/netflix/titus/common/util/rx/RetryHandlerBuilderTest.java
RetryHandlerBuilder can be configured with an optional predicate for a Throwable. This allows for configuring retries on a specific Throwable condition as opposed to retrying on all exceptions. RetryHandlerBuilder supports both reactive modes (rxjava, spring reactor) for this optional configuration.
> Retry handler builder configured with a predicate<Throwable>

- build.gradle
- titus-server-federation-springboot/build.gradle
Upgrading nebula plugins to handle https://docs.gradle.org/current/userguide/upgrading_version_6.html#publishing_spring_boot_applications
> Fix bootJar issues with Gradle 6.2

- .circleci/config.yml
... in parallel on multiple instances.
> circleci: run integration tests on multiple jobs

- titus-supplementary-component/task-relocation/src/main/java/com/netflix/titus/supplementary/relocation/RelocationConfiguration.java
- titus-supplementary-component/task-relocation/src/main/java/com/netflix/titus/supplementary/relocation/workflow/DefaultRelocationWorkflowExecutor.java
- titus-supplementary-component/task-relocation/src/main/java/com/netflix/titus/supplementary/relocation/workflow/step/MustBeRelocatedTaskStoreUpdateStep.java
- titus-supplementary-component/task-relocation/src/main/java/com/netflix/titus/supplementary/relocation/workflow/step/TaskEvictionResultStoreStep.java
- titus-supplementary-component/task-relocation/src/test/java/com/netflix/titus/supplementary/relocation/workflow/step/MustBeRelocatedTaskStoreUpdateStepTest.java
- titus-supplementary-component/task-relocation/src/test/java/com/netflix/titus/supplementary/relocation/workflow/step/TaskEvictionResultStoreStepTest.java
and increast the default from 30sec to 90sec
> Make RDS timeout configurable in the Titus relocation service

- .circleci/config.yml
... with the build phase, speeding up CI.
> docker compose test running in parallel

- titus-ext/jooqflyway/build.gradle
- titus-ext/jooqflyway/dependencies.lock
- titus-ext/jooqflyway/src/main/java/com/netflix/titus/ext/jooqflyway/jobactivity/EmbeddedPostgresService.java
- titus-ext/jooqflyway/src/main/java/com/netflix/titus/ext/jooqflyway/jobactivity/JooqConfigurationBean.java
- titus-ext/jooqflyway/src/main/java/com/netflix/titus/ext/jooqflyway/jobactivity/JooqJobActivityConnectorComponent.java
- titus-ext/jooqflyway/src/main/java/com/netflix/titus/ext/jooqflyway/jobactivity/JooqJobActivityConsumerStore.java
- titus-ext/jooqflyway/src/main/java/com/netflix/titus/ext/jooqflyway/jobactivity/RDSSSLSocketFactory.java
- titus-ext/jooqflyway/src/main/java/com/netflix/titus/ext/jooqflyway/jobactivity/RdsUtils.java
- titus-supplementary-component/job-activity-history-springboot/build.gradle
- titus-supplementary-component/job-activity-history-springboot/src/main/java/com/netflix/titus/supplementary/jobactivity/JobActivityMain.java
- titus-supplementary-component/job-activity-history/src/main/java/com/netflix/titus/supplementary/jobactivity/endpoint/rest/JobActivityHistorySpringResource.java
> Initial jooq flyway commit to connect to job activity

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/JobConstraints.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/JobFunctions.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/KubeNotificationProcessor.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeConstants.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeUtil.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DefaultPodAffinityFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/taint/DefaultTaintTolerationFactory.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/KubeNotificationProcessorTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DefaultPodAffinityFactoryTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/mesos/kubeapiserver/direct/taint/DefaultTaintTolerationFactoryTest.java
to restrict placement to nodes running a specific Kube backend version
> Add a Kube backend constraint

- titus-server-master/src/main/java/com/netflix/titus/master/config/MasterConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/DefaultSchedulingService.java
Add configurable lease max reject count property.
> add configurable lease max reject count property

- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeApiServerIntegrator.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeUtil.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/SchedulerModule.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/TaskPlacementFailureClassifier.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/constraint/DefaultSystemHardConstraint.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/constraint/KubeConstraint.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/constraint/NoOpConstraint.java
- titus-server-master/src/test/java/com/netflix/titus/master/mesos/kubeapiserver/KubeUtilTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/scheduler/constraint/KubeConstraintTest.java
Add scheduling constraint for kube nodes instead of trying to do lease management when conditions and taints change.
> add scheduling constraint for kube nodes

- titus-ext/cassandra/src/main/java/com/netflix/titus/ext/cassandra/store/CassandraJobStore.java
- titus-ext/cassandra/src/test/java/com/netflix/titus/ext/cassandra/store/CassandraJobStoreTest.java
Doing so confuses TitusGateway when a user runs a query for a task with `Finished` state filter, but the task is still active.
> Do not return active data set in archive query

- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/KubeNotificationProcessor.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeApiServerIntegrator.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeUtil.java
- titus-server-master/src/test/java/com/netflix/titus/master/mesos/kubeapiserver/KubeApiServerIntegratorTest.java
before adding a lease for a node to Fenzo
> Check if all required node attributes are present

- .circleci/config.yml
- gradle.properties
integration-test-master-2 is failing with OOM errors on Circle CI
> attempt at reducing heap memory used by tests on CI

- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeModule.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DirectKubeConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/resourcepool/PodResourcePoolResolverFeatureGuard.java
We need to be able to disable this feature for backward compatibility.
> Add resource pool resolver feature guard

- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DefaultTaskToPodConverter.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DirectKubeConfiguration.java
- titus-server-master/src/test/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DefaultTaskToPodConverterTest.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/kubernetes/KubeConstants.java
for reference check: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
> Align pod resource units with Kube spec

- titus-server-gateway/src/test/java/com/netflix/titus/gateway/service/v3/internal/ServiceMeshImageSanitizerTest.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/ServiceMeshImageSanitizer.java
Downstream services are expecting the ServiceMeshImageSanitizer to read and populate the relevant attributes as part of container and not JobDescriptor. This PR moves reading and populating of those attributes to container attributes section in the JobDescriptor.
> Move image sanitzation attributes to container section

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/sanitizer/JobConfiguration.java
* Update the max job dimensions.
> update the max job dimensions

- titus-server-master/src/main/java/com/netflix/titus/master/clusteroperations/ClusterOperationsConfiguration.java
* Increase agent removable grace period due to clock timings.
> increase agent removable grace period

- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeApiServerIntegrator.java
* Set task to Finished state with a crashed reason code when unable to create the pod such that a new task is created.
* Reject nodes that are missing allocatable or capacity information.
> K8s Integration Improvements

- titus-common-runtime/src/main/java/com/netflix/titus/runtime/connector/kubernetes/DefaultKubeApiFacade.java
- titus-common-runtime/src/main/java/com/netflix/titus/runtime/connector/kubernetes/KubeApiFacade.java
- titus-common-runtime/src/main/java/com/netflix/titus/runtime/connector/kubernetes/NoOpKubeApiFacade.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/controller/KubeControllerConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/controller/KubeControllerModule.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/controller/PersistentVolumeUnassociatedGcController.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeUtil.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/controller/PersistentVolumeUnassociatedGcControllerTest.java
GC of Persistent Volume Kube resources. The GC logic deletes from Kube any Persistent Volume that has not been associated with an active job for a certain time period.
> Initial persistent volume GC functionality

- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeModule.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/env/DefaultAggregatingContainerEnvFactory.java
- titus-server-master/src/test/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DefaultTaskToPodConverterTest.java
Support variable ContainerEnvFactories to aggregate across as part of Default implementation
> Adding back support for caller provided ContainerEnvFactories for EnvVar aggregation

- titus-server-runtime/src/main/java/com/netflix/titus/runtime/FeatureFlagModule.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/KubeSchedulerFeatureConfiguration.java
> Adding feature flag for routing Jobs with EBS volumes to KubeScheduler

- titus-common/src/main/java/com/netflix/titus/common/framework/reconciler/internal/EventDistributor.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/endpoint/v3/grpc/DefaultJobManagementServiceGrpc.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/endpoint/v3/grpc/DefaultJobManagementServiceGrpcMetrics.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/query/JobObserveTest.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/grpc/TestStreamObserver.java
+ more eagerly remove completed subscribers in `EventDistributor`
> Add metrics to the GRPC job service event stream

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/JobAttributes.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/KubePodConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/KubePodConstants.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/KubePodModule.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/KubePodUtil.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/RouterPodFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/affinity/DefaultPodAffinityFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/affinity/PodAffinityFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/env/DefaultPodEnvFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/env/PodEnvFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/legacy/ContainerEnvFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/legacy/DefaultAggregatingContainerEnvFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/legacy/PodContainerInfoFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/legacy/TitusProvidedContainerEnvFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/legacy/UserProvidedContainerEnvFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/taint/TaintTolerationFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/topology/DefaultTopologyFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/topology/TopologyFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/v0/V0SpecPodFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/v1/V1SpecPodFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeApiServerIntegrator.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/LegacyKubeModule.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DirectKubeConfiguration.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/pod/legacy/PodContainerInfoFactoryTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/pod/topology/DefaultTopologyFactoryTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/pod/v0/V0SpecPodFactoryTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DefaultPodAffinityFactoryTest.java
Add the initial v1 pod spec support for basic job configurations. This is not fully functional yet and is disabled by default.
> Initial V1 Pod Spec Support

- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DefaultDirectKubeApiServerIntegrator.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DefaultDirectKubeApiServerIntegratorMetrics.java
Add launch timeout metrics to enable insight into scheduling behavior
> Add launch timeout and inflight metrics

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/JobConstraints.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/affinity/DefaultPodAffinityFactory.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/kubernetes/KubeConstants.java
Some test scenarios would prefer to be able to schedule on a particular CPU model
> Add constraint allowing specification of cpu model

- titus-api/src/main/java/com/netflix/titus/api/appscale/model/AutoScalingPolicy.java
- titus-api/src/main/java/com/netflix/titus/api/appscale/model/PolicyConfiguration.java
- titus-api/src/main/java/com/netflix/titus/api/appscale/model/sanitizer/ScalingPolicyAssertions.java
- titus-api/src/main/java/com/netflix/titus/api/appscale/model/sanitizer/ScalingPolicySanitizerBuilder.java
- titus-api/src/test/java/com/netflix/titus/api/appscale/model/sanitizer/ScalingPolicyModelSanitizationTest.java
- titus-server-master/src/main/java/com/netflix/titus/master/appscale/endpoint/v3/grpc/DefaultAutoScalingServiceGrpc.java
- titus-server-master/src/test/java/com/netflix/titus/master/appscale/endpoint.v3/grpc/DefaultAutoScalingServiceGrpcTest.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/TitusEntitySanitizerModule.java
Basic check to prevent invalid input with null AlarmConfiguration
> Validator for AutoScalingPolicy model object

- titus-api/src/main/java/com/netflix/titus/api/appscale/model/sanitizer/ScalingPolicyAssertions.java
> Remove redundant check

- build.gradle
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/BasicContainer.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/Container.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/NetworkConfiguration.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/VolumeMount.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/store/mixin/BasicContainerMixin.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/store/mixin/ContainerMixin.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/store/mixin/VolumeMountMixin.java
- titus-api/src/main/java/com/netflix/titus/api/json/ObjectMappers.java
- titus-client/src/main/java/com/netflix/titus/runtime/endpoint/v3/grpc/GrpcJobManagementModelConverters.java
- titus-ext/cassandra/src/test/java/com/netflix/titus/ext/cassandra/store/CassandraJobStoreTest.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/KubePodUtil.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/v0/V0SpecPodFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/v1/V1SpecPodFactory.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/pod/v0/V0SpecPodFactoryTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/pod/v1/V1SpecPodFactoryTest.java
This adds VolumeMount support to the main container and extraContainers,
so that they can actually use the Volumes defined in the previous PR.
> Added VolumeMount support

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/Job.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/volume/Volume.java
- titus-ext/cassandra/src/test/java/com/netflix/titus/ext/cassandra/store/CassandraJobStoreTest.java
This slipped through my cracks.
> Fixed volume serializiation test

- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/KubePodUtil.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/v1/V1SpecPodFactory.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/pod/KubePodUtilTest.java
* Sanitize volume names so that they do not fail K8s validator.
> Update volume names for V1 pod spec

- titus-api/src/main/java/com/netflix/titus/api/FeatureActivationConfiguration.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/kubernetes/KubeApiConnector.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/service/v3/internal/TaskDataInjector.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/service/v3/internal/TaskRelocationDataInjector.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/startup/TitusGatewayConfiguration.java
Injecting container states into tasks at gateway
> Inject container states into task

- titus-cli/src/main/java/com/netflix/titus/cli/CLI.java
- titus-cli/src/main/java/com/netflix/titus/cli/CommandContext.java
- titus-cli/src/main/java/com/netflix/titus/cli/command/job/JobUtil.java
- titus-cli/src/main/java/com/netflix/titus/cli/command/job/unschedulable/PrintUnschedulableJobsCommand.java
- titus-cli/src/main/java/com/netflix/titus/cli/command/job/unschedulable/RemoveUnschedulableJobsCommand.java
- titus-cli/src/main/java/com/netflix/titus/cli/command/job/unschedulable/UnschedulableFinder.java
- titus-cli/src/main/java/com/netflix/titus/cli/command/job/unschedulable/UnschedulableJob.java
- titus-common/src/main/java/com/netflix/titus/common/util/DateTimeExt.java
- titus-common/src/test/java/com/netflix/titus/common/util/DateTimeExtTest.java
Add print/remove unschedulable job commands
> Add print/remove unschedulable job commands

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/BasicContainer.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/PlatformSidecar.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/VolumeMount.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/volume/SaaSVolumeSource.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/volume/SharedContainerVolumeSource.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/volume/Volume.java
- titus-api/src/test/java/com/netflix/titus/api/jobmanager/model/job/sanitizer/JobModelSanitizationTest.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/v1/V1SpecPodFactory.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/query/JobCriteriaQueryTest.java
I was sprinkling in @Valid, not knowing what it really does.
From reading the docs, it sounds like it is designed to
operate on an *Object* and enforce recursive validation.
This PR puts more specific validation on strings and such.
> Added stricter validation on some new titus objects

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/JobAttributes.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/JobFunctions.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/DefaultV3JobOperations.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/service/action/BasicServiceJobActions.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/basic/JobSubmitAndControlBasicTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/scenario/JobScenarioBuilder.java
Add call reason as a job attribute
> Add call metadata as a job attribute

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/store/mixin/VolumeSourceMixin.java
I missed this the first time around and forgot to
tell jackson how to serialize this kind
> Added SaaS Volume Jackson Mixin Hints

- build.gradle
Titus api version update for picking up auto scaling policy configuration changes
> updating titus api version

- titus-server-gateway/src/main/java/com/netflix/titus/gateway/service/v3/internal/JobFeatureComplianceChecks.java
The point of the HighScale network mode is to set
security groups and subnets on the backend, chosen at
task start time by our infrastructure, *not* baked into the job.
to that end, we must relax the validation when in this mode.
Note that I did not add *additional* validation that SG/subnets are
*not* set when in this mode. I will be doing that in a subsequent
PR in the new titus-federation codebase (I think).
> Relax Job validation on the HighScale network mode

- titus-common/src/main/java/com/netflix/titus/common/framework/simplereconciler/internal/SnapshotMerger.java
- titus-common/src/test/java/com/netflix/titus/common/framework/simplereconciler/internal/SnapshotMergerTest.java
Adds helper function that allows snapshots with different key types.
> Allow merging snapshot with different key types

- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/client/DefaultDirectKubeApiServerIntegrator.java
> Configurable deleteGracePeriod for Pods

- titus-server-gateway/src/main/java/com/netflix/titus/gateway/service/v3/internal/GatewayJobServiceGateway.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/jobmanager/gateway/SanitizingJobServiceGateway.java
Follow up to PR https://github.com/Netflix/titus-control-plane/pull/1246 which does not cover all cases.
> Verify job/task id format in the GRPC requests

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/TaskAttributes.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/JobManagerUtil.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/KubePodConstants.java
subnetIds and SgIds will be populated if the network mode is high scale, return this information to the titusui using the context setter
> Add high scale network mode data to contextsetter

- titus-common-client/src/main/java/com/netflix/titus/client/clustermembership/grpc/ClusterMembershipClient.java
- titus-common-client/src/main/java/com/netflix/titus/client/clustermembership/resolver/SingleClusterMemberResolver.java
- titus-common-client/src/test/java/com/netflix/titus/client/clustermembership/resolver/SimpleClusterMembershipClient.java
- titus-common-client/src/test/java/com/netflix/titus/client/clustermembership/resolver/SingleClusterMemberResolverTest.java
- titus-common-server/src/main/java/com/netflix/titus/runtime/clustermembership/DefaultClusterMembershipClient.java
- titus-common-server/src/main/java/com/netflix/titus/runtime/clustermembership/endpoint/grpc/ClusterMembershipGrpcEndpointComponent.java
- titus-common-server/src/main/java/com/netflix/titus/runtime/clustermembership/endpoint/grpc/GrpcClusterMembershipService.java
- titus-common-server/src/main/java/com/netflix/titus/runtime/clustermembership/endpoint/rest/ClusterMembershipRestEndpointComponent.java
- titus-common-server/src/main/java/com/netflix/titus/runtime/clustermembership/endpoint/rest/ClusterMembershipSpringResource.java
- titus-common-server/src/main/java/com/netflix/titus/runtime/endpoint/common/grpc/TitusGrpcServer.java
- titus-common-server/src/test/java/com/netflix/titus/runtime/clustermembership/endpoint/grpc/ClusterMembershipGrpcServerTest.java
- titus-common-server/src/test/java/com/netflix/titus/runtime/clustermembership/endpoint/grpc/ClusterMembershipServerResource.java
- titus-common-server/src/test/java/com/netflix/titus/runtime/clustermembership/service/ClusterMembershipConnectorStub.java
- titus-supplementary-component/task-relocation/src/main/java/com/netflix/titus/supplementary/relocation/endpoint/grpc/TaskRelocationGrpcServerRunner.java
- titus-supplementary-component/task-relocation/src/test/java/com/netflix/titus/supplementary/relocation/integration/TaskRelocationSandbox.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/grpc/TestStreamObserver.java
**FIXME**: please add at least one sentence explaining why changes here are being made.
> Use the GRPC assistant API in ClusterMembership client/server

- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/v1/V1SpecPodFactory.java
I believe this got lost in the v0->v1 transition.
Do I need to try/catch number format exceptions? or would it be better
ot just let it raise so the user can see it somehow?
> Respect killWaitSeconds job attribute

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/JobAttributes.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/KubePodConstants.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/v1/V1SpecPodFactory.java
This change adds ability to set the traffic steering attribute
> traffic steering pod attribute

- titus-supplementary-component/tasks-publisher/src/main/java/com/netflix/titus/supplementary/taskspublisher/TaskDocument.java
Network mode configuration is added to the published task document
> network mode added to ES model

- titus-common/src/main/java/com/netflix/titus/common/util/loadshedding/backoff/SimpleAdmissionBackoffStrategy.java
- titus-common/src/main/java/com/netflix/titus/common/util/loadshedding/backoff/SimpleAdmissionBackoffStrategyConfiguration.java
- titus-common/src/test/java/com/netflix/titus/common/util/loadshedding/backoff/SimpleAdmissionBackoffStrategyTest.java
Separate step-up/down adjustments for the backoff strategy to allow more conservative adjustments.
> CMB-342 Make SimpleAdmissionBackoffStrategy more configurable

- titus-server-master/src/main/java/com/netflix/titus/master/endpoint/v2/rest/JerseyModule.java
- titus-server-master/src/main/java/com/netflix/titus/master/endpoint/v2/rest/ResourceConsumptionEndpoint.java
- titus-server-master/src/main/java/com/netflix/titus/master/endpoint/v2/rest/ResourceConsumptionResource.java
- titus-server-master/src/main/java/com/netflix/titus/master/service/management/CapacityManagementAttributes.java
- titus-server-master/src/main/java/com/netflix/titus/master/service/management/CompositeResourceConsumption.java
- titus-server-master/src/main/java/com/netflix/titus/master/service/management/ManagementModule.java
- titus-server-master/src/main/java/com/netflix/titus/master/service/management/ResourceConsumption.java
- titus-server-master/src/main/java/com/netflix/titus/master/service/management/ResourceConsumptionEvents.java
- titus-server-master/src/main/java/com/netflix/titus/master/service/management/ResourceConsumptionService.java
- titus-server-master/src/main/java/com/netflix/titus/master/service/management/ResourceConsumptions.java
- titus-server-master/src/main/java/com/netflix/titus/master/service/management/internal/DefaultResourceConsumptionService.java
- titus-server-master/src/main/java/com/netflix/titus/master/service/management/internal/ResourceConsumptionEvaluator.java
- titus-server-master/src/main/java/com/netflix/titus/master/service/management/internal/ResourceConsumptionLog.java
- titus-server-master/src/main/java/com/netflix/titus/master/service/management/internal/ResourceConsumptionServiceMetrics.java
- titus-server-master/src/test/java/com/netflix/titus/master/service/management/internal/ConsumptionModelGenerator.java
- titus-server-master/src/test/java/com/netflix/titus/master/service/management/internal/ResourceConsumptionEvaluatorTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/service/management/internal/ResourceConsumptionLogTest.java
This reverts commit a599283c25115cdda791ed7a9b465565369d7579.
> Revert "Remove the V2 resource consumption endpoint (#1273)"
