Netflix/titus-control-plane

- titus-server-master/src/main/java/com/netflix/titus/master/agent/service/DefaultAgentManagementService.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/JobManagerConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/DefaultSchedulingService.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/SchedulerConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/constraint/DefaultSystemHardConstraint.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/constraint/DefaultSystemSoftConstraint.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/constraint/GlobalAgentClusterConstraint.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/constraint/GlobalConstraintEvaluator.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/constraint/GlobalInactiveClusterConstraintEvaluator.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/constraint/GlobalTaskLaunchingConstraintEvaluator.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/constraint/GlobalTaskResubmitConstraintEvaluator.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/scenario/JobsScenarioBuilder.java
* Remove logging and spectator proxies from agent management to reduce cpu time
* Add more instrumentation to the various sections of the scheduling process
* Use constant string names in the evaluators
> Reduce scheduling time

- titus-common/src/test/java/com/netflix/titus/common/util/ProtobufCopyTest.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/service/AggregatingJobManagementService.java
- titus-server-federation/src/test/java/com/netflix/titus/federation/service/AggregatingJobManagementServiceTest.java
- titus-server-federation/src/test/java/com/netflix/titus/federation/service/CellWithFixedJobsService.java
- titus-server-federation/src/test/java/com/netflix/titus/federation/service/CellWithFixedTasksService.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/endpoint/v3/grpc/DefaultJobManagementServiceGrpc.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/JobCriteriaQueryTest.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/service/JobManagementService.java
When fields are being filtered in a query, ensure all that is required by the federation proxy is included, and take out what the original API query didn't specify.
> Federation: ensure fields required for cursors are always present

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/JobAttributes.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/service/AggregatingJobManagementService.java
- titus-server-federation/src/test/java/com/netflix/titus/federation/service/AggregatingJobManagementServiceTest.java
- titus-server-federation/src/test/java/com/netflix/titus/federation/service/CellWithCachedJobsService.java
- titus-server-master/src/main/java/com/netflix/titus/master/endpoint/common/CellDecorator.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/JobSchedulingTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/CellAssertions.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/JobCriteriaQueryTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/JobFederationTest.java
This makes it so jobs and tasks are always persisted with `titus.stack`
being the federated stack name. The caveat is that jobs created not
through the federation proxy (including legacy V2 API calls that don't
go through federation) will not have the attribute persisted with them.
With it, the persisted state should more accurately reflect what jobs
and tasks were created in a federated context, and what is their
federated stack name.
All jobs and tasks queried through a federation proxy continue to have
`titus.stack` automatically decorated into them, regardless if the
records from each cell have it or not.
> let the federation proxy set titus.stack for jobs and tasks

- titus-server-gateway/src/main/java/com/netflix/titus/gateway/service/v3/JobManagerConfiguration.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/service/v3/internal/ExtendedJobSanitizer.java
- titus-server-gateway/src/test/java/com/netflix/titus/gateway/service/v3/internal/ExtendedJobSanitizerTest.java
Enforce that the disk size is always greater than or equal to the min disk size configuration. If the request is changed then `diskSizeLessThanMin` is appended to the `titus.noncompliant` job attribute.
> Enforce Min Disk Size

- titus-api/src/main/java/com/netflix/titus/api/loadbalancer/model/sanitizer/DefaultLoadBalancerJobValidator.java
- titus-api/src/main/java/com/netflix/titus/api/loadbalancer/service/LoadBalancerException.java
- titus-api/src/test/java/com/netflix/titus/api/loadbalancer/model/sanitizer/DefaultLoadBalancerJobValidatorTest.java
- titus-api/src/test/java/com/netflix/titus/api/loadbalancer/service/LoadBalancerExceptionTest.java
Validation of a routable IP address for a job is no longer necessary as all jobs have IPs.
> [TITUS-2281] Remove validation of routable IP on jobs

- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/v3/grpc/ErrorResponses.java
The job create limited exception happens when the requestor submits a job that already has a given app-stack-detail-sequence and should translate to invalid argument/bad request instead of resource exhausted.
> Fix status code

- titus-common/src/main/java/com/netflix/titus/common/util/rx/ObservableExt.java
- titus-common/src/test/java/com/netflix/titus/common/util/rx/ObservableExtTest.java
* Specify a type parameter in fromRunnable() to fix an "unchecked cast" warning in NetBeans.
* Delete a technically unsound cast in fromWithDelay()
> ObservableExt improvements

- codequality/Intellij_code_style.xml
- titus-server-federation/src/main/java/com/netflix/titus/federation/service/DefaultCellRouter.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/DefaultV3TaskInfoFactory.java
- titus-server-master/src/test/java/com/netflix/titus/master/mesos/DefaultV3TaskInfoFactoryTest.java
Jobs that specify a custom `CMD` will have their entrypoint and command sent to agents not as flat
strings anymore. The new code path on agents will not force any shell parsing. It is responsibility of API callers to break commands and entrypoints into valid lists, respecting the semantics of [the docker API](https://docs.docker.com/engine/api/v1.24/#create-a-container), and [`execvp`](http://pubs.opengroup.org/onlinepubs/9699919799/functions/exec.html).
The old behavior of flattening entrypoint strings, and relying on agent code to do shell parsing is being retired. To avoid breaking existing jobs, and allow for a smooth transition, only jobs that specify a command (previously a noop) will be sent to the new code path.
Related to Netflix/titus-executor#152 and …
> allow V3 jobs to specify a custom CMD 

- titus-server-federation/src/main/java/com/netflix/titus/federation/service/AggregatingJobManagementClient.java
- titus-server-federation/src/test/java/com/netflix/titus/federation/service/AggregatingJobManagementClientTest.java
gRPC streaming calls should not set any deadline to allow for long running clients. Testing here is not ideal and will add 4s to the total tests execution time, but there is currently no simple way to expose the client (stub) deadlines without major refactoring.
> Do not set deadlines for observeJob streaming calls

- titus-server-gateway/src/main/java/com/netflix/titus/gateway/service/v3/internal/ExtendedJobSanitizer.java
- titus-server-gateway/src/test/java/com/netflix/titus/gateway/service/v3/internal/ExtendedJobSanitizerTest.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/model/job/ContainersGenerator.java
These jobs are likely relying on legacy shell parsing being done by the executor, which is going away.
Internal: TITUS-1574
> mark jobs with spaces in their entrypoint binaries as noncompliant

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/JobFunctions.java
- titus-common/src/main/java/com/netflix/titus/common/util/TimeSeriesData.java
- titus-common/src/test/java/com/netflix/titus/common/util/TimeSeriesDataTest.java
- titus-server-master/src/main/java/com/netflix/titus/master/cluster/DefaultLeaderActivator.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/AgentQualityTracker.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/ContainerFailureBasedAgentQualityTracker.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/DefaultSchedulingService.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/SchedulerConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/SchedulerModule.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/constraint/DefaultSystemSoftConstraint.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/fitness/AgentManagementFitnessCalculator.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/fitness/TitusFitnessCalculator.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/embedded/cloud/agent/player/ContainerPlayersManager.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/embedded/cloud/agent/player/JobPlayer.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/embedded/cloud/agent/player/PlayerParser.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/embedded/cloud/agent/player/RuleSelector.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/embedded/cloud/endpoint/rest/SimulatedAgentsServiceResource.java
- titus-testkit/src/test/java/com/netflix/titus/testkit/embedded/cloud/agent/player/PlayerParserTest.java
To prevent scheduling tasks on agent nodes where there were recent failures,
we need to track all recent errors on each agent instance, and aggregate them into
a single number describing agents quality. This information is used by `AgentManagementFitnessCalculator` as a multiplier to adjust (lower), the computed fitness value.
> Agent quality tracker

- titus-ext/runner/Dockerfile.gateway
- titus-ext/runner/Dockerfile.master
See GoogleContainerTools/kaniko#247
> do not start a gradle daemon during docker builds

- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/v3/grpc/GrpcAgentModelConverters.java
The unknown state is present in the TitusMaster core model, so we need
it here for the proper mapping. Furthermore using UNRECOGNIZED protobuf enum
value results in the serialization process failure. We should never use it,
and always map the core model values into equivalent GRPC enum values.
> Add InstanceStateUnknown in the InstanceLifecycleState enum

- titus-server-master/src/main/java/com/netflix/titus/master/appscale/service/AppScaleManagerConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/appscale/service/AppScaleManagerMetrics.java
- titus-server-master/src/main/java/com/netflix/titus/master/appscale/service/DefaultAppScaleManager.java
- titus-server-master/src/test/java/com/netflix/titus/master/appscale/service/DefaultAppScaleManagerTest.java
new branch from v0.1.0-rc.78
Back-pressure handling for policy creation and deletion by providing ring buffer size for observeOn.
Bulk creation test to verify this behavior.
> Back pressure error handling 

- titus-ext/zookeeper/dependencies.lock
- titus-grpc-api/dependencies.lock
- titus-server-master/dependencies.lock
by https://titus.builds.test.netflix.net/job/titus-control-plane-lock-dependencies/60/
aopalliance:aopalliance: -> 1.0
c3p0:c3p0: -> 0.9.1.1
cglib:cglib-nodep: -> 3.1
com.101tec:zkclient: -> 0.4
com.101tec:zkclient: 0.4 ->
com.addthis.metrics:reporter-config3: -> 3.0.0
com.addthis.metrics:reporter-config-base: -> 3.0.0
com.amazonaws:aws-java-sdk-autoscaling: 1.11.390 -> 1.11.393
com.amazonaws:aws-java-sdk-core: 1.11.390 -> 1.11.393
com.amazonaws:aws-java-sdk-ec2: 1.11.390 -> 1.11.393
com.amazonaws:aws-java-sdk-elasticloadbalancingv2: 1.11.390 -> 1.11.393
com.amazonaws:jmespath-java: 1.11.390 -> 1.11.393
com.boundary:high-scale-lib: -> 1.0.6
com.carrotsearch:hppc: -> 0.5.4
com.clearspring.analytics:stream: -> 2.5.2
com.datastax.cassandra:cassandra-driver-core: -> 3.3.2 …
> Dependencies updated and locked

- titus-ext/elasticsearch/src/main/java/com/netflix/titus/ext/elasticsearch/ElasticsearchTaskDocumentPublisher.java
- titus-server-master/src/main/java/com/netflix/titus/master/MetricConstants.java
A full v3TasksStream needs to be wrapped with titusRuntime.persistentStream. This is to ensure any errors downstream won't terminate it.
> es publisher wrapped in retry w/ exponential backoff

- titus-common/src/main/java/com/netflix/titus/common/aws/AwsInstanceType.java
- titus-server-master/src/main/java/com/netflix/titus/master/clusteroperations/ClusterOperationsConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/service/management/internal/DefaultAvailableCapacityService.java
- titus-server-master/src/main/java/com/netflix/titus/master/service/management/internal/ResourceConsumptionEvaluator.java
- titus-server-master/src/test/java/com/netflix/titus/master/service/management/internal/DefaultAvailableCapacityServiceTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/service/management/internal/ResourceConsumptionEvaluatorTest.java
* Remove buffer from each capacity group in order to have a global shared buffer.
* Use only the current instance count instead of max for the critical tier within an instance group to determine available capacity.
> Update critical tier capacity group behavior

- titus-api/src/main/java/com/netflix/titus/api/model/Pagination.java
- titus-common/src/main/java/com/netflix/titus/common/util/Evaluators.java
- titus-common/src/main/java/com/netflix/titus/common/util/StringExt.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/service/v3/internal/GatewayJobManagementClient.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/JobCursorArchiveQueryTest.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/jobmanager/JobManagerCursors.java
In the `findTasks` operation with the `jobIds` query parameter, only the first page was returned for the archived data set.
> Fix tasks pagination for the archived data set

- build.gradle
Logs were too large to print always.  It was exceeding the TravisCI 4MB
limit.
> Only print stdout/stderr when a test fails

- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/v3/grpc/DefaultJobManagementServiceGrpc.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/v3/grpc/DefaultLoadBalancerServiceGrpc.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/v3/grpc/TitusPaginationUtils.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/v3/rest/JobManagementResource.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/v3/rest/LoadBalancerResource.java
- titus-server-runtime/src/test/java/com/netflix/titus/runtime/endpoint/v3/rest/LoadBalancerResourceTest.java
Pagination with page numbers will be deprecated and removed, this will help track callers of the API to assist in migrating them to cursors.
> emit a system log event for API calls using page numbers

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/validator/FailJobValidator.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/validator/ParallelValidator.java
- titus-api/src/test/java/com/netflix/titus/api/jobmanager/model/job/validator/NeverJobValidator.java
- titus-api/src/test/java/com/netflix/titus/api/jobmanager/model/job/validator/ParallelValidatorTest.java
- titus-common/src/main/java/com/netflix/titus/common/model/validator/ValidationError.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/JobValidatorNegativeTest.java
The ParallelValidator parallelizes execution of soft/hard validators.
Failure to return within the indicated timeout generates soft/hard
ValidationErrors respectively.
> Add validator to evaluate validators in parallel

- titus-server-master/src/main/java/com/netflix/titus/master/agent/AgentModule.java
- titus-server-master/src/main/java/com/netflix/titus/master/agent/store/AgentStoreReaper.java
- titus-server-master/src/main/java/com/netflix/titus/master/agent/store/AgentStoreReaperConfiguration.java
- titus-server-master/src/test/java/com/netflix/titus/master/agent/store/AgentStoreReaperTest.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/v3/grpc/ErrorResponses.java
Too short delay, may cause too eager data cleanup if there is a connectivity issue to AWS.
> AgentStoreReaper retention period should be configurable and have longer default delay

- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/jobmanager/client/GrpcJobManagementClient.java
In order to track with applications are violating validation rules its helpful to tag their metrics with the application name.
> Add application name to the metatron validation metrics tags

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/service/V3JobOperations.java
- titus-common/src/main/java/com/netflix/titus/common/util/FunctionExt.java
- titus-grpc-api/dependencies.lock
- titus-server-federation/src/main/java/com/netflix/titus/federation/service/AggregatingJobManagementClient.java
- titus-server-federation/src/test/java/com/netflix/titus/federation/service/AggregatingJobManagementClientTest.java
- titus-server-federation/src/test/java/com/netflix/titus/federation/service/CellWithFixedJobsService.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/endpoint/v3/grpc/DefaultJobManagementServiceGrpc.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/DefaultV3JobOperations.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/JobFederationTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/JobObserveTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/loadbalancer/service/DefaultLoadBalancerServiceTest.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/jobmanager/JobManagementClient.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/jobmanager/client/GrpcJobManagementClient.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/jobmanager/client/JobManagementClientDelegate.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/jobmanager/replicator/GrpcJobReplicatorEventStream.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/common/grpc/CommonGrpcModelConverters.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/v3/grpc/DefaultJobManagementServiceGrpc.java
- titus-server-runtime/src/test/java/com/netflix/titus/runtime/connector/jobmanager/replicator/GrpcJobReplicatorEventStreamTest.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/perf/load/runner/Terminator.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/rx/RxGrpcJobManagementService.java
Allow gRPC event streams (`JobManagement`) to be filtered, with the same criteria that can be used with `FindJobs` and `FindTasks`.
This depends on Netflix/titus-api-definitions#59. I will modify this PR once it gets merged with the dependencies updated.
> Server side filters for JobManagement event streams

- titus-server-master/src/main/java/com/netflix/titus/master/TitusRuntimeModule.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/MesosSchedulerCallbackHandler.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/MesosStateTracker.java
TitusMaster/Mesos state synchronization is eventually consistent, and this triggers many 
false positive orphaned containers alerts. To eliminate the false positives, we need to track
state for each unknown task, and emit alert only above certain duration threshold.
> Improve orphaned tasks metrics/reporting

- titus-api/src/test/java/com/netflix/titus/api/jobmanager/model/job/validator/ParallelValidatorTest.java
In Travis, it can take more than `10 ms` for even the PassValidator to return.  This causes test flakiness.
> Increase test timeout to accomodate clow CI machines

- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/validator/JobImageValidatorConfiguration.java
This PR enables tag to digest resolution by default. The previous PR was defaulted to disabled as we were waiting for a Platform Security Metatron server change to roll out. That Metatron change is now deployed to all regions so this resolution change can be enabled in all regions.
Even when enabled, the resolution still fails open. That means that a job is reject only when we can confirm the image does not exist. Any other error (e.g., failure to talk to registry, timeouts, etc...) fail open and allow the job to proceed with no digest.
> Enable tag to digest resolution by default

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/JobFunctions.java
- titus-common/src/main/java/com/netflix/titus/common/data/generator/DataGenerator.java
- titus-common/src/main/java/com/netflix/titus/common/data/generator/internal/MappedWithIndexDataGenerator.java
- titus-common/src/main/java/com/netflix/titus/common/util/Evaluators.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/service/v3/internal/GatewayJobManagementClient.java
- titus-server-gateway/src/test/java/com/netflix/titus/gateway/service/v3/internal/GatewayJobManagementClientTest.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/WorkerStateMonitor.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/GrpcClientConfiguration.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/embedded/cloud/agent/SimulatedTitusAgent.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/model/job/JobGenerator.java
In a specific scenario tasks search pagination was broken. When user:
* executed findTasks query
* with job ids as query parameter
* with task states that included both active and archived states
only the first page of the active data would be returned correctly.
The pagination was not broken if cursor was used.
> Fix tasks by page number pagination

- titus-ext/elasticsearch/src/main/java/com/netflix/titus/ext/elasticsearch/TaskDocument.java
This PR changes the Elasticsearch Task Document to also include a task's digest in the published document.
> Add image digest to ES task document

- titus-common/src/main/java/com/netflix/titus/common/util/ExceptionExt.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/TaskPlacementRecorder.java
Including an exception message in the job transaction log is not enough, as often it is a null value.
> Better job transaction error logging in TaskPlacementRecorder

- titus-common/src/main/java/com/netflix/titus/common/network/client/internal/RetryableRestClient.java
- titus-common/src/main/java/com/netflix/titus/common/network/client/internal/RxClientMetric.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/registry/DefaultDockerRegistryClient.java
This PR does 2 key things:
1. Fixes a bug where DefaultDockerRegistryClient had a extraneous timeout check. It should instead just rely on how it has configured its RxRestClient.
2. It makes the RxRestClient metric tags a bit more consistent and adds a retriesExhausted value.
> Rely on RxRestClient timeouts and add/cleanup RxRestClient metrics

- .travis.yml
- README.md
- buildViaTravis.sh
Followup of #392. Run `docker-compose up` on every build (as a separate travis job), and ensure the control plane comes up and is ready to serve requests.
This doesn't currently try to run any tasks (as nested containers), but that can be a simple addition in the future. PRs will not be gated on failures for now, we can enable that later if/when we get some confidence it will not be flaky.
Example execution: https://travis-ci.org/Netflix/titus-control-plane/builds/441950564
> CI: ensure docker-compose (as documented in README.md) works

- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/registry/DefaultDockerRegistryClient.java
This PR removes an unneeded usage of `first()`. In addition to not being needed, `first()` unsubscribes from the source observable after the first item is emitted, which led to the RxNettyRestClient not emitting `.doOnTerminate()` metrics.
> Remove unneeded usage of first()

- build.gradle
- titus-ext/aws/build.gradle
- titus-ext/aws/src/main/java/com/netflix/titus/ext/aws/AmazonAutoScalingProvider.java
- titus-ext/aws/src/main/java/com/netflix/titus/ext/aws/AwsModule.java
- titus-ext/aws/src/main/java/com/netflix/titus/ext/aws/RetryWrapper.java
- titus-ext/aws/src/main/java/com/netflix/titus/ext/aws/appscale/AWSAppAutoScalingClient.java
- titus-ext/aws/src/main/java/com/netflix/titus/ext/aws/appscale/AWSAppScalingConfig.java
- titus-ext/aws/src/main/java/com/netflix/titus/ext/aws/cloudwatch/CloudWatchClient.java
- titus-ext/aws/src/test/java/com/netflix/titus/ext/aws/appscale/AWSAppAutoScalingClientTest.java
This PR moves the Job Autoscaling AWS clients to control-plane. Any new files in the PR were simply moved with only modifications to cleanup imports and add headers.
Additionally, we are now relying on the normal AWS Java SDK for application autoscaling.
> Move job autoscaling AWS autoscale/cloudwatch clients to control-plane

- titus-server-federation/src/main/java/com/netflix/titus/federation/endpoint/grpc/TitusFederationGrpcServer.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/endpoint/v3/grpc/TitusGatewayGrpcServer.java
- titus-server-master/src/main/java/com/netflix/titus/master/endpoint/grpc/TitusMasterGrpcServer.java
In the recent change that improves the ephemeral port allocation for the embedded GRPC servers
accidentally there was removed code reading the GRPC port from configuration. As a result, the
GRPC servers were always run on a random ephemeral ports.
> Read the GRPC port from configuration

- titus-ext/aws/src/main/java/com/netflix/titus/ext/aws/appscale/AWSAppAutoScalingClient.java
- titus-ext/aws/src/main/java/com/netflix/titus/ext/aws/appscale/AWSAppAutoScalingMetrics.java
This PR does the following:
1) Cleans up how the AppScaling client manages metrics. This change should help with subsequent metrics improvements.
2) Add `errorCode` tag to AWS AppScaling error metrics.
> Add error code tag to AWS app autoscaling metrics

- titus-ext/aws/src/main/java/com/netflix/titus/ext/aws/appscale/AWSAppAutoScalingClient.java
- titus-ext/aws/src/main/java/com/netflix/titus/ext/aws/appscale/AWSAppScalingConfig.java
This PR removes passing of legacy IAM roles to AWS Application Autoscaling. These IAM roles were replaced by Service Linked Roles back in June and have been extraneous since then.
> Do not pass unused IAM role to AWS App Autoscaling

- titus-ext/aws/src/main/java/com/netflix/titus/ext/aws/appscale/AWSAppAutoScalingClient.java
- titus-ext/aws/src/main/java/com/netflix/titus/ext/aws/appscale/AWSAppAutoScalingUtil.java
- titus-ext/aws/src/main/java/com/netflix/titus/ext/aws/appscale/AWSAppScalingConfig.java
- titus-ext/aws/src/test/java/com/netflix/titus/ext/aws/appscale/AWSAppAutoScalingUtilTest.java
refactoring AWSAppAutoScalingClient in order to isolate logic for building entities such as policy name, resource Id. Also removes service namespace and scalable dimension into a publicly accessible location.
> moving policyName, resourceId in a util class

- titus-server-master/src/main/java/com/netflix/titus/master/loadbalancer/service/TargetStateBatchable.java
Really small change, right now objects being logged by the `LoadBalancerEngine` are being shown as Java reference ids.
> fix ip target details on logs

- .travis.yml
- titus-server-master/src/main/java/com/netflix/titus/master/endpoint/grpc/GrpcEndpointConfiguration.java
> use openjdk 8 on travis ci

- titus-ext/elasticsearch/src/main/java/com/netflix/titus/ext/elasticsearch/ElasticsearchTaskDocumentPublisher.java
time since last elastic search published is using AGE function from spectator library
> time since last successful elastic search published

- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/v3/grpc/TitusPaginationUtils.java
If the request has a cursor, any page numbers are ignored, and the cursor will be used instead.
> with a cursor on the request, no need to log pageNumber use

- titus-server-gateway/src/main/java/com/netflix/titus/gateway/endpoint/v3/rest/AgentManagementResource.java
- titus-server-master/src/main/java/com/netflix/titus/master/agent/AgentAttributes.java
- titus-server-master/src/main/java/com/netflix/titus/master/agent/endpoint/grpc/DefaultAgentManagementServiceGrpc.java
- titus-server-master/src/main/java/com/netflix/titus/master/agent/service/DefaultAgentManagementService.java
- titus-server-master/src/main/java/com/netflix/titus/master/clusteroperations/ClusterAgentAutoScaler.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/SchedulerConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/fitness/AgentManagementFitnessCalculator.java
- titus-server-master/src/test/java/com/netflix/titus/master/agent/service/DefaultAgentManagementServiceTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/clusteroperations/ClusterAgentAutoScalerTest.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/agent/AgentManagementClient.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/agent/client/GrpcAgentManagementClient.java
* add API to update agent instance attributes
* add ability to add nonRemovable agent attribute to an instance group to prevent any instance from being scaled away
* reduce phased out score and also use the attribute preferNoPlacement
* make critical tier spreading by jobId the default behavior
> Agent Management Improvements

- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/JobRetryTest.java
- titus-testkit/src/test/java/com/netflix/titus/testkit/embedded/cloud/connector/AbstractSimulatedMesosSchedulerDriverTest.java
In `JobRetryTest` all tests used the same application name/job group info which somtimes caused
job create errors:
`
com.netflix.titus.master.integration.v3.job.JobRetryTest > testServiceJobFailsAfterRetrying FAILED
java.lang.RuntimeException: GRPC status Status{code=INVALID_ARGUMENT, description=JobManagerException: Constraint violation - job with group sequence v3App-main-GA-v000 exists (7e4d6e5b-1522-4021-81b9-542df881cfe6), cause=null}: JobManagerException: Constraint violation - job with group sequence v3App-main-GA-v000 exists (7e4d6e5b-1522-4021-81b9-542df881cfe6)
`
`AbstractSimulatedMesosSchedulerDriverTest` incorrectly handled offers in the `testTaskKill` test.
> Flaky tests in AbstractSimulatedMesosSchedulerDriverTest and JobRetryTest classes

- .travis.yml
- build.gradle
- titus-api/dependencies.lock
- titus-common/dependencies.lock
- titus-ext/aws/dependencies.lock
- titus-ext/cassandra-testkit/dependencies.lock
- titus-ext/cassandra/dependencies.lock
- titus-ext/elasticsearch/dependencies.lock
- titus-ext/eureka/dependencies.lock
- titus-ext/jooq/dependencies.lock
- titus-ext/zookeeper/dependencies.lock
- titus-server-federation/dependencies.lock
- titus-server-gateway/dependencies.lock
- titus-server-master/dependencies.lock
- titus-server-runtime/dependencies.lock
- titus-supplementary-component/task-relocation/dependencies.lock
The docker-compose test on Travis is failing because of an incompatibility in transitive dependencies with the version of `jackson-databind` we are using.
This also forces all docker-compose logs to be dumped on Travis when the test fails, which helps immensely with understanding why containers didn't come up.
All PRs will now be gated on integration and docker tests passing (in addition to the unit tests that were required before).
> fix docker-compose test, force integration tests to run on every build

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/event/JobManagerEvent.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/event/TaskUpdateEvent.java
- titus-api/src/main/java/com/netflix/titus/api/loadbalancer/model/JobLoadBalancer.java
- titus-common/src/main/java/com/netflix/titus/common/util/CollectionsExt.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/DefaultV3JobOperations.java
- titus-server-master/src/main/java/com/netflix/titus/master/loadbalancer/service/DefaultLoadBalancerService.java
- titus-server-master/src/main/java/com/netflix/titus/master/loadbalancer/service/LoadBalancerEngine.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/MoveTaskTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/scenario/StubbedJobStore.java
- titus-server-master/src/test/java/com/netflix/titus/master/loadbalancer/service/DefaultLoadBalancerServiceTest.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/jobmanager/replicator/GrpcJobReplicatorEventStream.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/v3/grpc/V3GrpcModelConverters.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/client/V3ClientUtils.java
Task events from `JobOperations` will now have a flag indicating when a task moved from another job. This allows subscribers to update their indexes and act accordingly.
This PR also adds handling of tasks being moved to the `LoadBalancerEngine`, so IPs get properly deregistered/registered as tasks move to a different Job.
The information about tasks moving is not being added to the public gRPC APIs yet. That will come in another PR, along with changes to some components already using the gRPC event stream. I added some `TODOs` where changes will be required.
> Signal that a task has been moved in TaskUpdateEvents

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/sanitizer/SchedulingConstraintValidator.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/constraint/ActiveHostConstraint.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/constraint/V3ConstraintEvaluatorTransformer.java
Add experimental `ActiveHost` constraint such that users can use it as a soft or hard constraint depending on their requirements of landing on a host within an `Active` instance group when submitting a job.
> add experimental active host constraint

- titus-server-master/src/main/java/com/netflix/titus/master/mesos/MesosSchedulerCallbackHandler.java
Ignore task lost status updates from mesos if it is a reconciliation message and the job management component does not know about the task.
> ignore task lost status updates from mesos in specific cases

- titus-api/dependencies.lock
- titus-common/build.gradle
- titus-common/dependencies.lock
- titus-common/src/main/java/com/netflix/titus/common/util/ProtobufExt.java
- titus-common/src/test/java/com/netflix/titus/common/util/ProtobufDiffTest.java
- titus-ext/aws/dependencies.lock
- titus-ext/cassandra-testkit/dependencies.lock
- titus-ext/cassandra/dependencies.lock
- titus-ext/elasticsearch/dependencies.lock
- titus-ext/eureka/dependencies.lock
- titus-ext/jooq/dependencies.lock
- titus-ext/zookeeper/dependencies.lock
- titus-grpc-api/dependencies.lock
- titus-server-federation/dependencies.lock
- titus-server-gateway/dependencies.lock
- titus-server-master/dependencies.lock
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/MoveTaskTest.java
- titus-server-runtime/dependencies.lock
- titus-supplementary-component/task-relocation-springboot/dependencies.lock
- titus-supplementary-component/task-relocation/dependencies.lock
- titus-testkit/dependencies.lock
... and temporarily disable full diffing of JobDescriptor protobufs on job compatibility violations. This will provide a less nice message on validation errors for the `MoveTask` operation.
`google-truth` requires a more recent version of guava that is incompatible with Curator. A future PR will re-introduce the diff without causing transitive dependency incompatibilities.
> remove google-truth

- build.gradle
- titus-api/dependencies.lock
- titus-common/build.gradle
- titus-common/dependencies.lock
- titus-common/src/main/java/com/netflix/titus/common/util/ProtobufExt.java
- titus-common/src/test/java/com/netflix/titus/common/util/ProtobufDiffTest.java
- titus-ext/aws/dependencies.lock
- titus-ext/cassandra-testkit/dependencies.lock
- titus-ext/cassandra/dependencies.lock
- titus-ext/elasticsearch/dependencies.lock
- titus-ext/eureka/dependencies.lock
- titus-ext/jooq/dependencies.lock
- titus-ext/zookeeper/dependencies.lock
- titus-server-federation/dependencies.lock
- titus-server-gateway/dependencies.lock
- titus-server-master/dependencies.lock
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/MoveTaskTest.java
- titus-server-runtime/dependencies.lock
- titus-supplementary-component/task-relocation-springboot/dependencies.lock
- titus-supplementary-component/task-relocation/dependencies.lock
- titus-testkit/dependencies.lock
Pull in an older version that doesn't depend on recent versions of Guava. The older version does what we need it to do, and we don't use any of the functionality in google-truth itself, we only rely on the `ProtobufMessageDifferencer` functionality.
> try google truth again

- titus-common/src/main/java/com/netflix/titus/common/util/rx/RetryHandlerBuilder.java
- titus-common/src/test/java/com/netflix/titus/common/util/rx/RetryHandlerBuilderTest.java
Reactor based retry builder code uses FluxInterval to generate timer events. It throws IllegalArgumentException when period < 0. The fix is meant to address this issue
> retry builder fix for reactor based unlimited retries

- titus-common/src/main/java/com/netflix/titus/common/util/rx/RetryHandlerBuilder.java
retry delay expression overflows at retry #31, as a result we use maxDelay for subsequent retries
> retry delay overflow fixed

- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/v3/grpc/DefaultAutoScalingServiceGrpc.java
Information being logged is redundant with metrics being published.
> minor: reduce log verbosity from grpc requests to appscale

- build.gradle
- titus-api/dependencies.lock
- titus-common/dependencies.lock
- titus-ext/aws/dependencies.lock
- titus-ext/cassandra/dependencies.lock
- titus-ext/elasticsearch/dependencies.lock
- titus-ext/eureka/dependencies.lock
- titus-ext/jooq/dependencies.lock
- titus-ext/zookeeper/build.gradle
- titus-ext/zookeeper/dependencies.lock
- titus-ext/zookeeper/src/test/java/com/netflix/titus/ext/zookeeper/supervisor/ZookeeperLeaderElectorTest.java
- titus-server-federation/dependencies.lock
- titus-server-gateway/dependencies.lock
- titus-server-master/build.gradle
- titus-server-master/dependencies.lock
- titus-server-runtime-spring/dependencies.lock
- titus-server-runtime/dependencies.lock
- titus-supplementary-component/job-activity-history-springboot/dependencies.lock
- titus-supplementary-component/job-activity-history/dependencies.lock
- titus-supplementary-component/task-relocation-springboot/dependencies.lock
- titus-supplementary-component/task-relocation/dependencies.lock
- titus-testkit/dependencies.lock
As described here: https://curator.apache.org/zk-compatibility.html
```
Curator 4.0 has a hard dependency on ZooKeeper 3.5.x
If you are using ZooKeeper 3.5.x there's nothing additional to do - just use Curator 4.0
```
Although it is possible to run Curator 4.x with Zookeper 3.4.x in a compatibility mode,
not all operations are available. In our case we hit this issue, as for at least one
operation we get UNIMPLEMENTED error.
> Rollback to Curator version 2.x

- titus-api/src/main/java/com/netflix/titus/api/agent/model/AgentInstance.java
- titus-api/src/main/java/com/netflix/titus/api/agent/model/AgentInstanceGroup.java
- titus-api/src/main/java/com/netflix/titus/api/agent/service/AgentManagementService.java
- titus-server-master/src/main/java/com/netflix/titus/master/agent/service/AgentManagementConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/agent/service/DefaultAgentManagementService.java
- titus-server-master/src/main/java/com/netflix/titus/master/agent/service/cache/AgentCache.java
- titus-server-master/src/main/java/com/netflix/titus/master/agent/service/cache/DataConverters.java
- titus-server-master/src/main/java/com/netflix/titus/master/agent/service/cache/DefaultAgentCache.java
- titus-server-master/src/main/java/com/netflix/titus/master/agent/service/cache/InstanceCache.java
- titus-server-master/src/main/java/com/netflix/titus/master/agent/service/cache/InstanceCacheEvent.java
- titus-server-master/src/main/java/com/netflix/titus/master/agent/store/AgentStoreReaper.java
- titus-server-master/src/test/java/com/netflix/titus/master/agent/service/cache/DefaultAgentCacheTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/agent/service/cache/InstanceCacheTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/agent/service/cache/InstanceTestUtils.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/embedded/cell/master/EmbeddedTitusMasters.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/model/agent/AgentGenerator.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/model/agent/StubbedAgentManagementService.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/stub/connector/cloud/TestableInstanceCloudConnector.java
Improve how the agent cache integrates with the instance cache by subscribing to specific instance cache events as well as periodically synchronizing to ensure correct state.
> Improve how the agent cache integrates with the instance cache

- titus-server-master/src/main/java/com/netflix/titus/master/service/management/CapacityManagementAttributes.java
- titus-server-master/src/main/java/com/netflix/titus/master/service/management/CapacityManagementFunctions.java
- titus-server-master/src/main/java/com/netflix/titus/master/service/management/internal/DefaultAvailableCapacityService.java
- titus-server-master/src/main/java/com/netflix/titus/master/service/management/internal/SimpleCapacityGuaranteeStrategy.java
Add capacity management attribute to ignore instance group when doing calculations and setting instance group mins.
> add capacity management attribute to ignore instance group

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/JobCompatibility.java
- titus-api/src/test/java/com/netflix/titus/api/jobmanager/model/job/JobCompatibilityTest.java
- titus-common/src/main/java/com/netflix/titus/common/util/feature/FeatureComplianceLogger.java
... since these are mutable and should never affect the runtime behavior of a Task.
> Ignore JobDescriptor attributes for MoveTask compatibility checks

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/JobFunctions.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/JobType.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/DefaultV3TaskInfoFactory.java
The cpu prediction model requires the job type (service or batch) be available on the Agent.
> Add job type (service or batch) field to passthrough attributes

- titus-ext/jooq/build.gradle
- titus-ext/jooq/src/main/java/com/netflix/titus/ext/jooq/JooqConfiguration.java
- titus-ext/jooq/src/main/java/com/netflix/titus/ext/jooq/JooqConfigurationBean.java
- titus-ext/jooq/src/main/java/com/netflix/titus/ext/jooq/JooqModule.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/util/SpringConfigurationUtil.java
Adds the ability for the JooqModule to use an in-memory DB during injection based on a property. We use HSQL, which is what was used previously for test.
> Add property to initialize Jooq with an in-memory DB instead of Postgres

- titus-ext/jooq/src/main/java/com/netflix/titus/ext/jooq/JooqModule.java
- titus-ext/jooq/src/main/java/com/netflix/titus/ext/jooq/JooqUtils.java
- titus-ext/jooq/src/main/java/com/netflix/titus/ext/jooq/jobactivity/JooqJobActivityPublisherStore.java
- titus-ext/jooq/src/main/java/com/netflix/titus/ext/jooq/relocation/JooqTaskRelocationResultStore.java
- titus-ext/jooq/src/main/java/com/netflix/titus/ext/jooq/relocation/JooqTaskRelocationStore.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobactivity/service/JobActivityPublisher.java
This PR explicitly sets DB AutoCommit (https://docs.oracle.com/javase/6/docs/api/java/sql/Connection.html?is-external=true#setAutoCommit(boolean)) for all jOOQ stores. With autocommit, each store does not need to explicitly create their own transactions.
There is also a safety check in the Publisher that consumes the `observeJobs()` stream so that we don't accidentally propagate an Exception back to the publisher.
> Explicity set jOOQ autocommit and remove explicit transaction creation from jOOQ Stores

- titus-common/src/main/java/com/netflix/titus/common/network/client/TitusWebClientAddOns.java
Adds the statusCode tag to metrics emitted by WebClient. This value was emitted by RxNettyRestClient but missing from this new client.
> Add status code to WebClient metrics

- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/v3/grpc/V3GrpcModelConverters.java
Converting from grpc model to core Job/Task model is missing timestamp field. As a result Elastic search publishing (Es5) is recording incorrect timestamps for task fields.
> timestamp missing from conversion to core model

- titus-supplementary-component/tasks-publisher/src/main/java/com/netflix/titus/supplementary/taskspublisher/TasksPublisherCtrl.java
- titus-supplementary-component/tasks-publisher/src/main/java/com/netflix/titus/supplementary/taskspublisher/config/TasksPublisherConfiguration.java
Removing partial spring configuration override for building TasksPublisherCtrl objects. Changes to the default configuration makes it easy to override.
> spring config fix for task context map

- titus-server-gateway/src/test/java/com/netflix/titus/gateway/service/v3/internal/JobImageValidatorTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/JobSanitizeTest.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/registry/TitusRegistryClientConfiguration.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/validator/JobImageValidator.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/validator/JobImageValidatorConfiguration.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/validator/JobSecurityValidatorConfiguration.java
- titus-server-runtime/src/test/java/com/netflix/titus/runtime/connector/registry/RegistryClientTest.java
Without an explicit timeout, the sanitization chain was failing with the default timeout from `AggregatingValidator` (2s), which does not provide a useful message. It fails with something like:
> Did not observe any item or terminal signal within 2000ms in 'flatMap' (and no fallback has been configured)
> add a timeout to image sanitization/validation

- titus-common/src/main/java/com/netflix/titus/common/network/client/TitusWebClientAddOns.java
- titus-common/src/main/java/com/netflix/titus/common/network/client/internal/WebClientMetric.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/registry/DefaultDockerRegistryClient.java
- Moves WebClient Metrics to its own metrics-specific class.
- Records latency docker registry client requests.
> Add latency metric for regitry WebClient

- titus-server-gateway/src/main/java/com/netflix/titus/gateway/startup/TitusGateway.java
`TitusGateway` is used in the docker-compose integration test, which
does not include TaskRelocation service yet.
> Disable the TaskRelocation connector in TitusGateway

- build.gradle
- titus-api/dependencies.lock
- titus-common/dependencies.lock
- titus-ext/aws/dependencies.lock
- titus-ext/cassandra-testkit/dependencies.lock
- titus-ext/cassandra/dependencies.lock
- titus-ext/elasticsearch/dependencies.lock
- titus-ext/eureka/dependencies.lock
- titus-ext/jooq/dependencies.lock
- titus-ext/zookeeper/dependencies.lock
- titus-grpc-api/dependencies.lock
- titus-server-federation/dependencies.lock
- titus-server-gateway/dependencies.lock
- titus-server-master/dependencies.lock
- titus-server-runtime-spring/dependencies.lock
- titus-server-runtime/dependencies.lock
- titus-supplementary-component/job-activity-history-springboot/dependencies.lock
- titus-supplementary-component/job-activity-history/dependencies.lock
- titus-supplementary-component/task-relocation-springboot/dependencies.lock
- titus-supplementary-component/task-relocation/dependencies.lock
- titus-supplementary-component/tasks-publisher-springboot/dependencies.lock
- titus-supplementary-component/tasks-publisher/dependencies.lock
- titus-testkit/dependencies.lock
spring-boot 2.1.4 brings in tomcat-embed-core 9.0.17 which has incompatibilities with an internal TLS library used at Netflix.
Pin to 2.1.3, which is the recommended version ATM.
> pin spring-boot to 2.1.3

- .circleci/config.yml
- .travis.yml
- buildViaTravis.sh
Travis is being a bit too slow when running integration tests. This is an experiment in using CircleCI to see if it does any better.
I left tests running in both Travis and Circle so we can compare after a while.
> basic circle ci config to run all tests

- titus-supplementary-component/tasks-publisher/src/main/java/com/netflix/titus/supplementary/taskspublisher/EsPublisher.java
- titus-supplementary-component/tasks-publisher/src/main/java/com/netflix/titus/supplementary/taskspublisher/TaskEventsGenerator.java
- titus-supplementary-component/tasks-publisher/src/main/java/com/netflix/titus/supplementary/taskspublisher/TaskPublisherRetryUtil.java
- titus-supplementary-component/tasks-publisher/src/main/java/com/netflix/titus/supplementary/taskspublisher/TasksPublisher.java
- titus-supplementary-component/tasks-publisher/src/main/java/com/netflix/titus/supplementary/taskspublisher/config/TasksPublisherConfiguration.java
- titus-supplementary-component/tasks-publisher/src/test/java/com/netflix/titus/supplementary/taskspublisher/TaskEventsGeneratorTest.java
Current implementation of tasks publisher needs to be broken into a few separate components. 
1. TaskEventsGenerator - it listens to TitusAPI stream for job and task updates, builds a document that contains all the task state + job metadata and is ready to be published
2. TasksPublisher - interface defines publisher contract
3. EsPublisher - implements TasksPublisher that grabs task events generated from TaskEventsGenerator and is responsible for managing elastic search integration that publishes task documents.
The design enables hooking up additional publishers by decoupling task document building and actual publishing mechanism.
> Tasks publisher refactoring

- titus-ext/elasticsearch/src/main/java/com/netflix/titus/ext/elasticsearch/ElasticsearchModule.java
Transport client needs to be created only when elastic search publisher is enabled.
> transport client creation only when enabled

- titus-ext/jooq/build.gradle
- titus-ext/jooq/src/jooq/resources/log4j.properties
quiesce logs from the jooq source code generator that runs during gradle builds
> less verbose jooq logs during builds

- titus-common/src/test/java/com/netflix/titus/common/framework/scheduler/internal/DefaultLocalSchedulerTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/eviction/service/quota/system/SystemQuotaControllerTest.java
- titus-supplementary-component/task-relocation/src/test/java/com/netflix/titus/supplementary/relocation/integration/TaskRelocationIntegrationTest.java
... by increasing some test timeouts. I'm anecdotally noticing more flakiness in some unit tests after I added the `--parallel` flag. Let's see if this improves it.
cc @tbak @corindwyer (not asking for PR reviews since this is trivial)
> try to reduce test flakiness on Travis

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/JobFunctions.java
- titus-ext/eureka/src/main/java/com/netflix/titus/ext/eureka/containerhealth/EurekaContainerHealthService.java
- titus-ext/eureka/src/test/java/com/netflix/titus/ext/eureka/containerhealth/EurekaContainerHealthServiceTest.java
- titus-supplementary-component/task-relocation/src/main/java/com/netflix/titus/supplementary/relocation/RelocationConfiguration.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/junit/asserts/ContainerHealthAsserts.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/model/job/JobComponentStub.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/model/job/JobDescriptorGenerator.java
If a container is in OUT_OF_SERVICE state in Eureka, its real state is lost. This forces us two chose between two strategies:
* assume containers are down, and report them as unhealthy
* assume containers are up, and report them as healthy
The former strategy was assumed before this change. This resulted in large pools of resources to be excluded from the relocation process. We switch to the latter strategy, accepting that this may increase the risk for service availability during rollbacks.
> Enable task relocation for containers in  Eureka/OUT_OF_SERVICE state

- build.gradle
Pin the titus api definitions version to `0.0.1-rc61`
> pin the titus api definitions version to 0.0.1-rc61

- titus-common/src/main/java/com/netflix/titus/common/util/spectator/AuthorizationMetrics.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/endpoint/v3/grpc/JobAuthorizationService.java
This is change supports changes to nftitus. There are 2 main changes:
1. Adds common authorization metrics
2. Moves all feature predicate checking to the sub-class implementing `protected abstract Mono<AuthorizationStatus> authorize()`. Note that because this moves the predicate check it depends on the companion PR to properly scope which apps to check.
> Minor refactor to support IAM Role authorization

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/JobAttributes.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/JobCompatibility.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/JobFunctions.java
- titus-api/src/test/java/com/netflix/titus/api/jobmanager/model/job/JobCompatibilityTest.java
- titus-common/src/main/java/com/netflix/titus/common/util/CollectionsExt.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/service/v3/internal/GatewayJobServiceGateway.java
- titus-server-gateway/src/test/java/com/netflix/titus/gateway/service/v3/internal/JobImageValidatorTest.java
- titus-server-gateway/src/test/java/com/netflix/titus/gateway/service/v3/internal/JobSecurityValidatorTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/JobAttributesTest.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/validator/JobIamValidator.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/validator/JobImageValidator.java
When a job is cloned and either one of the copies had sanitization failures, they can have different values for the non-sanitized field(s), but are still compatible.
This PR also ignores all user-supplied `titus.sanitization.*` attributes for new jobs, since these are reserved and automatically filled by Titus.
> track Jobs with sanitization (open) failures, and relax moveTask validation for them

- titus-server-gateway/src/main/java/com/netflix/titus/gateway/service/v3/internal/GatewayJobServiceGateway.java
- titus-server-gateway/src/test/java/com/netflix/titus/gateway/service/v3/internal/JobImageSanitizerTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/JobSanitizeTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/JobValidatorNegativeTest.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/AdmissionSanitizer.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/AggregatingValidator.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/FailJobValidator.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/JobIamValidator.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/JobImageSanitizer.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/PassJobValidator.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/TitusAdmissionModule.java
- titus-server-runtime/src/test/java/com/netflix/titus/runtime/endpoint/admission/AggregatingValidatorTest.java
- titus-server-runtime/src/test/java/com/netflix/titus/runtime/endpoint/admission/NeverJobValidator.java
- titus-server-runtime/src/test/java/com/netflix/titus/runtime/endpoint/admission/TestingAppNameSanitizer.java
- titus-server-runtime/src/test/java/com/netflix/titus/runtime/endpoint/admission/TestingCapacityGroupSanitizer.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/embedded/cell/EmbeddedTitusCell.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/embedded/cell/gateway/EmbeddedTitusGateway.java
This prepares the ground for more advanced sanitization logic, and dedicated sanitizers that are not validators (and vice versa).
> admission: split sanitization and validation into different interfaces

- titus-api/src/main/java/com/netflix/titus/api/service/TitusServiceException.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/service/v3/internal/GatewayJobServiceGateway.java
- titus-server-gateway/src/test/java/com/netflix/titus/gateway/service/v3/internal/JobImageSanitizerTest.java
- titus-server-gateway/src/test/java/com/netflix/titus/gateway/service/v3/internal/JobSecurityValidatorTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/JobSanitizeTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/JobValidatorNegativeTest.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/AdmissionSanitizer.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/AggregatingSanitizer.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/AggregatingValidator.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/FailJobValidator.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/JobIamValidator.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/JobImageSanitizer.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/PassJobValidator.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/TitusAdmissionModule.java
- titus-server-runtime/src/test/java/com/netflix/titus/runtime/endpoint/admission/AggregatingSanitizerTest.java
- titus-server-runtime/src/test/java/com/netflix/titus/runtime/endpoint/admission/AggregatingValidatorTest.java
- titus-server-runtime/src/test/java/com/netflix/titus/runtime/endpoint/admission/EmptyValidator.java
- titus-server-runtime/src/test/java/com/netflix/titus/runtime/endpoint/admission/NeverJobValidator.java
- titus-server-runtime/src/test/java/com/netflix/titus/runtime/endpoint/admission/TestingAppNameSanitizer.java
- titus-server-runtime/src/test/java/com/netflix/titus/runtime/endpoint/admission/TestingCapacityGroupSanitizer.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/embedded/cell/EmbeddedTitusCell.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/embedded/cell/gateway/EmbeddedTitusGateway.java
This will allow more (slow) sanitizers that call external services to be added.
> Run sanitizers concurrently

- .travis.yml
... preventing double builds for PRs (PR HEAD and PR merge commit).
See https://docs.travis-ci.com/user/pull-requests/#double-builds-on-pull-requests for more details.
PRs will still be built by travis, but only the result of merging them onto their source branches (usually master).
To ensure releases can still be pushed to Bintray, branch builds will be only executed for commits to `master`, release tags (`v0.0.1-rcN` format), and hotfix branches prefixed with `hotfix`.
> Travis "branch builds" for only master and release branches

- titus-api/src/main/java/com/netflix/titus/api/FeatureActivationConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/DefaultV3JobOperations.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/scenario/JobsScenarioBuilder.java
To be used in emergencies, when tasks need to be moved, and operators are sure their jobs are compatible, even when there are some differences in their job descriptors.
> flag for temporarily disabling MoveTask validation

- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/JobImageSanitizer.java
... since some exceptions are expected and OK (e.g.: image not found)
> only log the full stacktrace at DEBUG level

- titus-common/src/main/java/com/netflix/titus/common/network/client/ClientMetrics.java
- titus-common/src/main/java/com/netflix/titus/common/network/client/LatencyRecorder.java
- titus-common/src/main/java/com/netflix/titus/common/network/client/WebClientExt.java
- titus-common/src/main/java/com/netflix/titus/common/network/client/internal/WebClientMetric.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeApiServerIntegrator.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/registry/DefaultDockerRegistryClient.java
Some of the async code was incorrectly computing a start timestamp from when the async method gets called, instead of when the async computation begins (when requests are sent).
This adds a new reusable operator for async clients using `Mono` that automatically records latency metrics.
> Record success and error latencies for WebClients in a consistent way

- build.gradle
- titus-server-master/build.gradle
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/LeaseRescindedEvent.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/VirtualMachineMasterService.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/VirtualMachineMasterServiceMesosImpl.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/WorkerStateMonitor.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeApiServerIntegrator.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/Snapshot.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/SnapshotComparison.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/DefaultSchedulingService.java
- titus-server-master/src/main/java/com/netflix/titus/master/service/management/CapacityManagementAttributes.java
- titus-server-master/src/main/java/com/netflix/titus/master/service/management/CapacityManagementFunctions.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/scenario/StubbedVirtualMachineMasterService.java
- titus-server-master/src/test/java/com/netflix/titus/master/mesos/kubeapiserver/SnapshotTest.java
Update the experimental k8s integration to create snapshots of nodes and compare them to manage fenzo leases.
A simulated kubernetes api-server will be added in a future PR in order to be able to perform integration tests against this integration.
> Update experimental k8s integration

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/TaskAttributes.java
- titus-server-master/src/main/java/com/netflix/titus/master/clusteroperations/ClusterAgentAutoScaler.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/endpoint/v3/grpc/DefaultJobManagementServiceGrpc.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/DefaultSchedulingService.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/InUseIpAllocationConstraintFailure.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/SchedulingService.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/TaskPlacementFailure.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/TaskPlacementFailureClassifier.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/constraint/IpAllocationConstraint.java
- titus-server-master/src/test/java/com/netflix/titus/master/clusteroperations/ClusterAgentAutoScalerTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/JobIpAllocationsTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/scenario/StubbedSchedulingService.java
This PR adds a task context field to tasks that are not placed during scheduling because their assigned IP allocation is already in use by another task. This PR consists of the following changes:
1. Adds a new task placement failure type indicating that the task is waiting for an in use IP allocation.
2. When tasks are returned their task context is updated to reflect if the last placement failed because of an in use IP allocation.
3. Group task placement failures by task id to allow point queries when looking up failed allocations for specific tasks.
> Add task context for tasks waiting for in use IP allocations

- build.gradle
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/service/v3/internal/GatewayJobServiceGateway.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/jobmanager/gateway/JobServiceGateway.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/jobmanager/gateway/SanitizingJobServiceGateway.java
That way we avoid expensive validation/sanitization calls for obvious invalid payloads.
> Run admission control after basic entity validations

- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeApiServerIntegrator.java
Relevant network metadata is now provided in pod annotations.
> Retrieve network metadata from pod updates

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/JobCompatibility.java
- titus-api/src/test/java/com/netflix/titus/api/jobmanager/model/job/JobCompatibilityTest.java
This allows jobs to have a "shadow job" counterpart with slightly different configuration (ENV), e.g. disabling some behavior, that will only be enabled when a task is moved to another job.
(internal ref: TITUS-2997)
> allow ENV to differ when moving tasks between jobs

- build.gradle
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/JobDescriptor.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/sanitizer/JobAssertions.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/vpc/SignedIpAddressAllocation.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/service/JobManagerException.java
- titus-common/build.gradle
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/endpoint/v3/grpc/DefaultJobManagementServiceGrpc.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/JobIpAllocationsTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/JobSubmitAndControlNegativeTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/JobTestUtils.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/scenario/JobScenarioBuilder.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/common/rest/TitusExceptionMapper.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/v3/grpc/ErrorResponses.java
This PR adds two validations for IP allocations:
- Check that provided IP allocations signatures are Base64 encoded.
- Check that jobs cannot be created or updated with a max or size greater than their number of IP allocations.
> Add API validations for IP allocations

- build.gradle
- titus-ext/aws/dependencies.lock
- titus-grpc-api/dependencies.lock
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/DefaultV3TaskInfoFactory.java
- titus-supplementary-component/tasks-publisher/src/main/java/com/netflix/titus/supplementary/taskspublisher/TaskDocument.java
Companion PR: https://github.com/Netflix/titus-api-definitions/pull/105
This PR sets IP allocation ID info in the ES task document and Agent proto, if available.
> Pass task IP allocation to agent and es publisher

- titus-supplementary-component/task-relocation/src/test/java/com/netflix/titus/supplementary/relocation/integration/TaskRelocationIntegrationTest.java
it looks like it occasionally throws `InvocationTargetException` when running with parallel gradle tasks on CircleCI.
This is a somewhat desperate attempt to solve flakiness in tests, e.g.: https://circleci.com/gh/Netflix/titus-control-plane/339. It seems the `InvocationTargetException` comes from deep layers of gRPC code, but unfortunately the `BlockingStubs` are destroying the exception stacktraces at https://github.com/grpc/grpc-java/blob/v1.10.1/stub/src/main/java/io/grpc/stub/ClientCalls.java#L221
If anything, this change will hopefully allow us to find the underlying issue more easily.
> blockingStub is maybe having concurrency issues

- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/common/reactor/server/AbstractMethodHandler.java
- titus-supplementary-component/task-relocation/src/test/java/com/netflix/titus/supplementary/relocation/integration/TaskRelocationIntegrationTest.java
Tests are still flaky after #623. E.g.: https://circleci.com/gh/Netflix/titus-control-plane/344
`InvocationTargetException` is coming from the gRPC-reactor stub we create using reflection, this PR surfaces the underlying exception that is triggering it.
> Attempt #2 on reducing TaskRelocation test flakiness

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/JobAttributes.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/prediction/EmptyJobRuntimePredictionClient.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/prediction/JobRuntimePrediction.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/prediction/JobRuntimePredictionClient.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/prediction/JobRuntimePredictions.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/JobRuntimePredictionSanitizer.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/JobRuntimePredictionSelector.java
- titus-server-runtime/src/test/java/com/netflix/titus/runtime/connector/prediction/JobRuntimePredictionsTest.java
- titus-server-runtime/src/test/java/com/netflix/titus/runtime/endpoint/admission/JobRuntimePredictionSanitizerTest.java
... during admission, from an external predictions service.
The default implementation of the predictions service is a no-op.
> Support automatically adding runtime predictions to Jobs

- titus-server-master/src/main/java/com/netflix/titus/master/model/ResourceDimensions.java
- titus-server-master/src/main/java/com/netflix/titus/master/service/management/internal/ResourceConsumptionServiceMetrics.java
- titus-server-master/src/main/java/com/netflix/titus/master/service/management/internal/SimpleCapacityGuaranteeStrategy.java
- titus-server-master/src/test/java/com/netflix/titus/master/model/ResourceDimensionsTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/service/management/internal/ResourceConsumptionLogTest.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/data/core/ResourceDimensionSample.java
Note that currently capacity groups **can not** specify gpus to be reserved, since the current implementation ignores machines with GPU available when computing minimum required capacity.
> track GPU utilization as a consumption metric

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/JobFunctions.java
- titus-common/src/main/java/com/netflix/titus/common/util/StringExt.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/OpportunisticCpuSchedulingTest.java
predictions are in seconds, but can be fractional and will be parsed with a resolution up to milliseconds.
> support factional job runtime predictions

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/TaskAttributes.java
- titus-server-master/src/main/java/com/netflix/titus/master/clusteroperations/ClusterOperationFunctions.java
- titus-server-master/src/main/java/com/netflix/titus/master/clusteroperations/ClusterRemovableAgentRemover.java
- titus-server-master/src/main/java/com/netflix/titus/master/clusteroperations/ClusterRemovableInstanceGroupAgentRemover.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/JobManagerUtil.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/common/action/task/BasicTaskActions.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/ContainerFailureBasedAgentQualityTracker.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/DefaultSchedulingService.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/SchedulingService.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/TaskPlacementRecorder.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/constraint/OpportunisticCpuConstraint.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/constraint/TaskCacheEventListener.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/resourcecache/AgentResourceCacheUpdater.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/resourcecache/TaskCache.java
- titus-server-master/src/test/java/com/netflix/titus/master/clusteroperations/ClusterAgentAutoScalerTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/clusteroperations/ClusterRemovableAgentRemoverTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/clusteroperations/ClusterRemovableInstanceGroupAgentRemoverTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/scenario/StubbedSchedulingService.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/scenario/StubbedVirtualMachineMasterService.java
- titus-supplementary-component/task-relocation/src/main/java/com/netflix/titus/supplementary/relocation/util/RelocationUtil.java
- titus-supplementary-component/tasks-publisher/src/main/java/com/netflix/titus/supplementary/taskspublisher/TaskDocument.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/model/job/JobComponentStub.java
* Use a single machine id throughout the control plane
* Update the `SchedulingService.removeTask` API to hide the internal implementation details
* Start using `TASK_ATTRIBUTES_AGENT_INSTANCE_ID` consistently and remove `TASK_ATTRIBUTES_AGENT_ID` so it is not accidentally used
> Use Single Machine ID

- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/JobReconciliationFrameworkFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/DefaultSchedulingService.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/SchedulingService.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/scenario/StubbedSchedulingService.java
Simplify the scheduling service APIs to not use hostname and determine hostname as an internal implementation detail.
> Simplify the scheduling service APIs

- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/model/v1/V1OpportunisticResource.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/model/v1/V1OpportunisticResourceSpec.java
Avoid issues with different timezones when parsing.
> Timestamps in opportunistic CRDs as msFromEpoch

- .circleci/config.yml
Embedded postgres does not like being run as root, default user for the previous docker image was root, using circleci's jdk8 image. Since the previous cache was in the root directory using a new index for this cache.
> Fix circleci builds

- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/common/V3QueueableTask.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/OpportunisticCpuSchedulingTest.java
When opportunistic scheduling fails, we reduce the number of allocated opportunistic CPUs for the next iteration.
When it reaches zero for the first time, stop opportunistic scheduling altogether (set opportunisticCpus to zero permanently), instead of resetting from the beginning with all requested CPUs being opportunistic.
This prevents tasks being queued for a long time when any other scheduling constraint failures not related to opportunistic scheduling were making tasks flip between opportunistic and non-opportunistic scheduling modes constantly.
> Limit attempts for opportunistic scheduling

- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeOpportunisticResourceProvider.java
It seems `@Activator` methods are being called twice (I will fix that in a different PR), which caused the `PolledMeter` gauge to be double counted. The default behavior of the Spectator client is to sum up multiple PolledMeters with the same metric Id.
> prevent PolledMeter#monitorValue called twice

- titus-server-federation/src/main/java/com/netflix/titus/federation/endpoint/grpc/AggregatingSchedulerServiceGrpc.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/endpoint/grpc/FederationGrpcModule.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/endpoint/grpc/TitusFederationGrpcServer.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/endpoint/rest/FederationSchedulerResource.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/endpoint/rest/JerseyModule.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/service/AggregatingSchedulerService.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/service/DefaultAggregatingSchedulerService.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/service/ServiceModule.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/JobFederationTest.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/embedded/EmbeddedTitusOperations.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/embedded/cell/EmbeddedCellTitusOperations.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/embedded/cell/gateway/EmbeddedTitusGateway.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/embedded/cell/master/EmbeddedTitusMaster.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/embedded/federation/EmbeddedFederationTitusOperations.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/embedded/federation/EmbeddedTitusFederation.java
for now limited to `findLastSchedulingResult` operation only.
> Add scheduler REST/GRPC endpoints to TitusFederation server

- titus-common/src/main/java/com/netflix/titus/common/util/guice/internal/ActivationProvisionListener.java
- titus-common/src/test/java/com/netflix/titus/common/util/guice/internal/ActivationProvisionListenerTest.java
Guice will call `onProvision()` multiple times even for a @Singleton some times (apparently when it is being injected multiple times).
Make sure each unique instance (based on `Object#equals()`) is only registered once to be activated.
> prevent @Activator methods called multiple times

- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/DefaultSchedulingService.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/TaskPlacementFailure.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/constraint/AgentManagementConstraint.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/constraint/OpportunisticCpuConstraint.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/OpportunisticCpuSchedulingTest.java
... when deciding to reduce opportunistic allocations. If all scheduling constraint failures are from non-schedulable agents (disabled, gpu, etc), keep opportunistic tasks queued as-is.
> opportunistic: filter out non-schedulable agents

- build.gradle
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/sanitizer/JobAssertions.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/vpc/SignedIpAddressAllocation.java
- titus-common/build.gradle
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/JobIpAllocationsTest.java
These fields are already base64 encoded going over the wire and and when written to disk.
> Remove requirement that IP byte arrays be base64 encoded

- titus-common/src/main/java/com/netflix/titus/common/util/ExecutorsExt.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/endpoint/grpc/TitusFederationGrpcServer.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/endpoint/v3/grpc/TitusGatewayGrpcServer.java
- titus-server-master/src/main/java/com/netflix/titus/master/endpoint/grpc/GrpcMasterEndpointConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/endpoint/grpc/TitusMasterGrpcServer.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/endpoint/v3/grpc/DefaultJobManagementServiceGrpc.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/common/grpc/AbstractTitusGrpcServer.java
- titus-supplementary-component/job-activity-history-springboot/src/main/java/com/netflix/titus/supplementary/jobactivity/JobActivityMain.java
- titus-supplementary-component/job-activity-history/src/main/java/com/netflix/titus/supplementary/jobactivity/endpoint/grpc/JobActivityGrpcServer.java
TitusMaster servers can be DoS'd with very few `ObserveJobs` calls. Currently, each `ObserveJobs` stream will consume a new thread in a TitusMaster server. Additionally, gRPC will by default use a different thread pool for each `Channel`. In a typical server configuration, the maximum number of threads is in the dozens of thousands.
These changes considerably improve (by 10x or more) our ability to handle server streaming calls:
* use a single thread pool for all gRPC tasks, instead of a separate thread pool per channel (default with gRPC)
* limit the number of threads used for server streaming (ObserveJobs) tasks, instead of using an unbounded thread pool and potentially spawning a new thread per request while stream snapshots are being generated (an expensive operation). This will cause …
> Limit threads used by ObserveJobs and add instrumentation

- titus-server-master/src/main/java/com/netflix/titus/master/appscale/service/DefaultAppScaleManager.java
- titus-server-master/src/test/java/com/netflix/titus/master/appscale/endpoint.v3/grpc/DefaultAutoScalingServiceGrpcTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/appscale/service/DefaultAppScaleManagerTest.java
application auto scaling controller uses a number of reconciliation mechanism between Titus job state and AWS auto scaling state. Each of these Rx streams are subject to failure that are not retried by default. By wrapping those streams in TitusRuntime.persistentStream(..), they get unlimited exponential backed off retries.
> Updated reconciliation streams for app auto scale controller 

- titus-server-master/src/main/java/com/netflix/titus/master/mesos/DefaultV3TaskInfoFactory.java
This allows for a single source to determine what compute environment a workload is running in - both EC2 and Newt will set this as well.
> Add NETFLIX_EXECUTOR env variable

- titus-client/src/main/java/com/netflix/titus/runtime/endpoint/JobQueryCriteria.java
- titus-client/src/main/java/com/netflix/titus/runtime/endpoint/v3/grpc/GrpcJobQueryModelConverters.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/service/v3/internal/GatewayJobServiceGateway.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/v3/grpc/query/V3TaskQueryCriteriaEvaluator.java
- titus-server-runtime/src/test/java/com/netflix/titus/runtime/endpoint/v3/grpc/query/V3TaskQueryCriteriaEvaluatorTest.java
to simplify querying for batch tasks with retry limits. As system error
retries are unbounded, the task list can be arbitrary long.
> Add `skipSystemFailures` task query filter

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/JobAttributes.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/DefaultV3TaskInfoFactory.java
- titus-server-master/src/test/java/com/netflix/titus/master/mesos/DefaultV3TaskInfoFactoryTest.java
New job attribute titusParameter.entryPoint.skipShellParsing is created to support a use case that can override the default but deprecated behavior in how control plane deals with the entry point (as list of strings) when 'command' is not provided.
> Job Attribute for skipping entry point concatenation 

- titus-ext/runner/Dockerfile.agent
Temporarily stop trying to update package info from repositories that are long gone.
The proper fix will come when we replace mesos with k8s in the docker-compose configuration.
> ci: temporary fix for the docker-compose test

- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/JobManagerConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/JobReconciliationFrameworkFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/common/SecurityGroupUtils.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/common/V3QueueableTask.java
... by not considering the order of security groups in the same ENI. It is only required they are the same set of SGs.
#744 changed the way security groups are considered to be equal, so the consistency check needed to change as well.
cc @corindwyer for visibility
> revert #746, fix ENI consistency check

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/sanitizer/SchedulingConstraintValidator.java
- titus-server-master/src/main/java/com/netflix/titus/master/clusteroperations/ClusterAgentAutoScaler.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/SchedulerUtils.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/constraint/AgentManagementConstraint.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/constraint/AvailabilityZoneConstraint.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/constraint/MachineGroupConstraint.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/constraint/MachineIdConstraint.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/constraint/TolerationConstraint.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/constraint/V3ConstraintEvaluatorTransformer.java
- titus-server-master/src/test/java/com/netflix/titus/master/scheduler/constraint/MachineGroupConstraintTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/scheduler/constraint/TolerationConstraintTest.java
Add new scheduling constraints:
* machineGroup - specify a specific group of machines to land on (instance group name)
* toleration - specify a toleration to land on a machine with the matching taint name
> New scheduling constraints

- titus-server-federation/src/main/java/com/netflix/titus/federation/endpoint/grpc/TitusFederationGrpcServer.java
- titus-server-master/src/main/java/com/netflix/titus/master/endpoint/grpc/TitusMasterGrpcServer.java
This will allow the admission controller interceptor to rely on (context) data set by other interceptors in the chain.
> grpc: run the admission controller interceptor last in the chain

- titus-ext/cassandra/src/main/java/com/netflix/titus/ext/cassandra/store/CassandraLoadBalancerStore.java
... to reduce the amount of memory and queue pressure on the C* driver during leader activation (when all LB associations are loaded).
> loadbalancer: allow C* ResultSet pagination during activation

- docker-compose.yml
- titus-ext/runner/Dockerfile.master
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/DefaultSchedulingService.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/SchedulerUtils.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/TaskPlacementFailureClassifier.java
Currently, we only publish a gauge with the total number of tasks that failed placement in the last scheduling iteration.
This adds a new (counter) metric with more insights into why placements failed and for what application/capacityGroup. It will also count *all* failures from all scheduling iterations.
Failures are grouped by `(applicationName, capacityGroup)` to limit the cardinality of the new metric.
> publish more detailed metrics on failed placements

- titus-ext/cassandra/src/main/java/com/netflix/titus/ext/cassandra/store/CassAppScalePolicyStore.java
- titus-ext/cassandra/src/main/java/com/netflix/titus/ext/cassandra/store/CassStoreHelper.java
- titus-ext/cassandra/src/main/java/com/netflix/titus/ext/cassandra/store/CassandraLoadBalancerStore.java
- titus-ext/cassandra/src/test/java/com/netflix/titus/ext/cassandra/store/CassStoreHelperTest.java
This prevents async (on demand) fetching of `ResultSet` pages blocking C* driver threads.
The Datastax driver has a deadlock detector that complains (throws an exception) when pagination of resultsets would cause a deadlock, particularly when results are processed in C* driver threads and blocking the C* driver event loop.
> process C* resultsets outside of C* driver threads

- titus-common/src/main/java/com/netflix/titus/common/util/grpc/reactor/GrpcToReactorServerFactory.java
- titus-common/src/main/java/com/netflix/titus/common/util/grpc/reactor/server/DefaultGrpcToReactorServerFactory.java
- titus-common/src/main/java/com/netflix/titus/common/util/grpc/reactor/server/GrpcToReactorServerBuilder.java
- titus-common/src/main/java/com/netflix/titus/common/util/grpc/reactor/server/MethodHandlersBuilder.java
- titus-common/src/test/java/com/netflix/titus/common/util/grpc/reactor/server/GrpcToReactorServerBuilderTest.java
Spring security annotations result in cglib proxied classes. These classes do no retain enough generic type information for the grpc to reactor method handler to work with, so we pass additional class details in these cases.
> Add grpc to reactor server support for cglib proxies

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/TaskAttributes.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/TaskStatus.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/JobAndTaskMetrics.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/JobManagerUtil.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/KubeNotificationProcessor.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/common/action/task/BasicTaskActions.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeApiServerIntegrator.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeUtil.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/model/PodAddedEvent.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/model/PodDeletedEvent.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/model/PodEvent.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/model/PodUpdatedEvent.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/KubeSchedulerTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/scenario/ScenarioTemplates.java
by adding `podCreated` reason code, to denote condition when Kube pod
was created for a task.
> Overload TaskState.Accepted in Kube integration

- titus-common/src/main/java/com/netflix/titus/common/util/rx/SchedulerExt.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobactivity/service/JobActivityPublisher.java
Non-daemon threads from some components with event loops are currently causing the JVM to hang when integration tests fail.
> force daemon threads for various event loops

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/JobFunctions.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/ext/BatchJobExt.java
- titus-common/src/main/java/com/netflix/titus/common/util/FunctionExt.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/common/DifferenceResolverUtils.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/DefaultSchedulingService.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/OpportunisticCpuSchedulingTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/JobAttributesTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/JobSubmitAndControlNegativeTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/scenario/InstanceGroupScenarioBuilder.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/scenario/InstanceGroupsScenarioBuilder.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/scenario/TaskScenarioBuilder.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/JobRuntimePredictionConfiguration.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/JobRuntimePredictionSanitizer.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/jobmanager/gateway/SanitizingJobServiceGateway.java
- titus-server-runtime/src/test/java/com/netflix/titus/runtime/endpoint/admission/JobRuntimePredictionSanitizerTest.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/embedded/cell/EmbeddedTitusCells.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/embedded/cell/gateway/EmbeddedTitusGateway.java
* ignore prediction attributes passed in when creating jobs (these are to be generated)
* cap runtime predictions to the runtime limit for batch jobs that have a limit
* use the job runtime limit as a fallback when no predictions are selected for a job
* lower the minimum job runtime limit to 5s (from 60s) to allow short running batch jobs to specify a runtime limit
> use job runtime limits as the runtime prediction when sensible

- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeApiServerIntegrator.java
A pod can either have a terminal phase of Succeeded or Failed when trying to tear down the container. This PR maps the killed reason code correctly when the container is in the Failed phase.
> Handle killTask failed pod phase

- titus-common-testkit/src/main/java/com/netflix/titus/testkit/junit/category/FunctionalTest.java
- titus-common-testkit/src/main/java/com/netflix/titus/testkit/junit/category/IntegrationNotParallelizableTest.java
- titus-common-testkit/src/main/java/com/netflix/titus/testkit/junit/category/IntegrationTest.java
- titus-common-testkit/src/main/java/com/netflix/titus/testkit/junit/category/SmokeTest.java
Switch JUnit categories to plain interfaces from annotations to allow extending and move Smoke and Functional test categories from CMB to Titus testkit common.
> Enable junit categories be extended

- build.gradle
new versions of IntelliJ only allow gradle overrides through a gradle.properties file. This will allow useMavenLocal to be overriden from the command line when a custom gradle.properties sets it to true.
> allow useMavenLocal to be disabled

- .circleci/config.yml
- gradle.properties
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/OpportunisticCpuSchedulingTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/scenario/InstanceGroupScenarioBuilder.java
The testkit will periodically revoke and recreate mesos offers. That caused a race where sometimes agents with opportunistic windows had their offers revoked and tasks were wrongly scheduled on agents that didn't have a pre-configured opportunistic availability.
> reduce flakiness on OpportunisticCpuSchedulingTest

- scripts/ci/travis/build-release
Anything that gets merged to `master` gets published as a snapshot. Version strings will look like `0.1.1-snapshot.20200303225245`. `0.1.1` comes from the last semver git tag on the branch.
> Start publishing snapshot builds from master

- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeApiServerIntegrator.java
* Always use the first ipv4 InternalIP address as the host ip.
> always use the first InternalIP address as the host ip

- titus-common/src/main/java/com/netflix/titus/common/util/archaius2/Archaius2Ext.java
- titus-common/src/main/java/com/netflix/titus/common/util/archaius2/Archaius2ObjectConfigurationResolver.java
- titus-common/src/main/java/com/netflix/titus/common/util/archaius2/PeriodicallyRefreshingObjectConfigurationResolver.java
- titus-common/src/main/java/com/netflix/titus/common/util/archaius2/SpringConfig.java
- titus-common/src/main/java/com/netflix/titus/common/util/archaius2/SpringProxyInvocationHandler.java
- titus-common/src/test/java/com/netflix/titus/common/util/archaius2/PeriodicallyRefreshingObjectConfigurationResolverTest.java
- titus-common/src/test/java/com/netflix/titus/common/util/archaius2/SpringConfigTest.java
- titus-common/src/test/java/com/netflix/titus/common/util/archaius2/SpringProxyInvocationHandlerTest.java
It fixies two oversights:
1. it is ok to return null for non-primitive types
2. List and Set getters return empty collections if property not set
> An update to the original Archaius2/Spring dynamic proxy implementation

- titus-common/src/main/java/com/netflix/titus/common/util/feature/FeatureGuards.java
- titus-common/src/test/java/com/netflix/titus/common/util/feature/FeatureGuardsTest.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/JobManagerUtil.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/batch/BatchDifferenceResolver.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/service/ServiceDifferenceResolver.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/scenario/JobsScenarioBuilder.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/FeatureFlagModule.java
With this PR, we can route using an application name, capacity group, tier or job type.
> More routing options for Fenzo/Kube scheduler

- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/batch/BatchDifferenceResolver.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/service/ServiceDifferenceResolver.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/KubeSchedulerMasterBootstrapTest.java
We overloaded the Accepted state, and extra check is needed when checking if
task should be scheduled.
> KubeScheduler task in Accepted state without pod not launched after failover

- .circleci/config.yml
- titus-ext/cassandra/src/test/java/com/netflix/titus/ext/cassandra/store/CassStoreHelperTest.java
Execution of all tests (on a single box) down to 11min on Circle CI, and hopefully less flaky.
> Increase the JVM heap on circleci for tests

- titus-common-grpc-api/build.gradle
- titus-grpc-api/build.gradle
protobuf tasks are now created lazily which broke the previous override rule setup
> Change task dependency rules to avoid issues caused by the recent gradle upgrade

- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/KubeNotificationProcessor.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/MesosConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeApiServerIntegrator.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeConstants.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeUtil.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DefaultPodAffinityFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DefaultTaskToPodConverter.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/taint/Tolerations.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/KubeNotificationProcessorTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/mesos/kubeapiserver/KubeUtilTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/mesos/kubeapiserver/direct/taint/DefaultTaintTolerationFactoryTest.java
1. Add job runtime predictions as annotations on Pods (when present).
2. For pods handled by Fenzo, propagate opportunistic allocations to agents via Pod annotations (in addition to encoded into `ContainerInfo`).
3. for pods handled by kube-scheduler (which will take care of filling pod annotations), update tasks (context) with opportunistic scheduling allocations so the Titus API reflects opportunistic allocations on Pods.
cc @gabrielhartmann this will start adding opportunistic CPU allocations as a Pod annotation: `pod.metadata.annotations['opportunistic.scheduler.titus.netflix.com/cpu']`
> handle Pod opportunistic scheduling annotations

- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/JobManagerUtil.java
Always add agent.hostIp task attribute to all tasks.
> always add agent.hostIp task attribute to all tasks

- titus-server-federation/src/main/java/com/netflix/titus/federation/service/AggregatingJobServiceGateway.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/service/CellInfoUtil.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/service/router/ApplicationCellRouter.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/service/router/CellRouter.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/service/router/ChainCellRouter.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/service/router/FallbackCellRouter.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/service/router/RoutingRuleSelector.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/service/router/SpecialInstanceTypeRouter.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/startup/TitusFederationComponent.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/startup/TitusFederationConfiguration.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/startup/TitusFederationModule.java
- titus-server-federation/src/test/java/com/netflix/titus/federation/service/AggregatingJobServiceGatewayTest.java
- titus-server-federation/src/test/java/com/netflix/titus/federation/service/AggregatingJobServiceGatewayWithSingleCellTest.java
- titus-server-federation/src/test/java/com/netflix/titus/federation/service/router/ApplicationCellRouterTest.java
- titus-server-federation/src/test/java/com/netflix/titus/federation/service/router/ChainCellRouterTest.java
- titus-server-federation/src/test/java/com/netflix/titus/federation/service/router/RoutingRuleSelectorTest.java
- titus-server-federation/src/test/java/com/netflix/titus/federation/service/router/SpecialInstanceTypeRouterTest.java
The primary goal for this PR is the ability to centralize special instances (GPU) in one cell, and route all jobs that need the special resources to that cell, irrespective of the application level routing rules.
> Instance type federation routing

- titus-ext/cassandra/src/main/java/com/netflix/titus/ext/cassandra/store/CassandraJobStore.java
- titus-ext/cassandra/src/test/java/com/netflix/titus/ext/cassandra/store/CassandraJobStoreTest.java
It is possible that finished jobs/tasks are not moved after they are finished to
the archive tables. This may happen during failover which happens
immediately after a job completes, but is not archived yet. To read such
abandoned items (which are ignored when loading active data into memory), we
have to make a fallback query in case the primary archive table does not contain
an entry.
> Read archived data from active job/task tables if not found in the archive tables

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/LogStorageInfos.java
- titus-api/src/test/java/com/netflix/titus/api/jobmanager/model/job/LogStorageInfosTest.java
This PR fixes an issue, where a custom S3 bucket validation logic would not run
when only a bucket, but not path is set.
> Custom bucket path is an optional parameter

- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeApiServerIntegrator.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeUtil.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DirectKubeConfiguration.java
This update is limited to `KubeApiServerIntegrator`. We should refactor KubeScheduler code path after verifying that the async API is stable enough. The sync/async mode is controlled via persisted property.
> Use KubeClient async API to launch pods

- titus-api/src/main/java/com/netflix/titus/api/FeatureRolloutPlans.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/JobAttributes.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/service/v3/internal/ExtendedJobSanitizer.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/service/v3/internal/JobFeatureComplianceChecks.java
- titus-server-gateway/src/test/java/com/netflix/titus/gateway/service/v3/internal/ExtendedJobSanitizerTest.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/jobmanager/JobManagerConfiguration.java
When default values for accountId and subnets container attributes are present in the JobManagerConfiguration but not defined in the JobDescriptor (in container attributes), a violation is recorded. Consequently, the job descriptor is sanitized with the default values from the configuration properties.
Currently we are limiting the compliance check only when default values for these two attributes are present as configuration properties since not all deployment stacks may be ready for us to enforce this strict requirement. Note that we are not providing any extra safety guards yet to make sure the accountId and subnet list are compatible. It is possible that an invalid combination is used which will result in failure to run the task. This is the current behavior and  unchanged.
> Adding compliance check for container accountId and subnets

- titus-server-master/src/main/java/com/netflix/titus/master/mesos/TaskAssignments.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/VirtualMachineMasterService.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/VirtualMachineMasterServiceMesosImpl.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeApiServerIntegrator.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/DefaultSchedulingService.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/TaskPlacementRecorder.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/scenario/StubbedVirtualMachineMasterService.java
Relevant **only when the kubernetes integration is enabled**, and **Fenzo is being used for scheduling** (not kube-scheduler).
Allow all pods to be created concurrently, instead of serializing calls per Node. In order to enable that, `VirtualMachineMasterService's` interface was modified to receive all assignments for all Nodes in a single call.
> Create all Pods concurrently in the fenzo result callback

- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/SchedulerUtils.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/TaskPlacementFailure.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/TaskPlacementFailureClassifier.java
A failure for a task with the `ExclusiveHost` hard constraint is different from other tasks failing on a machine because it is already running another task with `ExclusiveHost`.
Both failure modes are classified with different priority to avoid prematurely triggering the ClusterAgentAutoscaler, when tasks that don't have the hard constraint are failing due to other transient scheduling failures.
Automated testing of this part of the codebase is unfortunately pretty difficult due to some Fenzo classes not being public and/or mockable, so I'm punting on junit tests.
> Fix scheduling classifier handling of ExclusiveHost hard constraint failures

- titus-common/src/main/java/com/netflix/titus/common/util/CollectionsExt.java
- titus-common/src/test/java/com/netflix/titus/common/util/CollectionsExtTest.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DefaultPodAffinityFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/DefaultSchedulingService.java
- titus-server-master/src/test/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DefaultPodAffinityFactoryTest.java
Input in jobDescriptors does not consider constraint names to be case sensitive. Likely the same for constraint values, but since some of them are identifiers, I opted to leave them untouched.
> kube-scheduler: case insensitive constraint names

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/JobConstraints.java
- titus-server-master/src/main/java/com/netflix/titus/master/clusteroperations/ClusterAgentAutoScaler.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/common/V3QueueableTask.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/constraint/V3ConstraintEvaluatorTransformer.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/OpportunisticCpuSchedulingTest.java
Semantically it does not have sense to combine them both. In practice tasks that are assigned opportunistic CPUs may never be scheduled if they have the ExclusiveHost hard constraint, since there will be never any donors of underutilized CPUs on the same machine.
Unschedulable tasks end up triggering periodic (constant) scale ups of host machines (`ClusterAgentAutoScaler`).
> exclusiveHost prevents opportunistic scheduling

- titus-common/src/main/java/com/netflix/titus/common/util/code/LoggingCodeInvariants.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/TaskPlacementFailureClassifier.java
These changes protect against NPEs when evaluating failures due to the `ExclusiveHost` constraint on a task already running on machines being evaluated. Not all scheduling failures will have a `ConstraintFailure` filled by Fenzo, and it can be `null`.
> Scheduling failures classifier can throw NPEs

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/TaskAttributes.java
- titus-client/src/main/java/com/netflix/titus/runtime/endpoint/v3/grpc/GrpcJobManagementModelConverters.java
- titus-client/src/test/java/com/netflix/titus/runtime/endpoint/v3/grpc/GrpcJobManagementModelConvertersTest.java
RemoteJobManagementClient is used by JobDataReplicator to build a local cache of running jobs and tasks. It depends on converting a grpc Task object into a core Task object. In that process, it seems to be losing information about task log location that is provided by the grpc Task. This change is needed to enable client cache layers using RemoteJobManagementClient to access task log information including ui-link, s3 bucket / key, s3 account Id etc.
> core task log locations populated from grpcTask

- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/common/V3QueueableTask.java
With jobs elligible for opportunistic scheduling, reduce the number of allocated opportunistic CPUs by half on each failed scheduling iteration, accelerating fallback to regular scheduling (opportunisticCpus = 0) when there is not enough surplus of opportunistic CPUs available.
This trades off optimal usage of opportunistic CPUs for lower launch latencies, as opportunsitic tasks will sit on the queue for a shorter time waiting for opportunistic CPUs to show up.
It also introduces some bias in the amounts of opportunistic CPUs that are allocated to each task (e.g.: prime numbers, and number not divisible by 2 may be less likely to be used), but the tradeoff in queue times and reliability (during a large spike of opportunistic tasks and short supply) is worth for now.
> opportunistic CPUs: faster fallback from low supply (surplus)

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/JobAttributes.java
- titus-server-gateway/src/test/java/com/netflix/titus/gateway/service/v3/internal/JobImageSanitizerTest.java
- titus-server-gateway/src/test/java/com/netflix/titus/gateway/service/v3/internal/ServiceMeshImageSanitizerTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/JobSanitizeTest.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/connector/registry/TitusContainerRegistryModule.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/JobImageSanitizer.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/JobImageSanitizerConfiguration.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/ServiceMeshImageSanitizer.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/ServiceMeshImageSanitizerConfiguration.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/ServiceMeshImageValidatorConfiguration.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/TitusAdmissionModule.java
We expect the gateway to replace tags with digest when launching a job with service mesh container specified.
This allows the service networking team to have customers launch a service job with a release build, while making sure that all tasks launched for the job use the same version of proxyd.
> Add a sanitizer for service mesh image attribute.

- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DefaultTaskToPodConverter.java
Per the docs:
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
the default policy is indeed not "Default", but is "ClusterFirst".
We don't configure cluster ips in titus, nor do we want
k8s to manipulate our DNS configuration so setting the policy to
the actual "Default" is what we want.
This is what we are doing anyway, this just removes an annoying warning:
```
kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to "Default" policy.
```
----
This is my first titus api contribution. I could use some guidance on verifying this works.
> Set the default DNS policy for k8s pods to 'Default'

- titus-common/src/main/java/com/netflix/titus/common/util/limiter/Limiters.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/JobManagerConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/V3JobManagerModule.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/batch/BatchDifferenceResolver.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/common/DifferenceResolverUtils.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/service/ServiceDifferenceResolver.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/scenario/JobsScenarioBuilder.java
... with dynamic configuration.
This will help prevent bad feedback loops when task state gets stale (e.g.: pod informers are not receiving updates), or when downstream systems are slow, adding some back-pressure to reconciliation.
> Rate limit reconciliation of tasks stuck in state

- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/JobManagerUtil.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/KubeNotificationProcessor.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeUtil.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/KubeNotificationProcessorTest.java
I kinda don't know what I'm doing here.
It looks like vk + executor add extra annotations after the fact ([here](https://github.com/Netflix-Skunkworks/titus-virtual-kubelet/blob/68ea9b6c6183b91eaa12d2d2505f18732d81aae6/provider/runtime_pod.go#L188)) to provide networking metadata back to the control plane.
This doesn't work on kubelet at all, so the control plane has no idea what ip address a kubelet pod has.
I don't know how easy it is going to be to add these annotations via kubelet, but this unblocks things a little bit by getting at least an ip address?
> RFC - Make the kubeapiserver connector understand pod ips from kubelet

- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/JobManagerConfiguration.java
Align the default stuckInLaunched timeout with other timeouts for job management. 1min (the previous setting) can be too low (determined empirically) when `SharedInformers` are getting stale. 5min (the new default) is more aligned with the default `stuckInStartInitiated` for service jobs, and gives a higher chance of problems with stale `SharedInformers` to be detected and remediated.
> Default stuckInLaunchedTimeout: 1min -> 5min

- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DefaultTaskToPodConverter.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DirectKubeConfiguration.java
- titus-server-master/src/test/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DefaultTaskToPodConverterTest.java
With this change a decision about which IAM role to use for S3 uploads is made by the control plane, and can be easily changed in the future without requiring agent side updates.
> Add S3 writer role support

- titus-common-runtime/src/main/java/com/netflix/titus/runtime/connector/kubernetes/KubeApiClients.java
which is not handled correctly by okhttp
> Disable HTTP2 in KubeClient

- titus-server-master/src/main/java/com/netflix/titus/master/service/management/internal/ResourceConsumptionEvaluator.java
- titus-server-master/src/test/java/com/netflix/titus/master/service/management/internal/ResourceConsumptionEvaluatorTest.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/model/job/JobComponentStub.java
Without this fix, opportunistic CPU usage per job was being aggregated twice: first at the job level, then multiplied by
the running task count.
> fix opportunistic usage metrics for batch jobs with size > 1

- titus-server-master/src/main/java/com/netflix/titus/master/MetricConstants.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/controller/BaseGcController.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/controller/ControllerConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/controller/GcControllerUtil.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/controller/KubeControllerConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/controller/KubeControllerModule.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/controller/NodeGcController.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/controller/PodDeletionGcController.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/controller/PodOnUnknownNodeGcController.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/controller/PodTerminalGcController.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/controller/PodUnknownGcController.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/DefaultKubeJobManagementReconciler.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeApiServerIntegrator.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeModule.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeUtil.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DirectKubeConfiguration.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/controller/NodeGcControllerTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/controller/PodDeletionGcControllerTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/controller/PodOnUnknownNodeGcControllerTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/controller/PodTerminalGcControllerTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/controller/PodUnknownGcControllerTest.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/kubernetes/KubeConstants.java
* Extract gc controller logic from KubeApiServerIntegrator into new GC controllers.
* Separate podAdd,podUpdate event handling from podDelete.
* In podDelete, add a missing KillInitiated status to indicate something outside of Titus terminate the container.
> Extract GC controller logic from KubeApiServerIntegrator

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/JobFunctions.java
- titus-api/src/test/java/com/netflix/titus/api/jobmanager/model/job/JobFunctionsTest.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DefaultTaskToPodConverter.java
- titus-server-master/src/test/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DefaultTaskToPodConverterTest.java
The only place we do not handle this properly is in `DefaultTaskToPodConverter` when processing `zonebalance` constraint.
> Constraint names are case insensitive

- titus-supplementary-component/task-relocation/src/main/java/com/netflix/titus/supplementary/relocation/RelocationConfiguration.java
- titus-supplementary-component/task-relocation/src/main/java/com/netflix/titus/supplementary/relocation/connector/AgentManagementNodeDataResolver.java
- titus-supplementary-component/task-relocation/src/main/java/com/netflix/titus/supplementary/relocation/connector/KubernetesNodeDataResolver.java
- titus-supplementary-component/task-relocation/src/main/java/com/netflix/titus/supplementary/relocation/connector/NodePredicates.java
- titus-supplementary-component/task-relocation/src/test/java/com/netflix/titus/supplementary/relocation/connector/NodePredicatesTest.java
As part of the relocation service, we have a way to enable task terminations based on a configurable set of node conditions. This change is adding a configurable set of node taints that could be enabled to effect immediate task terminations. It's adding the following options to configure this behavior
1.  badTaintsPattern - a regular expression identifying undesirable node taints as reported by kubernetes
2. nodeTaintTransitionTimeThresholdSeconds - it denotes (in seconds) the least amount of time the node should sustain a taint before being eligible for task terminations
> node taints condition check

- titus-ext/aws/src/main/java/com/netflix/titus/ext/aws/appscale/AppAutoScalingCallbackSpringResource.java
- titus-ext/aws/src/test/java/com/netflix/titus/ext/aws/appscale/AppAutoScalingCallbackSpringResourceTest.java
For a spring boot resource receiving set-target callback from auto scaling engine, response wasn't getting built properly. The bug fix here addressed it.
> fixing response from set target request for auto scaling callbacks

- titus-common-runtime/src/main/java/com/netflix/titus/runtime/connector/kubernetes/DisableCompressionInterceptor.java
- titus-common-runtime/src/main/java/com/netflix/titus/runtime/connector/kubernetes/KubeApiClients.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/MesosConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeModule.java
Disabling compression while LISTing a large number of resources for a given resource type is much faster compared to its counterpart.
> Disable compression in Kube ApiClient for faster LIST operations

- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeApiServerIntegrator.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/kubernetes/KubeConstants.java
- Set appropriate message when pods are known to have been removed as a result of unresponsive node by Node Lifecycle Manager
- Instead of deletionTimestamp from the pod delete events, we use wallTime for KillInitiated and Finished events
> Improve messaging and timestamps when containers are terminated due to unresponsive nodes

- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/controller/KubeControllerConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/controller/NodeGcController.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeApiServerIntegrator.java
* Switch to the new node annotation prefix.
* Verify the res node annotation is in a valid format before creating a lease.
* Add the ability to turn off account id verification in the node gc controller.
> Kubernetes Integration Improvements

- titus-client/src/main/java/com/netflix/titus/runtime/connector/common/replicator/RetryableReplicatorEventStream.java
- titus-common-ext/kube/src/main/java/com/netflix/titus/ext/kube/clustermembership/connector/KubeClusterMembershipConnector.java
- titus-common/src/main/java/com/netflix/titus/common/framework/scheduler/internal/LocalSchedulerTransactionLogger.java
- titus-common/src/main/java/com/netflix/titus/common/util/rx/ReactorRetriers.java
- titus-common/src/main/java/com/netflix/titus/common/util/rx/RetryHandlerBuilder.java
- titus-common/src/test/java/com/netflix/titus/common/util/rx/ReactorRetryHandlerBuilderTest.java
- titus-common/src/test/java/com/netflix/titus/common/util/rx/RetryHandlerBuilderTest.java
- titus-ext/eureka/src/main/java/com/netflix/titus/ext/eureka/containerhealth/EurekaContainerHealthService.java
- titus-supplementary-component/tasks-publisher/src/main/java/com/netflix/titus/supplementary/taskspublisher/TaskPublisherRetryUtil.java
The reactor-core project removed the  `retryWhen(Function<Flux<Throwable>,? extends Publisher<?>> whenFactory)` method in its 3.4.0 release. This PR changes those usages to the supported `retryWhen(Retry retrySpec)` method, which allows projects depending on titus-control-plane libraries (e.g., CMB) AND using reactor-core > 3.4.X to work.
> Remove use of deprecated Reactor retryWhen

- titus-api/src/main/java/com/netflix/titus/api/agent/service/AgentManagementService.java
- titus-api/src/main/java/com/netflix/titus/api/connector/cloud/InstanceCloudConnector.java
- titus-api/src/main/java/com/netflix/titus/api/connector/cloud/noop/NoOpInstanceCloudConnector.java
- titus-ext/aws/src/main/java/com/netflix/titus/ext/aws/AwsInstanceCloudConnector.java
- titus-ext/aws/src/main/java/com/netflix/titus/ext/aws/Main.java
- titus-server-master/src/main/java/com/netflix/titus/master/agent/service/DefaultAgentManagementService.java
- titus-server-master/src/main/java/com/netflix/titus/master/agent/service/cache/DataConverters.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/controller/NodeGcController.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/VmOperationsInstanceCloudConnector.java
- titus-server-master/src/test/java/com/netflix/titus/master/agent/service/DefaultAgentManagementServiceTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/controller/NodeGcControllerTest.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/embedded/cloud/connector/local/SimulatedLocalInstanceCloudConnector.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/embedded/cloud/connector/remote/SimulatedRemoteInstanceCloudConnector.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/model/agent/StubbedAgentManagementService.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/stub/connector/cloud/TestableInstanceCloudConnector.java
It contains the following updates to the Kubernetes Node GC controller behavior
1. If node not found in AgentManagementService Cache, EC2 service call is made to fetch the instance status. 
2. If node status not found in the Cache or from the EC2 service call, then it's ignored for GC
> rechecking agent status if not found in cache

- titus-server-master/src/main/java/com/netflix/titus/master/config/MasterConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/ContainerInfoUtil.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/DefaultV3TaskInfoRequestFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DefaultTaskToPodConverter.java
- titus-server-master/src/test/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DefaultTaskToPodConverterTest.java
This feature, once enabled, will prevent setting env variables in ContainerInfo set as an annotation on the pod resources. 
Env vars are also being set in the pod spec which is now the primary source of this info. Removing the former will reduce redundancy, shrink the pod size and aid pod LIST latency when there are a number of pods in the system.
> Disable setting env variables in ContainerInfo gated by a fast property

- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/controller/PersistentVolumeUnassociatedGcController.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DefaultDirectKubeApiServerIntegrator.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DefaultDirectKubeApiServerIntegratorMetrics.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DefaultTaskToPodConverter.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/KubeModelConverters.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/controller/PersistentVolumeUnassociatedGcControllerTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DefaultTaskToPodConverterTest.java
This PR changes how EBS persistent volumes are being used. Persistent volumes directly specify the CSI driver rather than the legacy AWS block store and expecting Kube CSI migration to do the mapping. Also, Persistent volume claims are used rather than the specifying the persistent volume directly on the pod.
> TITUS-4588 Add support for EBS persistent volume claims

- titus-supplementary-component/tasks-publisher/src/main/java/com/netflix/titus/supplementary/taskspublisher/TaskDocument.java
- titus-supplementary-component/tasks-publisher/src/test/java/com/netflix/titus/supplementary/taskspublisher/TaskDocumentTest.java
We have seen cases where ES payload publishing fails if task environment map contains keys with invalid use of period (".") characters. This code changes looks for leading or trailing "." and any instances of multiple "."s
It removes the invalid keys from the map before publishing to elastic search endpoint
> ES task environment map sanitization

- titus-supplementary-component/tasks-publisher/src/main/java/com/netflix/titus/supplementary/taskspublisher/config/TasksPublisherConfiguration.java
It removes grpc-netty api usage that is deprecated from NettyChannelBuilder.
> removing deprecated grpc api usage

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/JobDescriptor.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/sanitizer/JobAssertions.java
- titus-server-gateway/src/test/java/com/netflix/titus/gateway/service/v3/internal/JobEbsVolumeValidatorTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/JobEbsVolumesTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/scenario/JobScenarioBuilder.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/JobEbsVolumeValidator.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/PassJobValidator.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/model/job/JobEbsVolumeGenerator.java
This PR adds:
1. Missing validation checks that job size <= # EBS volumes.
2. Missing validation check for duplicate volume IDs.
3. EBS API integration tests.
> Additional EBS integration tests

- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/DefaultV3JobOperations.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/JobManagerUtil.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/KubeNotificationProcessor.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/common/action/task/BasicTaskActions.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeApiServerIntegrator.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/KubeNotificationProcessorTest.java
The real reason I started on this PR was because I couldn't remember how to tell if something was scheduled via kubescheduler.
Then I thought how nice it would be if in the reason message it was more explicit about how thing are going. Like what is the "real" state of things, and what is going to happen next (if applicable).
After all, what does "accepted" really mean? 
I was unable to track down where `created`, `running`, and `<not_given>` (no reason message) came from.
Anyway, seemed like it would be a nice to have, and better messages can assure our users (me) that the thing is working (or not). I'm not super familiar with this codebase or java.
> RFC: Added more verbose and human-friendly reason messages for task updates

- titus-server-master/src/main/java/com/netflix/titus/master/mesos/DefaultV3TaskInfoRequestFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/MesosConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DefaultTaskToPodConverter.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DirectKubeConfiguration.java
* Add a default kill wait timeout per job type instead of a global default.
> add a default kill wait timeout per job type instead of a global default

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/JobFunctions.java
- titus-client/src/main/java/com/netflix/titus/runtime/connector/eviction/EvictionConfiguration.java
- titus-client/src/main/java/com/netflix/titus/runtime/connector/eviction/EvictionRejectionReasons.java
- titus-server-master/src/main/java/com/netflix/titus/master/eviction/service/EvictionServiceModule.java
- titus-server-master/src/main/java/com/netflix/titus/master/eviction/service/quota/TitusQuotasManager.java
- titus-server-master/src/main/java/com/netflix/titus/master/eviction/service/quota/system/SystemQuotaConsumptionResults.java
- titus-server-master/src/main/java/com/netflix/titus/master/eviction/service/quota/system/SystemQuotaController.java
- titus-server-master/src/test/java/com/netflix/titus/master/eviction/service/quota/TitusQuotasManagerTest.java
- titus-supplementary-component/task-relocation/src/main/java/com/netflix/titus/supplementary/relocation/descheduler/DefaultDeschedulerService.java
- titus-supplementary-component/task-relocation/src/main/java/com/netflix/titus/supplementary/relocation/descheduler/DeschedulerComponent.java
- titus-supplementary-component/task-relocation/src/main/java/com/netflix/titus/supplementary/relocation/descheduler/EvictionQuotaTracker.java
- titus-supplementary-component/task-relocation/src/main/java/com/netflix/titus/supplementary/relocation/descheduler/TaskMigrationDescheduler.java
- titus-supplementary-component/task-relocation/src/main/java/com/netflix/titus/supplementary/relocation/workflow/TaskRelocationWorkflowComponent.java
- titus-supplementary-component/task-relocation/src/test/java/com/netflix/titus/supplementary/relocation/descheduler/DefaultDeschedulerServiceTest.java
- titus-supplementary-component/task-relocation/src/test/java/com/netflix/titus/supplementary/relocation/descheduler/TaskMigrationDeschedulerTest.java
Titus-relocation service processes task relocations / migrations based on 
1. System disruption quota (rate limit)
2. System disruption window (configurable)
3. Job disruption budget
There are use-cases where an application would want to override the default behavior of when their containers can get migrated with respect to System disruption window. For applications who would want to be exempt from subjecting to System Disruption window could now be configured with "titus.eviction.appsExemptFromSystemDisruptionWindow" property.
The apps configured with this property are still subject to system level rate limit (quota) as long as the system disruption window is open. But when it's closed, these apps will ONLY be subject to job level eviction quota configured through disruption budget from …
> System disruption window override support

- titus-common-runtime/src/main/java/com/netflix/titus/runtime/connector/kubernetes/DefaultKubeApiFacade.java
- titus-common-runtime/src/main/java/com/netflix/titus/runtime/connector/kubernetes/KubeApiFacade.java
- titus-common-runtime/src/main/java/com/netflix/titus/runtime/connector/kubernetes/NoOpKubeApiFacade.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/controller/KubeControllerModule.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/controller/PersistentVolumeClaimGcController.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/controller/PersistentVolumeReclaimController.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/controller/PersistentVolumeUnassociatedGcController.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeObjectFormatter.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DefaultDirectKubeApiServerIntegrator.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DefaultTaskToPodConverter.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/KubeModelConverters.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/controller/PersistentVolumeClaimGcControllerTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/controller/PersistentVolumeReclaimControllerTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DefaultTaskToPodConverterTest.java
This PR fixes an issue with how PVCs were used that allowed a PV to be used by more than one pod at a time. With this change:
1. Each PVC is specific to the PV/pod pair and is not shared across tasks/pods. This prevent concurrent use of the PV.
2. PVCs are GC'd when the task/pod they are bound is terminal.
3. PVs are reclaimed (made available for reuse) when their PVCs are deleted.
Though less relevant if we choose to go with a less "Kubernetes-native" EBS approach, this is still useful because it fixes that Kubernetes-native feature that already exists.
> Fix PVC usage to prevent concurrent PV assignment

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/JobFunctions.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/JobManagerUtil.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/batch/BatchDifferenceResolver.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/service/ServiceDifferenceResolver.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/FeatureFlagModule.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/KubeSchedulerFeatureConfiguration.java
Assign jobs belonging to KubeScheduler capacity groups to KubeScheduler always.
Add machineType KubeScheduler routing rule
> Assign jobs belonging to KubeScheduler capacity groups to KubeScheduler always

- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/KubePodUtil.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/PodFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/v0/V0SpecPodFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeApiServerIntegrator.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DefaultDirectKubeApiServerIntegrator.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DirectKubeConfiguration.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/pod/v0/V0SpecPodFactoryTest.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/kubernetes/KubeConstants.java
Adds the following pod annotations to a pod for EBS configuration:
```
"ebs.volume.netflix.com/fsType": "xfs",
"ebs.volume.netflix.com/mountPath": "/ebs_mnt",
"ebs.volume.netflix.com/mountPerm": "RW",
"ebs.volume.netflix.com/volumeId": "vol-09a13c88ebc5c3597",
```
And disable creation of EBS PV and PVCs.
> Add pod annotations for EBS volumes and disable PV/PVC creation

- titus-supplementary-component/tasks-publisher/src/main/java/com/netflix/titus/supplementary/taskspublisher/TaskDocument.java
- titus-supplementary-component/tasks-publisher/src/test/java/com/netflix/titus/supplementary/taskspublisher/TaskDocumentTest.java
This change applies the same sanitization criterion for container attributes, job attributes as well as the environment variables in order to make it safe for ES payload
> attribute map sanitization uniformly to container, job and env

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- scripts/ci/circleci/publish-release
Hi folks,
As you might be aware, JFrog is sunsetting Bintray and JCenter: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
This upgrades to Nebula NetflixOSS which will publish to Nebula's OSS repos and Maven Central.
Repositories based on status:
* https://netflixoss.jfrog.io/artifactory/maven-oss-snapshots
* https://netflixoss.jfrog.io/artifactory/maven-oss-candidates
* https://netflixoss.jfrog.io/artifactory/maven-oss-releases
I went ahead and added the environment variables in https://app.circleci.com/settings/project/github/Netflix/titus-control-plane/environment-variables 
Please verify the change when trying to publish. Since we don't support CircleCI, we haven't try it out with other projects
We are also starting to recommend folks to use Github …
> Upgrade to modern Gradle/Nebula to replace Bintray publication

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/JobAttributes.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/JobFunctions.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/KubePodUtil.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/pod/KubePodUtilTest.java
This PR adds functionality in support of TITUS-4938. The feature uses Metatron auth context information for more secure/granular authz. This PR adds common attribute fields and removes them from created pods to avoid wasting space (the attributes are similarly not in ContainerInfo).
> Job attribute for security auth context

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/JobFunctions.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/vpc/IpAddressAllocationUtils.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/DefaultPodAffinityFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/resourcecache/TaskCache.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/JobEbsVolumesTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/JobIpAllocationsTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DefaultPodAffinityFactoryTest.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/model/job/JobEbsVolumeGenerator.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/model/job/JobIpAllocationGenerator.java
Apply AZ node selector to pods with Static IPs for use with Kube Scheduler. Previously Static IP to AZ constraint mapping was handled by Fenzo.
> Apply AZ constraint to pods with Static IPs

- titus-common/src/main/java/com/netflix/titus/common/framework/reconciler/internal/DefaultReconciliationFramework.java
- titus-common/src/main/java/com/netflix/titus/common/framework/reconciler/internal/EventDistributor.java
- titus-common/src/test/java/com/netflix/titus/common/framework/reconciler/internal/DefaultReconciliationFrameworkTest.java
- titus-common/src/test/java/com/netflix/titus/common/framework/reconciler/internal/EngineStub.java
- titus-common/src/test/java/com/netflix/titus/common/framework/reconciler/internal/EventDistributorTest.java
- titus-common/src/test/java/com/netflix/titus/common/framework/reconciler/internal/SimpleReconcilerEvent.java
This change eliminates the `ReconciliationEngine`s event streams merge operator, and instead processes events in a new dedicated thread which handles all downstream `ReconciliationEngine` event streams individually.
> Job service event stream refactoring

- titus-common-api/src/main/java/com/netflix/titus/api/model/IdAndTimestampKey.java
- titus-common-api/src/main/java/com/netflix/titus/api/model/PaginableEntityKey.java
- titus-common-api/src/main/java/com/netflix/titus/api/model/PaginationUtil.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/service/AggregatingJobServiceGateway.java
- titus-server-federation/src/test/java/com/netflix/titus/federation/service/CellWithFixedTasksService.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/service/v3/internal/GatewayJobServiceGateway.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/service/v3/internal/NeedsMigrationQueryHandler.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/endpoint/v3/grpc/DefaultJobManagementServiceGrpc.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/DefaultV3JobOperations.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/jobmanager/JobComparators.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/jobmanager/JobManagerCursors.java
- titus-server-runtime/src/test/java/com/netflix/titus/runtime/jobmanager/JobComparatorsTest.java
Java stream API and collection sorting is expensive. These changes gave 30% performance gain with 30K running tasks.
> GRPC findJobs/findTasks optimizations

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/JobAttributes.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/service/AggregatingJobServiceGateway.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/startup/TitusFederationConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/DefaultV3JobOperations.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/JobSchedulingCommonTest.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/model/job/JobDescriptorGenerator.java
This work enables the concept of FederationJobs which could span across deployment cells/stacks. As a first step, we need to create the JobIds externally and then pass it the deployment stacks so the job records can be created in external storage specific to the stack.
> Adding capability to mint new jobIds in federation

- titus-api/src/main/java/com/netflix/titus/api/federation/model/RemoteFederation.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/service/AggregatingJobServiceGateway.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/service/DefaultRemoteFederationConnector.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/service/DefaultRemoteFederationInfoResolver.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/service/FallbackJobServiceGateway.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/service/RemoteFederationConnector.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/service/RemoteFederationInfoResolver.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/startup/GrpcConfiguration.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/startup/TitusFederationConfiguration.java
- titus-server-federation/src/main/java/com/netflix/titus/federation/startup/TitusFederationModule.java
- titus-server-federation/src/test/java/com/netflix/titus/federation/service/AggregatingJobServiceGatewayTest.java
- titus-server-federation/src/test/java/com/netflix/titus/federation/service/AggregatingJobServiceGatewayWithSingleCellTest.java
- titus-server-federation/src/test/java/com/netflix/titus/federation/service/RemoteFederationJobServices.java
If enabled and configured, create job requests to the
AggregatingJobServiceGateway can be redirected to a remote service.
If the remote service produces an error or times out, fallback to the
current cell based approach occurs.
> Add remote federation capability for job create

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/Capacity.java
- titus-api/src/main/java/com/netflix/titus/api/service/TitusServiceException.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/service/action/BasicServiceJobActions.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/JobScalingTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/scenario/JobScenarioBuilder.java
Matching the behavior of Autoscaling Groups on AWS: https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_UpdateAutoScalingGroup.html
More specifically:
> If you specify a new value for MinSize without specifying a value for DesiredCapacity, and the new MinSize is larger than the current size of the group, this sets the group's DesiredCapacity to the new MinSize value.
> 
> If you specify a new value for MaxSize without specifying a value for DesiredCapacity, and the new MaxSize is smaller than the current size of the group, this sets the group's DesiredCapacity to the new MaxSize value.
> Automatically adjust the desired size of service jobs when min and/or max are updated

- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/KubePodConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/v0/V0SpecPodFactory.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/pod/v0/V0SpecPodFactoryTest.java
Added a new scheduler configuration that controls how `pod.spec.schedulerName` for Critical tier pods is set when we are in failover. Its default value is the current scheduler name used by the reserved resource pool (`titus-kube-scheduler-reserved`). Once the kube-scheduler changes with the new profile that implements bin packing through SecurityGroup affinity are rolled out, we can set this configuration property to the new value (`titus-kube-scheduler-reserved-binpacking`) to place new critical tier pods accordingly.
> Support for a separate kube-scheduler profile for activating bin packing on reserved tier

- titus-server-runtime/src/main/java/com/netflix/titus/runtime/FeatureFlagModule.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/KubeSchedulerFeatureConfiguration.java
Removed previous flags and added Tier based override flags that are checked first for routing all jobs with Static IP and EBS volume to kube-scheduler
> Tier based flags to route StaticIP and EBS Volume jobs to Kube-Scheduler

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/JobAttributes.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/JobFunctions.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/DefaultV3JobOperations.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/JobSchedulingCommonTest.java
* Removing the `federatedJobId` attribute when a job is being created so we can prevent cloned federatedJobIds
* Introducing `originalFederatedJobId` (copy of federatedJobId) for tracking
> Removing federatedJobId from JobAttributes

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/ContainerResources.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/sanitizer/JobAssertions.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/vpc/IpAddressAllocation.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/vpc/IpAddressLocation.java
- titus-api/src/test/java/com/netflix/titus/api/jobmanager/model/job/sanitizer/JobAssertionsTest.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/service/v3/internal/ExtendedJobSanitizer.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/model/job/JobEbsVolumeGenerator.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/model/job/JobIpAllocationGenerator.java
Validates that jobs submitted with EBS Volumes and Static IPs have lists with matching resource AZs. Jobs with mismatched AZs are rejected as tasks from those indexes would not have been schedulable.
> EBS and IP AZ Validation

- titus-server-gateway/src/main/java/com/netflix/titus/gateway/service/v3/internal/ExtendedJobSanitizer.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/common/DifferenceResolverUtils.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/JobEbsVolumesTest.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/JobEbsVolumeValidator.java
Fixes an issue where EBS and IP provided index orders were not being honored. The usage of `.sorted()` was legacy and not functionally adding anything.
Also, the validation of EBS and IP matching AZs is moved to the `JobEbsVolumeValidator` so that it only runs on TJC where the EbsVolume objects are sanitized.
> Fix inconsistent EBS and IP index usage

- titus-api/src/main/java/com/netflix/titus/api/endpoint/v2/rest/representation/ApplicationSlaRepresentation.java
- titus-api/src/main/java/com/netflix/titus/api/model/ApplicationSLA.java
- titus-api/src/main/java/com/netflix/titus/api/model/SchedulerConstants.java
- titus-api/src/main/java/com/netflix/titus/api/store/v2/ApplicationSlaMixIn.java
- titus-ext/cassandra/src/test/java/com/netflix/titus/ext/cassandra/store/CassandraApplicationSlaStoreTest.java
- titus-server-master/src/main/java/com/netflix/titus/master/endpoint/v2/rest/Representation2ModelConvertions.java
- titus-server-master/src/main/java/com/netflix/titus/master/scheduler/DefaultTierSlaUpdater.java
- titus-server-master/src/main/java/com/netflix/titus/master/service/management/ManagementSubsystemInitializer.java
- titus-server-master/src/test/java/com/netflix/titus/master/endpoint/v2/rest/ApplicationSlaManagementResourceTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/scenario/StubbedApplicationSlaManagementService.java
- titus-server-master/src/test/java/com/netflix/titus/master/scheduler/DefaultTierSlaUpdaterTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/store/cache/ApplicationSlaStoreCacheTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/store/memory/InMemoryApplicationSlaStoreTest.java
- titus-server-runtime/src/test/java/com/netflix/titus/runtime/endpoint/common/rest/JsonMessageReaderWriterTest.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/data/core/ApplicationSlaSample.java
Add resourcePool to ApplicationSLA
- Set default value for resourcePool to reserved/elastic for non-GPU critical/flex tier capacity groups when scheduler is set to kubeScheduler
- In additional to creating a mechanism to separate capacity management at ApplicationSLA (Capacity Group)m, this change enables GPU capacity management where there may be multiple pools of GPU instances
> Add resourcePool to ApplicationSLA

- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/KubePodModule.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/resourcepool/KubeSchedulerPodResourcePoolResolver.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/resourcepool/PodResourcePoolResolverChain.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/pod/resourcepool/PodResourcePoolResolverChainTest.java
* Added a new resource pool resolver for pods when their associated capacity groups are enabled for kube scheduler and have a well-defined resource pool
* Provides a mechanism for controlling resource pool assignments from respective capacity groups (for example, GPU resource pools) which may have different underlying behaviors for capacity management
* Introduced a counter to track which pod resource pool resolver is active
> Add capacity group based pod resource pool resolver

- titus-api/src/main/java/com/netflix/titus/api/endpoint/v2/rest/representation/ApplicationSlaRepresentation.java
- titus-ext/cassandra/src/test/java/com/netflix/titus/ext/cassandra/store/CassandraApplicationSlaStoreTest.java
- titus-server-master/src/main/java/com/netflix/titus/master/endpoint/v2/rest/Representation2ModelConvertions.java
- titus-server-runtime/src/test/java/com/netflix/titus/runtime/endpoint/common/rest/JsonMessageReaderWriterTest.java
* Allow management of Capacity Groups with GPU resource dimension through application management v2 api
* Default value for the `instanceGPU` is 0 and it is optionally set to maintain backward compatibility of the API
* This API will be used by Titus UI and Capacity Controller to keep Capacity Groups' GPU asks in sync
> Support for creating CapacityGroups with GPU resource dimension

- titus-server-runtime/src/main/java/com/netflix/titus/runtime/FeatureFlagModule.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/KubeSchedulerFeatureConfiguration.java
We have been making use of higher resolution routing rules for enabling Kube-Scheduler migration. 
Now that we are nearing the completion, this global property provides a way to migrate any last jobs that may still be running using Fenzo and make sure the transition is complete.
> Top level override property to enable KS by tier

- titus-ext/job-validator/src/main/java/com/netflix/titus/ext/jobvalidator/ebs/JobEbsVolumeSanitizer.java
- titus-ext/job-validator/src/test/java/com/netflix/titus/ext/jobvalidator/ebs/JobEbsVolumeSanitizerTest.java
We want to preserve the order that volumes are provided by users.
> Remove sorting EBS volumes during sanitization

- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/DefaultV3JobOperations.java
When JVM hiccup alert was triggering, we noticed a thread consuming quite a lot of CPU in this function. Converting this away from Java streams use to relieve some pressure as per our previous optimizations in this space.
> Converting Java streams call to for-loop

- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/taint/DefaultTaintTolerationFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/taint/Tolerations.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/pod/taint/DefaultTaintTolerationFactoryTest.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/kubernetes/KubeConstants.java
unless jobs have the `activehost` hard constraint
> tolerate decommissioning nodes by default

- titus-supplementary-component/task-relocation/src/main/java/com/netflix/titus/supplementary/relocation/descheduler/DefaultDeschedulerService.java
- titus-supplementary-component/task-relocation/src/main/java/com/netflix/titus/supplementary/relocation/util/RelocationPredicates.java
- titus-supplementary-component/task-relocation/src/main/java/com/netflix/titus/supplementary/relocation/util/RelocationUtil.java
- titus-supplementary-component/task-relocation/src/test/java/com/netflix/titus/supplementary/relocation/descheduler/DefaultDeschedulerServiceTest.java
Titus relocation service  builds a list of planned relocation schedules for jobs with self managed relocation policies.  Due to a race condition it runs into a behavior where self managed plan contracts are not getting applied. It builds the list of planned relocations as the first step in de-scheduling. But then it also checks the node status for relocation at a later point in time in order to determine tasks that could be terminated from the eligible nodes.
This fix applies another check for self managed jobs to correctly apply the relocation delay as defined in the job specification.
> Self Managed relocation plan creation fixed

- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/KubePodModule.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/resourcepool/GpuPodResourcePoolResolver.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/pod/resourcepool/GpuPodResourcePoolResolverTest.java
When Jobs have an associated ApplicationSLA with a well-defined resourcePool, the order in which current resourcePool resolution works would always use the one on ApplicationSLA as the primary resourcePool to annotate the pods and set node selectors. This evaluation order does not work for special cases such as GPU and farzone.
In this PR, we are changing the order such that GPU and farzone jobs resolve to their pre-configured resourcePools (using fast properties) before any other resolution steps.
> Reorder resource pool resolvers to prioritize special cases first

- gradle.properties
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/JobDescriptor.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/JobModel.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/NetworkConfiguration.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/store/mixin/JobDescriptorMixin.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/store/mixin/NetworkConfigurationMixin.java
- titus-api/src/main/java/com/netflix/titus/api/json/ObjectMappers.java
- titus-client/src/main/java/com/netflix/titus/runtime/endpoint/v3/grpc/GrpcJobManagementModelConverters.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/KubePodUtil.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/pod/v0/V0SpecPodFactoryTest.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/kubernetes/KubeConstants.java
Pairs with
https://github.com/Netflix/titus-api-definitions/pull/130
This represents a new place to put job-level networking
configuration (instead of container resources).
Starting with a new enum for networking mode.
My intent here is only to pass this through into the pod
for the backend to consume, no other logic in the control-plane
should be needed here.
----
I am over my head here. The test I wrote passes, but I can't explain why, and the other validator tests fail with
```
<[Validation failed: 'field: '', description: ''null' in fields: networkConfiguration', type: 'HARD'',
Validation failed: 'field: 'container.securityProfile.securityGroups', description: 'Number of security groups must be between 1 and 6', type: 'HARD'']>
at …
```
> Added new NetworkConfiguration API

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/NetworkConfiguration.java
getNetworkModeName() is somehow leaking into the json serialization
of the NetworkConfiguration object, leading to:
```
"networkConfiguration":{"networkMode":0,"networkModeName":"UnknownNetworkMode"}
```
I don't want this, I only want the enum int in there.
Additionally, if we do make mistakes in the future with new properties,
I don't want the API to panic, so I added
@JsonIgnoreProperties(ignoreUnknown = true)
Which seems to be common practice in this codebase.
I'm not sure how to test this end-to-end.
> Ignore the string version of network_configuration

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/JobDescriptor.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/JobModel.java
- titus-client/src/main/java/com/netflix/titus/runtime/endpoint/v3/grpc/GrpcJobManagementModelConverters.java
I missed this piece, which actually tells the model builder
to use the NetworkConfiguration when provided by the actual
descriptor.
My tests were not enough to exercise this because I was building
the job object manually and not fully through CreateJob.
----
I couldn't quite find a unit test where you don't end up building the job object yourself.
But I tested this manually on my dev stack and confirmed it connects the dots.
> Make the job descriptor builder always include network configuration

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/TaskAttributes.java
- titus-client/src/main/java/com/netflix/titus/runtime/endpoint/v3/grpc/GrpcJobManagementModelConverters.java
- titus-client/src/test/java/com/netflix/titus/runtime/endpoint/v3/grpc/GrpcJobManagementModelConvertersTest.java
This change provides a way to include the live logs (stdout) location for a Titus task / container inside the Titus Task Core model attributes. This helps with remote data replicator building Task core model from gRpc response.
> live logs url included in task attributes

- titus-client/src/main/java/com/netflix/titus/runtime/connector/jobmanager/JobSnapshotFactories.java
- titus-client/src/main/java/com/netflix/titus/runtime/connector/jobmanager/PCollectionJobSnapshot.java
- titus-client/src/test/java/com/netflix/titus/runtime/connector/jobmanager/JobSnapshotPerf.java
- titus-client/src/test/java/com/netflix/titus/runtime/connector/jobmanager/JobSnapshotTest.java
- titus-client/src/test/java/com/netflix/titus/runtime/connector/jobmanager/JobSnapshotTestUtil.java
- titus-client/src/test/java/com/netflix/titus/runtime/connector/jobmanager/PCollectionJobSnapshotTest.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/endpoint/v3/grpc/DefaultJobManagementServiceGrpc.java
TJC GRPC snapshot could include task events without their corresponding,
leading job events. It was possible because jobs and tasks were requested
in two subsequent calls from Job API.
> Fix TJC snapshot; better inconsistency handling in PCollectionJobSnapshot

- titus-common-runtime/src/main/java/com/netflix/titus/runtime/connector/kubernetes/DefaultKubeApiFacade.java
- titus-common-runtime/src/main/java/com/netflix/titus/runtime/connector/kubernetes/KubeApiException.java
- titus-common-runtime/src/main/java/com/netflix/titus/runtime/connector/kubernetes/KubeApiFacade.java
- titus-common-runtime/src/main/java/com/netflix/titus/runtime/connector/kubernetes/KubeUtil.java
- titus-common-runtime/src/main/java/com/netflix/titus/runtime/connector/kubernetes/NoOpKubeApiFacade.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/controller/GcControllerUtil.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/controller/PersistentVolumeClaimGcController.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/controller/PersistentVolumeReclaimController.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/controller/PersistentVolumeUnassociatedGcController.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeApiServerIntegrator.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeUtil.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DefaultDirectKubeApiServerIntegrator.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/controller/PersistentVolumeClaimGcControllerTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/controller/PersistentVolumeReclaimControllerTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/controller/PersistentVolumeUnassociatedGcControllerTest.java
Hide Kube Java lib invocations behind internal API. We need a proper interface between Kube and Titus so we can easily inject stubbed version of Kube Cluster in the integration tests.
> Hide Kube Java lib invocations behind internal API

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/TaskAttributes.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/JobManagerUtil.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/KubeNotificationProcessor.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/TitusExecutorDetails.java
- titus-server-master/src/main/java/com/netflix/titus/master/mesos/kubeapiserver/KubeUtil.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/KubeNotificationProcessorTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/scenario/StubbedVirtualMachineMasterService.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/embedded/cloud/agent/TaskExecutorHolder.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/embedded/cloud/connector/remote/SimulatedRemoteMesosSchedulerDriver.java
We are moving to a new world where IPv6 is the main thing,
and IPv4 is extra.
This change makes the ipv4/ipv6 task attribute setter "NetworkMode"-aware,
and only sets the IPv4 when it makes sense.
Only a small number of experimental tasks are using this mode,
so we need to use those as canaries to see what else will break
when we stop publishing a v4 address in this way.
----
This change will also be paired with a titus-executor change that add networkMode
to the details that come back for the control-plane to use.
> Only set the ipv4 container attribute if we have one

- titus-server-federation/src/main/java/com/netflix/titus/federation/service/AggregatingJobServiceGateway.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/JobSubmitAndControlBasicTest.java
This information is necessary to evaluate scheduling parity between
fedv1 and fedv2 approaches before the transition to fedv2
> Add routing cell metadata to jobs created via fedv1

- titus-api/src/main/java/com/netflix/titus/api/FeatureActivationConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/JobManagerUtil.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/affinity/DefaultPodAffinityFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/topology/DefaultTopologyFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/v0/V0SpecPodFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/v1/V1SpecPodFactory.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/pod/topology/DefaultTopologyFactoryTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/pod/v0/V0SpecPodFactoryTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/mesos/kubeapiserver/direct/DefaultPodAffinityFactoryTest.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/kubernetes/KubeConstants.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/model/job/JobGenerator.java
The new behavior can be disabled by the `titus.feature.relocationBinpackingEnabled` flag.
Binpacking is accomplished by:
* a new label added to tasks that should opt-into binpacking (currently only tasks from jobs with SelfManaged disruption policies)
* Pod affinity and anti-affinity rules against the label above
> Binpack self-managed tasks to optimize their relocation

- build.gradle
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/BasicContainer.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/JobDescriptor.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/store/mixin/BasicContainerMixin.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/store/mixin/JobDescriptorMixin.java
- titus-api/src/main/java/com/netflix/titus/api/json/ObjectMappers.java
- titus-client/src/main/java/com/netflix/titus/runtime/endpoint/v3/grpc/GrpcJobManagementModelConverters.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/v0/V0SpecPodFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/v1/V1SpecPodFactory.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/pod/v0/V0SpecPodFactoryTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/pod/v1/V1SpecPodFactoryTest.java
This changed takes in the new proto for ExtraContainers and appends
those containers to the pod (v0 and v1 schemas).
This adds a new place for adding test to the V1 schema pod builder
as well.
These new extraContainers are constructed pretty much as-is from
proto to V1Container, minimal processing is done.
----
Because these are just "extra" containers, which will be empty for 99% of workloads (for now), the incremental increase in load on Cassandra will be minimal (just `extraContainers: []`) and the incremental load on k8s/etcd will be none.
This is just the really the most basic container you can get, there will need to be future room for things like volumes and healthchecks and all sorts of fancy stuff, but in the end those too will be just passed into the pod object.
> Implemented extraContainers

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/BasicContainer.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/JobDescriptor.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/NetworkConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/v0/V0SpecPodFactory.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/model/job/JobDescriptorGenerator.java
I don't think any of these small fixes actually will
fix my core issue of extraContainers being empty, even
after confirming it is in the JobDescriptor grpc object.
> Small fixes for extraContainers functionality

- titus-common-runtime/src/main/java/com/netflix/titus/runtime/connector/kubernetes/KubeApiException.java
For Titus developers, and heck for titus users, it is
a better experience for all when we get the right error message
we need when it is "low level". The types of errors one gets
when k8s throws a non-200 at us are hard to get at currently.
This change makes it so we get the response body with it.
Per https://github.com/kubernetes-client/java/issues/695#issuecomment-530139220
Before:
```
Failed to create pod: (IllegalStateException) Unable to launch a task 6325b498-3132-496e-969b-ae6308b43871 -CAUSED BY-> (KubeApiException) Bad Request -CAUSED BY-> (ApiException) Bad Request
```
After:
```
Failed to create pod: (IllegalStateException) Unable to launch a task 8cdf15d2-8b79-4c09-a8c7-9d7544a6bcbe -CAUSED BY-> (KubeApiException) Bad Request: httpStatus=400, …
```
> Expanded the error message on kubeapi failures

- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/JobAndTaskMetrics.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/scenario/JobsScenarioBuilder.java
Publishing a limit will allow for percentage (of limit) based alerts
> emit a metric with the limit for active jobs

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/JobDescriptor.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/PlatformSidecar.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/store/mixin/JobDescriptorMixin.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/store/mixin/PlatformSidecarMixin.java
- titus-api/src/main/java/com/netflix/titus/api/json/ObjectMappers.java
- titus-client/src/main/java/com/netflix/titus/runtime/endpoint/v3/grpc/GrpcJobManagementModelConverters.java
- titus-ext/cassandra/src/test/java/com/netflix/titus/ext/cassandra/store/CassandraJobStoreTest.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/KubePodUtil.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/v0/V0SpecPodFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/v1/V1SpecPodFactory.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/pod/v1/V1SpecPodFactoryTest.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/jobmanager/gateway/SanitizingJobServiceGateway.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/kubernetes/KubeConstants.java
- titus-testkit/src/main/java/com/netflix/titus/testkit/model/job/JobDescriptorGenerator.java
This new feature takes the new PlatformSidecar objects from the
Titus API proto definition and populates the appropriate
annotations on the pod. No additional processing is required by
the control-plane, because we want to stay pretty close to
the "the pod spec is the api" vision.
Two big things we need to iron out:
1. Annotation format. It would be nice to get some good conventions,
and hopefully not change them over time. Luckily in the webhook
we can parse multiple annotations and merge them together as we change.
2. This whole `Struct` stuff. The reasoning behind using a protobuf
[Struct](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Struct)
field was to preserve the structured data that would come in
from the API, and not treat it like …
> Take incoming platform Sidecars and make annotations for them

- build.gradle
- titus-client/src/main/java/com/netflix/titus/runtime/endpoint/v3/grpc/GrpcJobManagementModelConverters.java
Since I've split out all these new features out of the titus_job_api,
so that they can shared with other systems (cmb), I had to make this
one small breaking change to extract out the Image stuff -> BasicImage.
Everything else (proto stuff) is the same because they are all part of the same Java package, just in different files.
> Bump titus-api-definitions to include BasicImage changes

- titus-client/src/main/java/com/netflix/titus/runtime/connector/jobmanager/CachedReadOnlyJobOperations.java
- titus-supplementary-component/task-relocation/src/main/java/com/netflix/titus/supplementary/relocation/descheduler/DefaultDeschedulerService.java
- titus-supplementary-component/task-relocation/src/main/java/com/netflix/titus/supplementary/relocation/workflow/step/RelocationMetricsStep.java
Relocation service runs into the runtime type error while de-scheduling eligible tasks from marked or unhealthy agents. This change is similar in nature to the bug-fix done to Metrics step code in order avoid incorrect casting of Map to a List from PCollectionJobSnapsho
> relocation de-scheduler fix

- titus-client/src/main/java/com/netflix/titus/runtime/endpoint/JobQueryCriteria.java
- titus-client/src/main/java/com/netflix/titus/runtime/endpoint/v3/grpc/GrpcJobQueryModelConverters.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/query/JobCriteriaQueryTest.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/v3/grpc/query/V3AbstractQueryCriteriaEvaluator.java
This adds the most basic job query search based on platform
sidecars.
It only adds a single param `platformSidecar` so one can get all
the jobs/tasks that have use that platformSidecar.
I expect all queries around platform sidecars like this to be centered
around a specific sidecar, not multiple sidecars, so I didn't think we
needed additional complexity around N sidecars.
> Added basic platformSidecar job query search support

- titus-client/src/main/java/com/netflix/titus/runtime/endpoint/JobQueryCriteria.java
- titus-client/src/main/java/com/netflix/titus/runtime/endpoint/v3/grpc/GrpcJobQueryModelConverters.java
- titus-server-master/src/test/java/com/netflix/titus/master/integration/v3/job/query/JobCriteriaQueryTest.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/v3/grpc/query/V3AbstractQueryCriteriaEvaluator.java
This is part2 of allowing platform sidecar (PS) authors to be
able to find jobs of interest to them.
Specifically, this will allow them to find jobs that are using
a particular channel, so those jobs can be bounced or hunted
down when a particular channel needs to be deprecated.
*Or* when that channel is upgraded, jobs/tasks using that channel
can be targeted for relocation, to force them to get the latest
version.
----
I didn't feel the need to go "all out" and write lots of integration tests
to verify this new code's interaction with "platformSidecar=", I think it
can be safely assumed that, like any other query filter, this is an "And"
filter, and will be applied *together* with a sidecar name to narrow the scope.
While technically possible for one to just query based on a channel …
> Added support for filtering based on platformSidecar channel

- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/v1/V1SpecPodFactory.java
These missing breaks meant there was some weird leakage
and erroneous extra annotations from the *next* case!
> Fix attribute annotation mixup on v1 pod spec

- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/v1/V1SpecPodFactory.java
I want to make this name change before we have too many things
keying off of container names in the newer multi-container world.
Remember, we already have a unique identifier for the pod, the pod ID
is the task uuid, that is great.
The container name though, I think it would be better to have a consistent
string we can key off of: "main". This simplifies a lot of future code
that has to detect "which" container they are on, or making a volumeMount
that needs to reference "which" container to attach.
For all things that ever need to ask "what is the name of the main container"
or "am I running on the main container", they will not need to *also* look
up the taskid var and compare.
----
Keep in mind this will break nobody if merged today, and only *may* break
people as I roll out v1 pod …
> Make the name of the 'main' container be 'main' in V1 schema pods

- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/v1/V1SpecPodFactory.java
Previously, in v0 pod specs the Titus executor would
do a conversion at the last minute, extracting the
efsid from the protobuf.
In v1 pod specs, I think it makes more sense for the
nfs:server field to be "true" and actually be an NFS
server, which means implement this conversion in the
control plane.
----
This getTargetRegion looks pretty convenient, but I don't really
know how to be sure if it is correct in practice on our servers.
(this appears to be the first consumer?)
> Convert EFS IDs to NFS Hostnames for v1 pod specs

- .github/workflows/nebula.yml
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/v1/V1SpecPodFactory.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/pod/v1/V1SpecPodFactoryTest.java
Previously, we did not handle the case where we had
multiple volumes with a mix of RO/RW on the same source.
This change makes it so we always put the burden of RW/RO
on the volume *mount* (not the volume), and re-use the
volume itself (always RW, doesn't really matter too much).
> v1 pod schema: Handle multiple complex efs volumes

- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/KubePodConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/v0/V0SpecPodFactory.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/kubernetes/KubeConstants.java
Now that we have 100% rollout of this feature, we are
ready to remove the toggle.
This change must be deployed *after* the titus-executor
change to always use bytes
> Removed the useBytes toggle, always set bytes on pods

- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/JobManagerUtil.java
99% of the work needed to make ipv6-only containers has
either already been done, or is on the executor side.
This is the only place I found in the CP codebase that
assumes there is an IPv4 ready on every container.
> Enable IPv6 Only containers

- titus-client/src/main/java/com/netflix/titus/runtime/endpoint/v3/grpc/GrpcJobManagementModelConverters.java
- titus-server-gateway/build.gradle
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/endpoint/GatewayGrpcModule.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/endpoint/v3/grpc/TitusGatewayGrpcServer.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/kubernetes/F8KubeObjectFormatter.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/kubernetes/KubeApiClient.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/kubernetes/KubeApiConnector.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/kubernetes/PodAddedEvent.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/kubernetes/PodDeletedEvent.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/kubernetes/PodEvent.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/kubernetes/PodUpdatedEvent.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/service/v3/internal/GatewayJobServiceGateway.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/service/v3/internal/TaskRelocationDataInjector.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/startup/TitusGateway.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/startup/TitusGatewayConfiguration.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/startup/TitusGatewayModule.java
- titus-server-gateway/src/test/java/com/netflix/titus/gateway/service/v3/internal/TaskRelocationDataInjectorTest.java
We need to get container status from pods. The pods information is not available at the gateway layer until we add shared informer. This PR adds shared informer and code to get the container status. The shared informer will be behind a feature flag.
> Adding kube shared informer to gateway

- titus-server-federation/src/main/java/com/netflix/titus/federation/service/FallbackJobServiceGateway.java
Fallback is not applicable to streaming api calls like ObserveJob(s).  So we call the `RemoteJobServiceGateway` when enabled and the original `AggregatingJobServiceGateway` when disabled.  Failure is just a failure and we do not attempt to fallback.
> Call remote federation for ObserveJob(s) when enabled

- build.gradle
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/volume/SaaSVolumeSource.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/volume/SharedContainerVolumeSource.java
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/store/mixin/SaaSVolumeSourceMixin.java
- titus-api/src/main/java/com/netflix/titus/api/json/ObjectMappers.java
- titus-client/src/main/java/com/netflix/titus/runtime/endpoint/v3/grpc/GrpcJobManagementModelConverters.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/KubePodUtil.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/v0/V0SpecPodFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/v1/V1SpecPodFactory.java
This adds support for a new SaaS Volume type.
It only has the 1 string to worry about, the ID.
On the backend (TJC), pods are created using the Ceph
volume type, with the ID as the path.
> Added SaaSVolume support

- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/KubePodConstants.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/v1/V1SpecPodFactory.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/pod/v1/V1SpecPodFactoryTest.java
We need to preserve this Image Tag somehow into
the v1 pod so that we can retrieve it on the backend
and use it for Metatron to validate.
> Added container image tag to v1 pod schema pods

- titus-client/src/main/java/com/netflix/titus/runtime/connector/jobmanager/RemoteJobManagementClientWithKeepAlive.java
- titus-client/src/test/java/com/netflix/titus/runtime/connector/jobmanager/RemoteJobManagementClientWithKeepAliveTest.java
- titus-common/src/main/java/com/netflix/titus/common/util/FunctionExt.java
Ensure keepAlive publishers (interval subscriptions) don't leak when grpc connections (observeJobs) are terminated.
> gateway: properly dispose internal subscriptions

- titus-server-gateway/src/main/java/com/netflix/titus/gateway/service/v3/internal/GatewayJobServiceGateway.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/service/v3/internal/NeedsMigrationQueryHandler.java
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/service/v3/internal/TaskDataInjector.java
- titus-server-gateway/src/test/java/com/netflix/titus/gateway/service/v3/internal/TaskDataInjectorTest.java
Looks like we were overriding task status with the latest changes. Fixed that.
> Refactor class name to TaskDataInjector and fix task status builder

- titus-api/src/main/java/com/netflix/titus/api/appscale/model/AlarmConfiguration.java
- titus-api/src/main/java/com/netflix/titus/api/appscale/store/mixin/AlarmConfigurationMixIn.java
- titus-api/src/test/java/com/netflix/titus/api/appscale/model/PolicyConfigurationTest.java
- titus-ext/aws/src/main/java/com/netflix/titus/ext/aws/cloudwatch/CloudWatchClient.java
- titus-ext/aws/src/test/java/com/netflix/titus/ext/aws/cloudwatch/CloudWatchClientTest.java
- titus-server-master/src/main/java/com/netflix/titus/master/appscale/endpoint/v3/grpc/DefaultAutoScalingServiceGrpc.java
- titus-server-master/src/main/java/com/netflix/titus/master/appscale/endpoint/v3/grpc/InternalModelConverters.java
Step scaling policy configuration currently supports a default metric dimension - AutoScalingGroup
For other cloud-watch metrics that are not tagged with AutoScalingGroup, we didn't have a way to create a step scaling auto scaling policy.
This code change is aimed at supporting additional metric dimensions in creating cloud watch alarm configuration that is associated with a step scaling policy.
Note that - the Target tracking policy configuration already supports this feature.
> Step scaling custom dimensions

- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/client/DefaultDirectKubeApiServerIntegrator.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/client/DirectKubeConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/PodFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/RouterPodFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/v0/V0SpecPodFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/v1/V1SpecPodFactory.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/pod/RouterPodFactoryTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/pod/v0/V0SpecPodFactoryTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/pod/v1/V1SpecPodFactoryTest.java
We had this code in previously for kubelet + the
AWS EBS CSI Driver.
Now that we are no longer using that driver, we no longer
need the complexity of PV / PVCs at all (pretty sure),
and all we need is a plain volume + volumeMount.
Also with this change, EBS volumes will be enabled in all
regions, and we'll no longer need a feature toggle.
----
Can we remove `boolean useKubeScheduler` next? :)
> Remove unused EBS PV code

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/JobFunctions.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/KubePodUtil.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/v0/V0SpecPodFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/v1/V1SpecPodFactory.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/pod/v0/V0SpecPodFactoryTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/pod/v1/V1SpecPodFactoryTest.java
This change makes it so we always use the awsElasticBlockStore
volumeSource on a volume, instead of using PV/PVCs.
This does leave a lot of leftover unused code that I will clean up on
the next PR, only after verifying there are no unintended side-effects
from configuring pods this way.
On v0 pods, nothing should change, because we still just use the
annotations as the source of truth.
For v1 pods, tests should go green (they fail currently), because the
titus-executor expects awsElasticBlockStore to be filled in, but is
currently not.
> Use awsElasticBlockStore instead of PVS pods

- build.gradle
- titus-api/src/main/java/com/netflix/titus/api/jobmanager/model/job/NetworkConfiguration.java
This extends the model to include the new HighScale network mode so it
can be selected. No other business logic at this time (most will
actually be done on titus-executor).
----
I've tried to replace the `networkModeToName` with some sort of autogen'd thing, but I always end up with java naming conflicts because they are both called `NetworkConfiguration` (ie, I can't import the auto-gen java protobuf class at all).
It isn't a big deal, but if anyone has any suggestions, please let me know.
> Enabled the new HighScale network mode

- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/v1/V1SpecPodFactory.java
This was setting it to "true", but what we really want for the value of
the annotation is that actual sched policy itself.
> Fix schedBatch policy for v1 pods

- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/v0/V0SpecPodFactory.java
This is the same as v1 pods, but bringing this feature to v0 pods
because I don't really see us getting to v1 pods any time soon.
But, platform sidecar developers need this feature, because we need to
be able to reference the main container "by name", and it is way easier
when that is a constant.
> Make v0 pods use the "main" container as the container name

- build.gradle
- titus-server-gateway/src/main/java/com/netflix/titus/gateway/service/v3/internal/TaskDataInjector.java
- titus-server-gateway/src/test/java/com/netflix/titus/gateway/service/v3/internal/TaskDataInjectorTest.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/kubernetes/KubeConstants.java
Now that we have containerStatus plumbed all the way through, this is
the next pass which adds more data like image stuff and platform sidecar
stuff.
The reason this is difficult is because with platform sidecars, we need
to look at annotations to verify what the exact tag/digest/name that an
image comes from. The stock k8s v1 container status has no room for this
of course. And it doesn't have room for tag/digest, which we really
want.
This adds code for parsing and extracting annotations to be able to get
back the exact container image and (optionally) the platform sidecar
that added it.
I consider this code to be "best effort", as this is a new feature and
there are a number of ways that the data can simply not show up.
Once this data is in our API, I can make it visible to the Titus …
> Added image data and platform sidecar data to containerStatus

- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/KubePodConstants.java
I copy/pasted these strings from titus-executor, but from the golang
struct!
There was a different function (toMap) that converted the struct fields
to actual annotations that use subtly different case.
> Fixed legacy network pod annotation case

- titus-server-gateway/src/test/java/com/netflix/titus/gateway/service/v3/internal/JobImageSanitizerTest.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/JobImageSanitizer.java
With this change, we fail early on resolving image digest. For an unknown error, it'd fail job creation instead of letting the job scheduling progress without image digest only to fail during the container launch time.
> image sanitizer fix

- titus-common/src/main/java/com/netflix/titus/common/util/event/EventPropagationUtil.java
- titus-common/src/test/java/com/netflix/titus/common/util/event/EventPropagationUtilTest.java
This changes creates an upper bound for the event propagation state size so that a cloned Titus job with an existing event propagation attribute will not grow unbounded in size
> making event.propagation.stages bounded in size

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/TaskAttributes.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/JobManagerUtil.java
I incorrectly added code in https://github.com/Netflix/titus-control-plane/pull/1220/
that made the EIP of a task be the "primary" ip.
This broke LB registration.
I liked the idea of getting the EIP context data back out, but it should
be the primary ip. Instead this adds a new piece of context data so that
one can still see what the EIP was in the UI and other tools, but the
primary ip will remain the private ipv4 address.
> Use a special EIP task context attribute instead of the primary IP

- titus-common-server/src/main/java/com/netflix/titus/runtime/endpoint/metadata/spring/CallMetadataAuthentication.java
- titus-common-server/src/main/java/com/netflix/titus/runtime/endpoint/metadata/spring/SpringCallMetadataInterceptor.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/v3/rest/JobManagementSpringResource.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/v3/rest/LoadBalancerSpringResource.java
I was looking at our API docs and wondered what it might take to get our
swagger page into a position where it could replace our (outdated)
markdown docs.
I don't think it is too bad. In fact I think it is good that the params
and what they do are so closely tied to the docs like this.
I still can't hide `authorities[0].authority` and 6 other params that
are crowding out the page, but maybe on the next pass?
> RFC: Added more swagger annotations, hid others

- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/KubePodConstants.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/v1/V1SpecPodFactory.java
This annotation is set at the time of pod creation. It is being added to unblock work in agent deploy tooling where we need to look up type of the policy by the referenced job.
The type of policy set on the job may change after a pod is created which could render this annotation out of sync. A better approach is to create Disruption Budget CRDs and reference them by jobId. This will be future work.
> Adding a pod annotation for disruption budget policy type

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/service/JobManagerException.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/DefaultV3JobOperations.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/limiter/DefaultJobSubmitLimiter.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/limiter/JobSubmitLimiter.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/integration/scenario/JobsScenarioBuilder.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/limiter/DefaultJobSubmitLimiterTest.java
- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/v3/grpc/ErrorResponses.java
Currently two error conditions are clubbed together in the job submit limiter that makes it hard to distinguish between 
1.  Duplicate job sequence ID submission
2. Max active jobs limit reached.
This code change is aimed at separating the two error conditions into their own JobManagerException error codes. It enables the API to return `RESOURCE_EXHAUSTED` when max active job limit is reached.
> refactoring job submit limiter

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/TaskAttributes.java
- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/JobManagerUtil.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/KubePodConstants.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/KubeNotificationProcessorTest.java
This exposes the effective network mode of a task out via the task
context.
This is "effective" because it represents the actual network mode used
on a task, which is not necissarily what was selected on the job that
created it. (most of the time, is unset!).
> Added task.networkMode context attribute

- titus-server-master/src/main/java/com/netflix/titus/master/jobmanager/service/JobManagerUtil.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/KubePodConstants.java
- titus-server-master/src/test/java/com/netflix/titus/master/jobmanager/service/KubeNotificationProcessorTest.java
Now that the executor is publishing new-style annotations, we no longer
need to read these legacy ones.
This also simplifies the logic on the CP side, because it can take
whatever annotations are set (or not!) at face value.
> Use new annotations instead of legacy ones from the executor

- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/KubePodConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/KubePodModule.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/affinity/DefaultPodAffinityFactory.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/resourcepool/MixedSchedulerResourcePoolResolver.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/resourcepool/ResourcePoolAssignment.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/pod/resourcepool/CapacityGroupPodResourcePoolResolverTest.java
- titus-server-master/src/test/java/com/netflix/titus/master/kubernetes/pod/resourcepool/MixedSchedulerResourcePoolTest.java
This new resource pool resolver, if enabled, will take precidence over
the normal capacity group-based resource pool selectors.
It won't apply to GPU workloads or other more specific things, those
will go to the same resource pools as always.
It contains the hard-coded rule for ram/cpu ratio to provide a
preference for the "best" instance type, but won't actually prevent it
from being scheduled wherever it fits.
----
I'll make PRs for setting the scheduler name and priority class 
like the webhook did (https://github.com/Netflix-Skunkworks/titus-agent-controllers/blob/master/mixedscheduling/router.go) in the next prs.
Example affinity on my dev stack:
``` "spec": {
"affinity": {
"nodeAffinity": {
"preferredDuringSchedulingIgnoredDuringExecution": [
{
"preference": {
"matchExpressions": [ …
```
> Added new MixedSchedulerResourcePoolResolver

- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/KubePodConfiguration.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/KubePodUtil.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/v1/V1SpecPodFactory.java
Porting the webhook logic, this adds a new priority class for reserved/elastic workloads when in mixed mode, as well as setting the actual scheduler name.
I'm pretty sure the scheduler name may be TBD? (@joshi-keyur have you picked it out yet? How about `titus-kube-scheduler-mixed` ?)
----
For titus-kube-common constants, I currently only auto-generate annotations.
I'll make a subsequent PR to do labels and other misc constants like these scheduler names too.
> Added scheduler priority and scheduler name when in mixed mode

- titus-api/src/main/java/com/netflix/titus/api/jobmanager/JobAttributes.java
We don't set a topology skew (constraint) by default for jobs without an availability disruption budget.
> minor fix on the maxSkew attribute behavior

- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/KubePodUtil.java
- titus-server-master/src/main/java/com/netflix/titus/master/kubernetes/pod/v1/V1SpecPodFactory.java
We are slowly dipping our toes into a new world of scheduling with the
introduction of mixed scheduling.
Soon we'll have 1 unified scheduler handling things.
In that world, I do not want users _1_ Red/Black deploy job having to wait
behind 1000 batch jobs that got queued up from a CMB run.
Therefore, I would like to introduce a new priorityclass for service
jobs to run in, that is not as high as those that have reserved
capacity, but higher than batch.
**Someday** we'll continue to expand this function to allow for more
cases, like high priority batch jobs, or preemptable stuff, etc. But for
now I would like to ease us towards the mixed scheduling world.
But I don't want mixed scheduling to be *worse* than the world we have
today, and I think a medium tier will fix that.
Google Doc: …
> RFC: Allow service jobs higher scheduling priority compared to batch

- titus-server-runtime/src/main/java/com/netflix/titus/runtime/endpoint/admission/JobImageSanitizer.java
I'm working on moving docker image validation to titus-kube-validator.
While I'm doing that, I think we can relax this validator just a little
bit.
If there is already a digest, I think we can take the assumption that it
was added in there by titus-kube-validator.
If a user typos the digest, eh? Sure it will pass validation, but then
get expontially backed off or fail.
Either way this protects a bit better against the dreaded
```
TitusServiceException: Job sanitization error in TitusGateway: Image validation error: image=Image{name='drydock/big_data_services', tag='candidate', digest=''}, cause=Did not observe any item or terminal signal within 4500ms in 'map' (and no fallback has been configured)`
```
(granted titus-kube-validator will probably get the same error)
But at least users can …
> Don't bother validating docker images if the digest is specified
